### ISSUE TITLE
Wordpress 5.5 needs SimpleXML php extension

### ISSUE THREAD

**Issue by aaronsql2019** [hestiacp/hestiacp#1011]
I'd like to see the php extension called 'SimpleXML' added to HestiaCP.  This looks like it is a strong recommendation for WordPress 5.5. Here is a quote:

For this to work, you need to render the sitemaps on the frontend and that requires the SimpleXML PHP extension.

https://www.seroundtable.com/wordpress-5-5-google-sitemaps-integration-29829.html

Since HestiaCP appears to be focused on WordPress as one of it's main targets, i'd LIKE to recommend that this PHP extension become enabled, out of the box.

**Comment by jaapmarcus** [comment]
It should be already loaded on default please check if 

/etc/php/{php-version}/fpm/conf.d/20-simplexml.ini exsists

**Comment by ScIT-Raphael** [comment]
@jaapmarcus is right, php-xml is already included as default for every php version, you'll find the reference here: https://github.com/hestiacp/hestiacp/blob/f0eaa05a8628097167725af9daf14a93d2bddc38/bin/v-add-web-php#L57

Due to the fact we already have the module installed, I go to close this feature request now.

**Comment by aaronsql2019** [comment]
Thanks so much. Sorry. I didn't see it
