### ISSUE TITLE
Hestia added mail records without having enable mail selected.

### ISSUE THREAD

**Issue by raouldeheer** [hestiacp/hestiacp#1149]
### In a few words, please describe the issue that you're experiencing:
When I add a new dns zone to Hestia it automatically adds mail records without mail being checked in box or installed.

### What steps did you take when the issue occured? 
1. Click on the DNS tab
2. Click on Add DNS zone
3. Click on list records

### Expected behavior:
There should be no mail records because mail isn't installed nor is it selected.

### Operating system:
Ubuntu 20.04 LTS

### Hestia Control Panel version:
1.2.3 

### Additional notes:
When I installed HestiaCP I didn't install any of the mail options.
And mail doesn't show up in the navbar, so I expected it to be fully disabled.

**Comment by johnnyq** [comment]
@raouldeheer I noticed this as well. 
I believe it does this because new web domains use the default DNS Template as defined in the user profile. 
Although there is a DNS template called no-mail. 
So maybe when a new web domain is added and mail is not checked then it should use no-mail dns template.
This makes sense.
I'm not sure how easily it would be implement though.

**Comment by raouldeheer** [comment]
@johnnyq an option to choose which DNS Template to use would already make an enormous difference.
I don't know how hard it is to make such an option, but it seems possible. 
I've got two servers, one with mail and one without mail, so on the one without mail setting the DNS Template to default-nomail is a solution.
But not for the one with mail, because then I would have to chance the DNS Template in the package every time, I must add a domain with mail.
Placing all the nomail domains on my server without mail also isn't an option because that server is for testing and internal website only.

**Comment by ScIT-Raphael** [comment]
@raouldeheer you can already set the default dns template under user packages. So if you wish to have the nomail template as default on your non mail server, just adjust the default package. Infact there is already a one click solution, I dont think there is any additional modification needed?

**Comment by johnnyq** [comment]
@ScIT-Raphael I still think if you click add web domain and not click "Enable mail for this domain" it should not create mail records in the DNS zone, if "Create DNS zone" is checked.

**Comment by raouldeheer** [comment]
_"Infact there is already a one click solution"_
I don't think constantly changing the DNS Template in the package is the _"solution"_
Some domains need mail and other don't.
Having mail on nomail domain has caused trouble in the past and removing every mail record by hand takes too long.
So I'm wondering what the _"one click solution"_ is.

**Comment by snakehill** [comment]
I don't think having the mail records created anyways is per se wrong, because domain verifications will usually look into such also and will throw errors and warnings if there are none.

However, I feel that if mail is disabled, the records should reflect this.

No imap, mail, pop, smtp and webmail A records should be created as these are redundant.

_dmarc TXT record should be set to `v=DMARC1;p=reject;sp=reject;pct=100;aspf=s`

SPF @ TXT record should be `v=spf1 a mx ip4:[IPv4] ip6:[IPv6] ~all` (without the IPv6 part for now but for when that is supported)

That would add much required security against mail spoofing and abuse also.

**Comment by snakehill** [comment]
I don't think that having the records added is bad per se, but I feel like they should reflect the fact there is no mail, simply for security's sake because it helps against spoofing and other abuse. Many validation services would throw errors without it.

Accordingly, if not checked, the TXT @ SPF record should become `v=spf1 -all`

With the _dmarc TXT record being something like `"v=DMARC1;p=reject;sp=reject;pct=100;aspf=s"`

The A records for `imap`, `mail`, `pop`, `smtp` and `webmail` are redundant and only clutter up the records in case there is no mail.

To change, select and/or remove the records seems to take 16 clicks at the very least, per domain.

**Comment by ScIT-Raphael** [comment]
> To change, select and/or remove the records seems to take 16 clicks at the very least, per domain.

You can also mass select them using the checkboxes in front, but I know what you mean. We will rework the process as soon as we have some free time.

**Comment by snakehill** [comment]
> > To change, select and/or remove the records seems to take 16 clicks at the very least, per domain.
> 
> You can also mass select them using the checkboxes in front, but I know what you mean. We will rework the process as soon as we have some free time.

Believe it or not, but that is including using the checkboxes. It's 17 clicks without haha. But that includes changing up the TXT records.

**Comment by jaapmarcus** [comment]
I think it won’t hurt to allow the selection of an template before creating an mail domain.

For example I use Google 4 Bussiness for some domains I need to manually modify them also mean will there are allready availlable as template. But not before 1.3.0 at least

**Comment by ghost** [comment]
This will be addressed as part of #1281, closing this report but linking for reference.
