### ISSUE TITLE
control panel sends email from root@subdomain.domain.com

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#1165]
Currently the control panel sends email from root@subdomain.domain.com 

This can cause issues. I've tried in /etc/emails-addresses to change it but that had no effect. I'm not sure where this is being set. 

Is there a current way on Ubuntu 20.04 to change that that works that anyone knows of? If not maybe making it easier to change this address, like a box in the configure tab of the CP. Or maybe create  v-change-root-email?

**Comment by jaapmarcus** [comment]
Short answer:

Add `php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f email@domain.com `

to /usr/local/hestia/php/etc/php-fpm.conf

**Comment by ghost** [comment]
I didn't think about that.. I forget the admin panel servers are seperate. Any update will undo any changes. It would be good to have a permanent way to set that.

**Comment by dpons039** [comment]
+1 for this!
It would be awesome if there was a way to set the email or make it use the same email that "admin" user has.

**Comment by schiwe** [comment]
+1 for this please !
Any progress ?

**Comment by ScIT-Raphael** [comment]
It depends on which email you mean, on one side, there is the installation notification which will be sent over mail-wrapper.php (https://github.com/hestiacp/hestiacp/blob/f755067916dfdd844fc0657bf676cf84a86d3556/web/inc/mail-wrapper.php#L30) on the other side, there are the default system notifications sent from cron. There are aswell parts like the inform function about new user or mysql account which generates a mail over the same mail-wrapper.

Personaly, I think hestia@host.domain.tld isnt a bad sender, because on email@domain.tld you would probaly have an active spf record which will block the e-mails aswell.

Can someone exactly describe the need and why it should changed? Where would be the advantage if it would be for example the admins e-mail address?

**Comment by jaapmarcus** [comment]
@ScIT-Raphael  I agree how ever:

Received: from root by monitor.domain.nu with local (Exim 4.92) (envelope-from <root@ monitor.domain.nu >) id 1kOSbb-0003OV-L3 for me@xxxx.nu; Fri, 02 Oct 2020 23:28:43 +0200

Where monitor.domain.nu = hostname.

**Comment by ghost** [comment]
> It depends on which email you mean, on one side, there is the installation notification which will be sent over mail-wrapper.php (
> 
> https://github.com/hestiacp/hestiacp/blob/f755067916dfdd844fc0657bf676cf84a86d3556/web/inc/mail-wrapper.php#L30
> 
> ) on the other side, there are the default system notifications sent from cron. There are aswell parts like the inform function about new user or mysql account which generates a mail over the same mail-wrapper.
> Personaly, I think [hestia@host.domain.tld](mailto:hestia@host.domain.tld) isnt a bad sender, because on [email@domain.tld](mailto:email@domain.tld) you would probaly have an active spf record which will block the e-mails aswell.
> 
> Can someone exactly describe the need and why it should changed? Where would be the advantage if it would be for example the admins e-mail address?

if you use the new global relay and you don't program this root email that is a subdomain and not likly the one you actuall use it causes issues with the relay not liking random emails from not setup addresses

**Comment by jaapmarcus** [comment]
We have added a smtp relay for internal mail 
https://github.com/hestiacp/hestiacp/pull/1988

**Comment by ghost** [comment]
Just read that now. Interesting ty.
