### ISSUE TITLE
Feature Request: Optional: Old and New Login Forms

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1178]
I noticed the login form changed to offer better security.
You now enter the username then click next then enter your password then click login. 
I understand the security behind it, hence bots can't guess username and password combos at the same time easily. 

We use a password manager to auto fill the data for us, but we have to click autofill but each time for the user and password. This has caused a little bit of annoyance as we are in and out of the panel quite often.

One way to eliminate the threat is 2 factor Auth which Hestia supports and we use.

So my suggestion is to make the new login optional in the control panel settings, but still keep it on by default to keep a default secure environment.

**Comment by mehargags** [comment]
pls vote for this in the already existing thread... that'd help devs track it better.
https://github.com/hestiacp/hestiacp/issues/1071

@ScIT-Raphael can you merge it there pls?

**Comment by ScIT-Raphael** [comment]
As already written in #1071 we had to rework the login process due to the load issue on 2fa validation which could lead to a dos. There is currently no way back to the old login form because of that issue, I can confirm the issue with the password managers, basicly you'll need to insert the username, on my side I can choose the password from my list (google chrome).

A possible fix would be to implement the login form like google or microsoft does it, if anyone knows how, please feel free to provide a pull request!

For now, I'll leave the issue open and have a look, if we can optmize the current form to allow the use of password managers with the right field detection.

**Comment by ScIT-Raphael** [comment]
@mehargags sorry, I'm not able to merge issue reports, but they are linked now.

**Comment by neto737** [comment]
I can see some possibilities here:

Why not in the first screen validate user/password and then redirect to a “new” form to validate the OTP code?

Or simply put the OTP field in the login form and check if the 2FA for that user is enabled or not and then validate it.

Also can be added a checkbox to show/hide the OTP field.

Only some ideas, I would like to help with that but I think that this kind of change should be discussed before being started.

**Comment by jaapmarcus** [comment]
The form we used for "1.2.0" won't come back:

We where able to push up the server load to 60/70% by manually guessing usernames/pressing random keys.
Also I had multiple issues with both systems with keychain (OsX) continuing to the "check" instead waiting for the answers.

How ever a middle ground would be this...

<img width="564" alt="Screenshot 2020-09-26 at 18 15 56" src="https://user-images.githubusercontent.com/9754650/94345204-84b1ce80-0024-11eb-8370-2e878cc36134.png">

And then forward to the "One time pin" form

<img width="699" alt="Screenshot 2020-09-26 at 18 40 59" src="https://user-images.githubusercontent.com/9754650/94345677-f50e1f00-0027-11eb-8f55-ab8a9ebe36bd.png">

**Comment by jaapmarcus** [comment]
Created an pull request:
https://github.com/hestiacp/hestiacp/pull/1232

**Comment by ScIT-Raphael** [comment]
merged.
