### ISSUE TITLE
[Bug] Password generation issues installers

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#1184]
After the release of the new password generation users reporting issues with password generation.

https://forum.hestiacp.com/t/installer-password-generation-issue/1601/25
https://forum.hestiacp.com/t/unable-to-add-database/1705/8

<img width="350" alt="Screenshot 2020-09-13 at 14 26 37" src="https://user-images.githubusercontent.com/9754650/93018591-2b33b380-f5d1-11ea-8c0b-b859ff538994.png">

**Comment by jaapmarcus** [comment]
Fixed when we release new version.

**Comment by kpapad904** [comment]
Just a quick reminder that HestiaCP could consider pwgen [1][2] (created by long-time Linux dev Theodore Ts'o), instead of manually feeding /dev/urandom to transformation functions.

Pwgen is very small, doesn't drag along any dependencies and is available for all Linux flavors since many years. It can be particularly useful when generating passwords for end-users.

[1] https://packages.debian.org/source/buster/pwgen
[2] https://github.com/tytso/pwgen

**Comment by jaapmarcus** [comment]
Fix of #1191 seems to be working fine
