### ISSUE TITLE
Dependency Error with Upgrade 1.2.4 to 1.3.0 (beta)

### ISSUE THREAD

**Issue by Red3Tango** [hestiacp/hestiacp#1260]
### In a few words, please describe the issue that you're experiencing:
When upgrading to 1.3.0 (beta) there is an unresolved dependency error that does not get resolved automatically.

### What steps did you take when the issue occured? 
1. Fresh (limited) install of Debian 10
2. Install Hestia 1.2.4
3. Install php_7.4.10-alpha and nginx_1.19.2-alpha
4. Upgrade to 1.3.0 (beta) using `v-update-sys-hestia-git hestiacp main install`
-fix-
5. Run `apt-get --fix-broken install` after dependency failure.

### Expected behavior:
Resolve dependency errors for missing package and install.

### Operating system:
Debian 10 (Buster)

### Hestia Control Panel version:
1.2.4 -> 1.3.0 (beta)
hestia-php_7.4.10-alpha
hestia-nginx_1.19.2-alpha

### Additional notes:
```
Preparing to unpack .../hestia_1.3.0~beta_amd64.deb ...
Unpacking hestia (1.3.0~beta) over (1.2.4) ...
dpkg: dependency problems prevent configuration of hestia:
 hestia depends on zstd; however:
  Package zstd is not installed.

dpkg: error processing package hestia (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hestia
```

**Comment by jaapmarcus** [comment]
I will close the issue. This is caused due to the fact 1.2.4 doesn't require zstd and 1.3.0 (beta) in this case does.
It will be fixed when we publish the packages official packages. As apt will handle it self. dpkg isn't able to handle it propperly.

As noted in https://forum.hestiacp.com/t/1-3-0-rc-we-need-you/1673

But any way thank you for reporting.
