### ISSUE TITLE
Top and (htop) non showing processes

### ISSUE THREAD

**Issue by roccomilluzzo** [hestiacp/hestiacp#1320]
After the update to the latest hestia vesta users (admin and custom ones) are not able to see running processes via top and htop, it works only if you use root or call it via sudo.

This has happened into 3 different servers in different farms

### Operating system:
Debian 10

### Hestia Control Panel version:
 1.3.0

**Comment by ScIT-Raphael** [comment]
Hi

This is not a bug, it is by design. The output of proc has been limited due to a security issue (Fixed a security issue where user password reset keys could potentially be gleaned from system process list - thanks RACK911 LABS): https://github.com/hestiacp/hestiacp/commit/47d375ca7fb59844ed156e246e44258cfc8ba1d3
