### ISSUE TITLE
not sure where the group is. trying to add comments and case got closed. 

### ISSUE THREAD

**Issue by Johnzapf** [hestiacp/hestiacp#1381]
Just trying to add info/comments about the 1.3.1 RC and case got closed, don't know where to go to easily do this?

also still trying to work through the SSL error thing...

![Capture](https://user-images.githubusercontent.com/36643715/99196544-d4b63300-2741-11eb-8a3f-2ea6e652cd82.JPG)

**Comment by cmstew** [comment]
Hey,

GitHub is for issue reports and feature requests. This will be closed soon because it's off topic.

Those icons are infinity symbols and mean that you are using for example 11 out of unlimited Cron jobs according to the selected package.

Please continue to use the forum for your SSL question. As far as we can tell, SSL is working fine. All the maintainers run Hestia on their own servers too and don't experience the problem you're mentioning. So it's likely an isolated issue. If you can show us a way to reproduce it, feel free to open another issue on GitHub and please use the template provided for filing your report. It gives us helpful information to help us troubleshoot.

The best place to give feedback is on our discord:

https://discord.gg/nXRUZch

**Comment by jaapmarcus** [comment]
If you edit the package size it should work fine. 

<img width="1058" alt="Screenshot 2020-11-16 at 00 50 54" src="https://user-images.githubusercontent.com/9754650/99200496-f6490600-27a5-11eb-9aae-e7bc23dedc05.png">

**Comment by Johnzapf** [comment]
I am not a HestiaCP god, have no clue what edit the package size means

________________________________

**Comment by cmstew** [comment]
Please move to discord for further questions, comments, and discussion.

Click this button to see the default packages. It is only available from an administrative account.

<img width="1090" alt="Screen Shot 2020-11-15 at 5 02 05 PM" src="https://user-images.githubusercontent.com/8193597/99200784-a007a300-2764-11eb-94f7-5bcf02716ff5.png">


Again, here is the link to join:

https://discord.gg/nXRUZch
