### ISSUE TITLE
Git CI

### ISSUE THREAD

**Issue by tojorodialson** [hestiacp/hestiacp#1402]
Hello,
Is possible integrate GIT automation in Hestia?
Why not with name of user you must remove underscore? Example: **admin_user** become **user**
Thank you
Tojo

**Comment by ScIT-Raphael** [comment]
`Is possible integrate GIT automation in Hestia?`
Please explain more.

`Why not with name of user you must remove underscore? Example: admin_user become user`
Don't understand here aswell, what you mean...

**Comment by tojorodialson** [comment]
Example the Git automation is similar in plesk for see change real time project
In username, I have admin_user and why you use a predecessor before name? Its simple use user but not admin_user

**Comment by jaapmarcus** [comment]
You mean for us database / ftp account?

<img width="665" alt="Screenshot 2020-11-18 at 10 56 22" src="https://user-images.githubusercontent.com/9754650/99515033-b8f29d00-298c-11eb-8e74-ab60db737008.png">

In 1.3.0 and before if you used admin_admin edit database became mangled / broken. The fix should sync the behaviour for edit/add database (and ftp)

**Comment by tojorodialson** [comment]
The both

**Comment by ScIT-Raphael** [comment]
I think we got some language barrier here. You probaly mean this feature here: https://docs.plesk.com/en-US/obsidian/customer-guide/git-support/using-remote-git-hosting.75848/

Would need a lot of development, which we currently don't have time for. If you would like to see this feature, we are open for any pull request.

About user definition: We have a multi user environment, so if another user want to create "cms", he can't, because the user has already be used. So adding user_ in front, will solve this issue and should be common, also in other hosting panels. Just in case you mean this :).

**Comment by ScIT-Raphael** [comment]
Closing because answered, please let me know if you have any additonal questions.
