### ISSUE TITLE
 I uploaded it to my server but login error

### ISSUE THREAD

**Issue by yvzcvdm** [hestiacp/hestiacp#1434]
I cannot login in the application because the / home / user / tmp folder does not have write permission. I need to allow with the help of consol. Can you fix this error.

**Comment by ScIT-Raphael** [comment]
First of all, issue report isnt decoration, it would give us some additional informations about your system. But in the current case, you're in the wrong system because it is not a hestia issue which we could fix. I would suggest to switch to our forum to get help from the community (https://forum.hestiacp.com).
