### ISSUE TITLE
[Feature Request] Set start date and end date to the email autoreply.

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1468]
It is self-explanatory.

Just set so yo dont have to remember to reactivate after your holidays.

**Comment by johnnyq** [comment]
Good idea @jlguerrerosanz +1

**Comment by ScIT-Raphael** [comment]
Hi @jlguerrerosanz 

We just discussed your request in our dev chat: an implementation would be not easy at all, also mail is, due to the current o365/gsuite situation not our primary target.

If you would like to see this function, please feel free to provide us a PR - we would love to review, discuss and implement it!
