### ISSUE TITLE
[Feature Request] - Use server as Web + DNS Slave

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1481]
### In a few words, please describe the issue that you're experiencing:
When I try to add a web domain on a slave DNS server of a DNS cluster Hestia does not allow me to do it because the DNS zone exist (because of the slave)

### Additional notes:
I already know that to make that work you would have to rewrite a lot of code so I would suggest a different approach.

How about **if we configure a server as DNS slave we disable all DNS management capabilites of the web interface?** So we can safely use the server for both services.

**Comment by jaapmarcus** [comment]
As also told in the forum this has been by design and we can't really suite the exact need of every body.  There are maybe other Control panels that suit this needs... 

In the case of most users are using them: 

Server A: Web + DNS + DB + Email  + DNS Slave for B
Server B: Web + DNS + DB + Email  + DNS Slave for A 

Or just rent 1 or 2 "small" vps servers in a different network for a few dollar / euro and act as 2nd / 3rd DNS server / Slave. The 5 euro that costs me to rent an other vps in an different network is me personally fully worth.

This is according the standards any way the preferred way. 

Even if we "decide" to disable the DNS capabilites we will still get in problems that multiple systems need to adjusted.  And it could break current installs.  And this is probably the last thing what you really want. 

Also our time is as any opensource project is  limited and other issues have an higher priority we don't think there is an high demand for the is issue...

**Comment by jlguerrerosanz** [comment]
Thank you. I understand.
