### ISSUE TITLE
[Feature Request] - Check DNS records before saving / publishing

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1518]
I have made serveral mistakes today.

- I set an IP in a CNAME field.
- I also forgot to put the "." at the end of a CNAME record: "xxx. -> CNAME -> yyy.mydomain.com**.**"
- I also copied and pasted the "." in the IP field of an A record.

I would like either:
- Have the option to review the DNS zone before going "live".
- or to have a warning or autocorrect if I forget the "." or add an inncesary "." after the IP

**Comment by ghost** [comment]
We will review the error checking that is currently in place for DNS records, however it is up to the domain administrator to verify that their DNS records are configured correctly.

**Comment by jtraulle** [comment]
It would be great to either :

- generate a temporary new zone and check it with named-checkzone and prevent the user to add an invalid record if the resulting zone file is invalid (for example adding a CNAME record when another record already exists)
- emphasis on the UI that the zone is in error and has **not** been reloaded

In fact, there is no way at the moment to know if all the records presented in the UI are served or not because of an error besides checking `/var/log/syslog`.
