### ISSUE TITLE
[Feature Request] - Bulk apply ipset to Firewall rules

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1551]
To apply an ipset to a firewall rule you have to edit them one by one.

From here: https://sub.domain.com:8083/list/firewall/

You should be able to check the rules and then apply ipset to the selection.

**Comment by jaapmarcus** [comment]
There is still an open bug report regarding the issue. https://github.com/hestiacp/hestiacp/issues/1472
Until this has been fixed the issue is duplicate...

Also the current team only consist out of about 6 active persons and they do it mostly as an "side" project next to their day job. The have decided to share the "result" for "free" / AS IS that was caused by this "side" project and there is currently not enough development power. If you really want to add a new feature please create a pull request in that case we will review it and maybe consider adding it. 

https://github.com/hestiacp/hestiacp/issues/1550 

As you can't just "attach" an ip set to a rule it will be a rewrite of the current admin system / design. For this there is currently not enough "man" power available as it will result in a lot of work...

**Comment by jlguerrerosanz** [comment]
I know I ask for many things and make lots of suggestions. This is my way of contributing. 

I am suggesting things that I think would be useful to me and other people. I know there are only a few of active programmers working and I would love to help but programming is not in my skillset. I will sign up for the 1.4 beta test program.
