### ISSUE TITLE
[Feature Request] - Show sent email count next to domain in list

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1552]
When you list users, you don't know if one has a compromised password and is sending spam.
https://sub.domain.com:8083/list/user/

If we showed the email count we would know:

grep -oP "A=\K([A-Za-z0-9_.:@]+)" /var/log/exim4/mainlog | sort | uniq -c | sort -nr

Alternatively we could have an email report under statistics.

If you want to show only domains or email accounts over a longer period of time and above a certain thereshold:

gunzip -c /var/log/exim4/mainlog*.gz | grep -oP "A=\K([A-Za-z0-9_.:@]+)" | sort | uniq -c | sort -nr | awk -v limit=50 '$1 > limit{printf ("%8s\t%s\n", $1, $2)}'

**Comment by ScIT-Raphael** [comment]
Just one wish: Please stop "thumbs up" your own issue requests, this is so weird :).

**Comment by ScIT-Raphael** [comment]
Just some first thoughts:

- Listening under user seems to be the wrong place, when we should implement it, then under the mail section.
- Running it on every visit would slow down the page view, if there are more than testing mails. A solution would be to add it to the daily statistics cronjob.
- Function doesnt make a real sense, expect you got spamming users - then just a list would be the wrong thing to display that behaviour.

Personaly, I don't see any advantage of it, but we will discuss it in the team.

**Comment by ScIT-Raphael** [comment]
Also with eximstats there is already a function providing statistic informations: https://www.exim.org/exim-html-current/doc/html/spec_html/ch-exim_utilities.html#SECTmailstat

**Comment by jaapmarcus** [comment]
Currently the only place where you can see is under:

/list/server/?mail

**Comment by ghost** [comment]
I think listing a emails sent in the last 24 hours # somewhere would be a good safety feature. I know that my email logs show over 1000 attempts to log into each server, appliance and app I administer. I think everyone I know in my line of work is basically looking at logs with nothing but dictionary attacks. They do break into servers, and use them to spam, this would help ppl catch if they were compromised. It would also help catch users whos web site/cms was compromised. As a "hosting" panel if you host users they could get hacked and use to send spam.

**Comment by jlguerrerosanz** [comment]
Yes! That's the point.
One client went to a phishing portal faking roundcube and gave her login credentials.
My server got sending only 1.000 scam emails per day for over a week until it got blacklisted.

I need an indicator to know if the server is sending spam has been compromised before it gets listed.

**Maybe scan with clamav smtp messages and show a warning to the admin in the panel would suffice. Or a bounce email to sent to the user.**

**Comment by jaapmarcus** [comment]
We do all ready supply with an email report generated via eximstats. 

https://github.com/hestiacp/hestiacp/blob/0fdfc846cd3b538e9a8bae4f360e04f0aab606ba/web/list/server/index.php#L95
and
https://github.com/hestiacp/hestiacp/blob/0fdfc846cd3b538e9a8bae4f360e04f0aab606ba/bin/v-list-sys-mail-status#L37-L42

So the question to ask would it benefit to place the information more clear....

I know via Directadmin the administrator would have an list how many Email has been send in the last 24hours in the "User" overview if we want to ask this is probally the best location. Not with an extra list that nobody uses:

<img width="1121" alt="Screenshot 2021-01-13 at 13 45 55" src="https://user-images.githubusercontent.com/9754650/104454412-1b8ba200-55a6-11eb-8534-33944d8340c5.png">

This can be "generated" during statics cronjob. It will give the user some basic knowledge the user knows. If the numbers show something strange admins can always contact an certain user / or take any actions 

Any other location is probably not "useful" as nobody is going to check 50 users on a daily basis.

**Comment by wojsmol** [comment]
@jlguerrerosanz Directadmin also send mail to user and administrator when user reaches daily limit and second during stats generation.

**Comment by shaneshuford** [comment]
If you decide to add a sent emails count to the users list, why not also consider adding a received emails count column as well? I use hesita for personal project use and check each of my user accounts for inbound emails daily.

**Comment by jlguerrerosanz** [comment]
@wojsmol that would be wonderful! So that the admin doesn't have to set a cronjob to monitor that stuff.
@jaapmarcus the place you are suggesting is perfect.

I would be very happy with this. But as you know I always ask for more just in case...

- If we get a "hit" we will want to dig further. Can we then provide that information in the email accounts overview for a domain? So that we know exactly which accounts are above the thereshold.
- We would also need to edit a config file or have a GUI to set the thereshold to trigger the alarm. I don't know if Directadmin does that for us.
- And maybe we want to set a different level for each domain or a don't trigger policy for some domains.

Thank you very much for your time

**Comment by ScIT-Raphael** [comment]
Just to write this up a bit: Such a statistic information would not be enough to inform you about a hacked domain or account, which spams around from your server. It basicly will not inform you and as @jaapmarcus already pointed out, you will not look on it every day. **tl;tr:** Not usable for sending spam detection.

Also we already ship hard coded sending rates with the exim configuration for php scripts:
https://github.com/hestiacp/hestiacp/blob/main/install/deb/exim/exim4.conf.template#L87-L95

aswell as for registered users:
https://github.com/hestiacp/hestiacp/blob/main/install/deb/exim/exim4.conf.template#L128-L133

So sending thousands of emails in a hour would be basicly not possible.

So what we are talking about: The current statistic value would be per domain, probaly loaded from eximstats. As written, it is only statistics, it will not help to detect mass sending attemps.

If you want to have such a function like configure rate limits for every email domain, which will also email report you potential abuse, you'll need to provide it on your own. The current available timeframe isnt that high to provide such a complex function, also leaving the issue report open would help, just due to the fact, that we will not have enough time to resolve it. So it will stay open for months or years without finishing it - in our point of view this should not be the target.

So the current question would be: Do we need such a statistic function, due to the fact of "good to know"? If yes, we probaly can expand the statistic cron script for the mail domains and show it in the overview, that part should be possible.

**Comment by jaapmarcus** [comment]
There is an old feature request for sending Quota limit that past so sending an email when past the xxx quota defined in the package is an option. 

https://github.com/hestiacp/hestiacp/issues/428

Due to the age it should is not the highest priority

**Comment by ScIT-Raphael** [comment]
We currently close this issue - with the existing system we do not want to implement this request. This may be integrated, if we find enough time to do a whole rewrite of the interface.
