### ISSUE TITLE
Why should wait more than 3 hours for just restore emails, can we can skip this step, from cli

### ISSUE THREAD

**Issue by hummans** [hestiacp/hestiacp#1554]
i m trying to restore a backup from vestacp on commandline
but i m waitting more than 3 hours just for email restore 
i do not have any email account just more than 80 subdomains with one website

please fix this

Thank You

**Comment by ScIT-Raphael** [comment]
There is no known issue, probaly your restore is stuck because of something. Please consider to use https://forum.hestiacp.com or our Discord channel for general support.

Github is for issue reports, based on the issue template and more informations which let us reproduce your issue, so we could fix it. In your case, it currently sounds like a community support case. If we should get additional informations from you which leads to a bug, we will for sure fix it - but in the current state, I'll go to close your issue report.

**Comment by jaapmarcus** [comment]
v-restore-user  USER BACKUP [WEB] [DNS] [MAIL] [DB] [CRON] [UDIR] [NOTIFY]

v-restore-user  USER BACKUP yes yes no yes yes yes yes yes 

Probally
https://docs.hestiacp.com/cli_commands/commands.html#v-restore-user
