### ISSUE TITLE
[Feature Request] - Move all email messages to a different account

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1557]
Sometimes a client has fired an employee and wants to delete email account but not lose the messages.

Expected behaviour:
- Visit origin account
- Click on "move all messages to a different account"
- Confirm

After that, an admin can set aliases or delete the account.

I thought about a "merge account" option but it is more limited and the real difficulty is to move the messages not to do the other stuff.

**Comment by jaapmarcus** [comment]
I searched the Hestia forum there hasn't been a request for merging an account in the past 2 years. Also on the forums of VestaCP there was in the past no need for it.

But it can be done via CLI
  
Creating such option would mean we spend about a few hours on a function:
1. That is very niche feature that probably will be not used often.
2. This can be done via CLI:
`cp -R /home/username/mail/mydomain.com/abc/{cur,new}/ /home/username/mail/mydomain.com/xyz/`
3. And could cause other issues where users accidentally merges a certain account.

Also our main focus is to keep the current system basic as possible however add certain functions will improve the overall experince of Hestia Users. We don't need to replace all CLI commands in a system. And we should set priority to functions / features that will be used by most of our users or could be considered use full. 

Any good (new) feature discussed on Discord or Forum will end over here as this is the best way to keep track of all those features. 

I would prefer "waste" my time on a feature that is used by 50% of all Hestia users then a feature that has almost no use cases.

**Comment by jlguerrerosanz** [comment]
Thank you for taking your time to explain your answer. I know that only 20% of what I suggest will end being considered and I am happy with that.

**Comment by jaapmarcus** [comment]
The "80%" still creates a load that also could be spend on development instead.

**Comment by jlguerrerosanz** [comment]
Among all the things you can do, you are choosing to take your time and answer me. Which I appreciate.

**Comment by jaapmarcus** [comment]
To keep overview and prevent good issue / features to be lost in the "List" of never completed issue list we try to keep the list as short as possible. 

Closing an issue with out even considering / answer is not the way we want to work and we got multiple bad reviews in the past on our private personal/company accounts via Google and other review sites because users didn't like that we closed an issue. 

If you really want to help creating feature request for simple things tasks that can be done via CLI isn't the best way possible. We really don't want to become "I can do everything" control panel with "1000" features that aren't used at all.  I the next few weeks we provide an early beta version that need to be tested. Also shortly after the beta build is / has been made translations need to be done and many more tasks things needed to be done.
