### ISSUE TITLE
Feature Request: max_children setting

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#1573]
I get the following errors in /var/log/php7.4-fpm.log
`
[16-Jan-2021 18:22:59] WARNING: [pool host.somedomain.com] server reached max_children setting (8), consider raising it`

There is no where on the WebGUI to increase this value and would be a great addition

here is a post on the forum about but no ticket was evert created

https://forum.hestiacp.com/t/php-fpm-max-children/1905

In the meantime what file would i edit to change this globally without breaking anything, much appreciated

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/issues/919

This feature will implement the same idea 

It will allow you to set certain php settings via the GUI

**Comment by jaapmarcus** [comment]
If you want to change it globally you will need to create a new template with the increased values. I am against creating an "Site wide" options as it would mean time spend doesn't match the extra effort to build in for all domains

Also the default settings are fine for 90% of the use cases

**Comment by ioannidesalex** [comment]
@johnnyq  For the moment you may edit the max_children value in the conf files located at /etc/php/<phpversion>/fpm/pool.d 

However the changes will be lost on hestia upgrade (at least for now).

**Comment by CryptorClub** [comment]
Guys, thank you for working on hestia cp. It's great!

I'd like to share my experience after 24 hours pain. I've migrated my site from Vesta CP, that has live users and traffic. That was suddenly because of suspension of previous hoster. Anyway. 
With same configuration server even better. 
From Ubuntu 18 to Ubuntu 22
From (Apache + Nginx + FastCGI) to (Apache + Nginx + PhpFpm)

I'm new to PhpFpm and pain was a lot, while to load simple cache on php needs ~10 seconds.

Choosing exact version X.X of php in Domain configuration in panel.
Than modification of `pm.max_children` line from 8 to 1000 in
`/etc/php/X.X/fpm/pool.d/domain.name.conf`
than 
`sudo systemctl restart phpX.X-fpm` command in terminal

helped!

Anyway. This feature should be in panel, because, this will reduce pain for other Admins.

Best wishes and growth!

**Comment by jaapmarcus** [comment]
There is already a feature request for it...

https://hestiacp.com/docs/server-administration/web-templates.html#how-can-i-change-settings-for-a-specific-domain

Also create a new template and don't modify the existing configs.

**Comment by CryptorClub** [comment]
That's good. Modifying template is better. 
Increasing pm.max_children (more than 8) at least for admin user by default would be also good thing.
> There is already a feature request for it...
> 
> https://hestiacp.com/docs/server-administration/web-templates.html#how-can-i-change-settings-for-a-specific-domain
> 
> Also create a new template and don't modify the existing configs.

**Comment by ioannidesalex** [comment]
What's your usecase for increasing pm.max_children (more than 8) for admin user?

**Comment by CryptorClub** [comment]
> What's your usecase for increasing pm.max_children (more than 8) for admin user?

Thanks for reply and collaborating in Hestia project.

My usecase, that I need only one site for whole panel, because using it for myselt as UI to manage this site. I'm not planning to create other users in nearest future and not planning use hestiacp as hosting panel (for this one site in sightseeing future on this VPS). And the feature is to get powerful user from the start (I'm read, advice to create another user for working site. Possible, that not understand all risks... In this case the pain appears after creating child users and Administrator little bit easier find possibility how to compare config between child and admin user for site perfomance, while using site on admins profile). As I wrote before, I've migrated from Vesta with live site and stuck on few things one of this - is this line, that as result produce 24 hours of pain, until solution was found. 
I like your panel as new birth from Vesta and want to reduce this pain, if similar usecases for other users will be. 

The second thing(1 hour of pain), that stuck on migration, that possible need to open and explain in another issue for feature. Is existing parameter in .htaccess file (for php.ini max.size request), that returns 400 error for whole site. You may ask, I will create another issue with little more details to reproduce.

Best wishes, growth and happy developing.

**Comment by ioannidesalex** [comment]
I understand your usage. However:
- it is bot advised to run websites via admin user
- your usecase is not so common, thus it cannot be the default.

But, you have the flexibility to create your own php-fpm template and use that one.
