### ISSUE TITLE
Feature Request: hestiacp, exim, and dovecot use letsencrypt

### ISSUE THREAD

**Issue by howarddavis** [hestiacp/hestiacp#160]
### Operating System (OS/VERSION):

All Supported

### HestiaCP Version:

Current Stable

### Feature Request:

Functionality to check for the FQDN of the server within all websites, see if letsencrypt cert exists, if exists use letsencrypt cert for each hestiacp, exim, and dovecot where it will be updated along with the website.

Maybe just check in the admin's websites for the FQDN, but have an option on the Server Settings to choose a different user that hosts the FQDN along with an override for the letsencrypt cert if it doesn't exist.

something like

if (exists(FQDN.letsencrypt.cert)){
    use FQDN.letsencrypt.cert for hestia, exim, & dovecot
} else {
    use default cert for hestia, exim, & dovecot
}

see forum post that uses built in functionality of vestacp

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?f=10&t=17353&sid=5afd6ecfd9668cd77559db939311b5e3

**Comment by ioannidesalex** [comment]
I think what is mentioned in the forum thread is already implemented in Hestia. Not 100% sure though.

**Comment by howarddavis** [comment]
the function to do it via cli is there, I'm asking for a way via the control panel itself

**Comment by ScIT-Raphael** [comment]
We plan a complete rewrite of the backend with a feature release. Because we still search for missing webdesigner, this plan is a bit delayed.

Also the request for a gui option for creating server let's encrypt cert does exist already and will be implemented in the new backend. For now, I will close this issue/feature request. If you've any additional comment, feel free to reopen it!
