### ISSUE TITLE
[FEATURE] - make hestia cloudnative

### ISSUE THREAD

**Issue by leolios** [hestiacp/hestiacp#1610]
I've been using HestiaCP for several months in lab mode on the infras of several dedicated servers, I realize that it corresponds to my expectations in terms of web hosting or even more on some ideas or I wish to contribute, however today, working in software engineering, my production needs are more demanding especially on the importance of making HestiaCP cloudnative as much as possible by using it in a Docker container. 

- [x]  I would like to make a contribution this week by making HestiaCP cloudnative, first of all by trying some very simple use cases, for example just running Hestia from a container.

2.  As an alternative if that falls through I've been thinking about Kubernate to see other solutions to make it available on the cloud.
 
- In the long run, I would like this solution to allow me to be more efficient on the field and why not propose to go further once the cloudnative is crossed.

I forked the project to start developing this part.
I'm going to add the issue with its linked number to make it easier to trace my proposal and the proposed improvement.

You can find me on the Discord under the nickname Léolios, last year I did the translations in French and I have some ideas to improve Hestia which seems to me a great project!

This year I would like to bring my ideas of improvement to bring my little stone to the project. I underline that this contribution is also with the framework of my school in Bordeaux.

Definition EN => [CloudNative](https://docs.bluekeys.org/guide/dev/technologies/cloud-native-definition#english)
Définition FR => [CloudNative](https://docs.bluekeys.org/guide/dev/technologies/cloud-native-definition)

**Comment by jlguerrerosanz** [comment]
Why is it so important for you to put Hestia in a docker container?

What is the specific use case that you are thinking of?

**Comment by leolios** [comment]
Good evening, I invite you to read the link I put at the bottom of the previous message that explains what cloudnative is to already understand the context I'm in.

This will answer most questions :)

**Comment by susinths** [comment]
@leolios  Did you have time looking more into it?

**Comment by thiagoalcav** [comment]
Maybe he wants something like this: https://hub.docker.com/r/niiknow/vestacp/

But I think that containerizing the server doesn't bring that much gain. It would eventually become a dockerized monolith. However, it might be interesting to think about adding orchestrator features to Hestia. In this context, mariadb, dns, mailserver, firewall etc. they would become containers configured to interconnect.

We would perhaps have a screen where you can list and perform basic tasks like stopping, restarting containers, viewing logs and a specific option in the DNS module so that you can use it as a proxy for new services. So a new DNS could be a redirect to a container.

Or just have this redirect option and manage the Docker images through https://www.portainer.io/

**Comment by jaapmarcus** [comment]
https://github.com/Steveorevo/hestiacp-dockered
