### ISSUE TITLE
[FEATURE] - make more test and refacto + CI

### ISSUE THREAD

**Issue by leolios** [hestiacp/hestiacp#1614]
Following a conversation about Discord it seems interesting to add tests and also to restructure the functioning.

[Link Discord](https://discord.com/channels/737721354937303161/738055454285889597/804707916346425364)

It seems more coherent to me to cut the tests by file and context, then add new ones.

This will make it possible to better divide up the operation as recommended by good software development practice in quality, this avoids making a complete regression of the tests following an error in a single file. We can speak of the S.O.L.I.D principles in object-oriented programming as an example of good practice.

My goal will be :

- [x] split the tests
- [x] add one or two tests
- [x] I have some ideas for a CI for the tests I will try the experiment on my fork.

Later add more.

**Comment by jaapmarcus** [comment]
Since the issue has been added we have allready implemented 

- Shellcheck 
- PHP Linting
- Bats testing + added a lot of new tests including tests that hasn't been done before.

Feel free to add more tests if you want. As we currently use Drone.io for as long tests are able to run in a docker container it should will probally work fine
