### ISSUE TITLE
[BUG] Backup script does not account for exclusions when checking for available disk space

### ISSUE THREAD

**Issue by arharp** [hestiacp/hestiacp#1616]
**Describe the bug**
When the backup script runs, it does not factor in any exclusions in the user's backup configuration when determining if there's enough disk space available.

**To Reproduce**
I have a user whose account uses 20 GB of storage. My server's drive is only 30 GB, but I still would like to backup most of the user account, including the databases, mail accounts, and config files. I have setup an exclusion for the folder containing the bulk of the data (around 18 GB of data), but when I run `v-backup-user username` I get a message saying `Error: not enough diskspace available to perform the backup.`.

**Expected behavior**
The script should still backup the user since the exclusions reduce the amount of storage required to create the backup.

**Operating system:**
Debian 10.8

**Hestia Control Panel version:**
v1.3.2

**Comment by jaapmarcus** [comment]
Know issue but probally hard to solve. We currently calculate the "needed" disk space by summing up the values in  user.conf

**Comment by jlguerrerosanz** [comment]
I would suggest to add a "FORCE" parameter so if you force the backup it will do it overriding this check

v-backup-user username [param1] [param2] --force=yes

**Comment by jaapmarcus** [comment]
Doesn't work for automated backups

Of we have to allow it also for v-backups-users 

Prefable the "way" should be calculating the available disk space with out the folders

**Comment by arharp** [comment]
Couldn't you use `du` to calculate how much space is actually being used? It makes it a little more complex and would take a little longer to calculate, but it could be done. Another option would be to use the value in user.conf unless there are exclusions set for the user account. If there are exclusions, you could then use `du` to check the actual disk usage.

**Comment by jaapmarcus** [comment]
Fixed it will be released in 1.4.3

**Comment by xtrime-ru** [comment]
HI!

Im having issues with backup after this fix: https://github.com/hestiacp/hestiacp/pull/1875
Im using v1.4.9. And start getting emails with: `not enough diskspace available to perform the backup.` 

There is enough free space, and little backups:
![telegram-cloud-photo-size-2-5206272624097867027-y](https://user-images.githubusercontent.com/34161928/127903527-ad16fbfc-6f40-480a-ab2e-a6578c617388.jpg)
![telegram-cloud-photo-size-2-5206272624097867028-y](https://user-images.githubusercontent.com/34161928/127903540-0f147e7d-5f78-4aae-9e66-150f0aad6b5b.jpg)


To hotfix this issue i've changed multiplier from 2 to 1:
```shell
let u_disk=$(($(get_user_disk_usage) * 1))
```

How can i solve issue without fixing hestia files?

**Comment by ScIT-Raphael** [comment]
Do you have any exclusions for the admin account?

**Comment by xtrime-ru** [comment]
No exclusions: 
![image](https://user-images.githubusercontent.com/34161928/127908619-a3e6accc-7f5a-4f11-ba8b-d613851b0de7.png)

**Comment by jaapmarcus** [comment]
What do you see when you echo both vars?

https://github.com/hestiacp/hestiacp/blob/1280c82af12429907fceed7bf1742f38b21a0045/bin/v-backup-user#L180-L182

**Comment by xtrime-ru** [comment]
> What do you see when you echo both vars?
> 
> https://github.com/hestiacp/hestiacp/blob/1280c82af12429907fceed7bf1742f38b21a0045/bin/v-backup-user#L180-L182

u_disk=7280 
v_disk=6888

**Comment by ayyilmaz** [comment]
I am getting emails with: `not enough diskspace available to perform the backup` at least las 5 updates. Still this problem continue with last update.

**Comment by ScIT-Raphael** [comment]
you need to have the current user diskspace twice for backup, please verify you've enough free resources.

**Comment by ayyilmaz** [comment]
Can we decrease this limit to one? I have enough free resources. My users files's size is 3 gb and there is 10 gb free resources. I used manual backup option on admin panel and this process still continue per 5 minutes. How can I stop the process without effect other user's backup?

Also I hope google drive, yandex disk and cloud.mail.ru options will ve added in near future .

> you need to have the current user diskspace twice for backup, please verify you've enough free resources.

**Comment by ScIT-Raphael** [comment]
No, due to the fact that twice the user size is needed for a propper backup (copy of the folder and the gzip file itself).

Also additional backup targets arent in planing from dev side, there is already ftp, sftp and backblaze. If you like to have additional one, we're always open for PRs.

**Comment by xtrime-ru** [comment]
I cant confirm get_user_disk_usage is correct. My issue was not caused by any bugs, just database growth :)

Thanks for support!

**Comment by gegenyrichard** [comment]
I've ran into this problem too.
Hestia create local backup file first _(transfer it over ftp if it's set.)_
If your local space not enough to perform the backup, it will always fail.
Always maintain your local free disk space.
In my case , the problem source was a huge 10Gb+ error txt file in a 30Gb  SSD :)

**Comment by satsis** [comment]
Same issue
**/usr/local/hestia/bin/v-backup-user m**
Error: not enough diskspace available to perform the backup.

root@i:/home/iv# df
Filesystem                        1K-blocks      Used Available Use% Mounted on
udev                               24587988         0  24587988   0% /dev
tmpfs                               4933240      1668   4931572   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv **478572536 201326840** 256687760  **44%** /
tmpfs                              24666196         0  24666196   0% /dev/shm
tmpfs                                  5120         0      5120   0% /run/lock
tmpfs                              24666196         0  24666196   0% /sys/fs/cgroup
/dev/nvme0n1p2                      1510792    310668   1105100  22% /boot
/dev/loop1                            64768     64768         0 100% /snap/core20/1634
/dev/loop2                            69504     69504         0 100% /snap/lxd/22753
/dev/loop4                            68864     68864         0 100% /snap/lxd/21835
/dev/loop3                            49152     49152         0 100% /snap/snapd/17336
/dev/loop5                            49152     49152         0 100% /snap/snapd/17029
tmpfs                               4933236         0   4933236   0% /run/user/1000
/dev/loop6                            64768     64768         0 100% /snap/core20/1695

250GB free

**Comment by jaapmarcus** [comment]
How large is your user?

**Comment by gegenyrichard** [comment]
now my user disk usage about 2,5Gb
before, when the backup always failed it was over 28Gb
(my VPS full SSD space is 30GB)

**Comment by jaapmarcus** [comment]
let u_disk=$(($(get_user_disk_usage) * 2))
Should be less than the available disk space. 

So this is why

**Comment by codejp3** [comment]
Getting this issue too for a while now and finally reporting it.

I have Hestia running in a 32GB container (about 16GB used).

I have a mount point within that container to hold a rather large NextCloud data directory (1TB+).

I have added the domain.com:public_html/data/ directory as an exclusion so that massive directory should be excluded.

I also have the default /backup directory setup as an external mount point so backups are saved outside of the container and have no effect on the container HDD size in the first place. Even the backup-temp dir is within that external mount point so has zero effect on the container available space.

The only way I can get backups to work is comment out the size checks within /usr/local/hestia/bin/v-backup-user, but it's a hack and not guaranteed to stick after hestia upgrades.

![hestia-backup-size-issue](https://user-images.githubusercontent.com/26341487/210668825-a7eb5599-dff4-43c4-b182-0d46d98ee441.png)

I know my setup is not standard, and there are good reasons to check for available disk space and required disk space as default for 99% of systems out there, but there has to be a decent way to "force-allow" backups (like @jlguerrerosanz [mentioned](https://github.com/hestiacp/hestiacp/issues/1616#issuecomment-776755767)) or to "bypass" this space check altogether. Looking at forum topics related to this issue, it has been an ongoing problem since at least 2019, and probably way before that.

As @jaapmarcus [commented](https://github.com/hestiacp/hestiacp/issues/1616#issuecomment-776781539), this isn't a simple task, but I think it is a worthwhile one to get sorted once and for all.

**Comment by codejp3** [comment]
I'm tempted to start on a patch for this within the next few days.

Considering these changes:

1. Adding select input option to admin panel `/edit/package/` per-package below # of allowed backups 
- "Perform Backups" 
- options "Only If Space Available" & "Force Backups" 
- default: "Only If Space Available"
- key/val pair added to `$HESTIA/data/users/$user/user.conf` per-user based on user package
2. Add optional arg `bypass-space-check` to `v-backup-user` CLI
3. Add extra check in `v-backup-users` for "Perform Backups" key/val pair, and if set to "Force Backups", then add optional `bypass-space-check` arg to `nice -n 19 ionice -c2 -n7 $BIN/v-backup-user $user >> $log 2>&1`


That's what comes to mind. **Set bypassing space checks on a _per-package basis_**. 


Either that, or:
1.  a "global" bypass space checks in admin panel `/edit/server/` -> Backups dropdown.
- seems likely to cause issues with insufficient disk space
2.  on a per-site basis within admin panel `/edit/web/`
- seems dangerous allowing users to select which sites can bypass space checks and would require extra package settings to limit which users can adjust it


 I like the idea of being able to adjust it on a per-user basis depending on which **package** they're assigned to.


Thoughts / feelings / input before I get started on this?

**Comment by jaapmarcus** [comment]
> on a per-site basis within admin panel /edit/web/

For me is this a no go.

**Comment by sistemi-nv** [comment]
I know this is an old and heavily discussed topic, but the problem is real.
Can I suggest a (maybe?) new approach?
What about a dedicated partition for backups, formatted with zfs filesystem?
That way you can perform a new backup with a simple rsync of necessary directories (without any compression) to a backup zfs path but only after doing a date-named snapshot of it.  The backup time-depth should be managed simply deleting oldest snaphots.
ZFS snapshots are Copy-On-Write based (AFAIK), and are directly mountable and accessible to the user.
So, the requested space for backup will be equal to the space actually occupied by data plus the modified amount of data (typically 10-20% max in a day-by-day usage)
If you have to restore an old backup, the restore script should mount the corresponding snapshot in a tmp directory and simply perform the restore operations by a "reverse" rsync into the actually operating directories.

If ZFS dedicated partition is not suitable, the same approach can be performed with hard-links; executing (instead of of a zfs snapshot) a copy of the backup folder into a new date-named one using the "--link" cp option;  then rsyncing actual data to the backup copy.
This way you'll end having multiple versions (inode reference) of the files, but with the space occupied just once if the file wasn't modified .
Is this approach ideally working?

Thanks
giuliano

**Comment by jaapmarcus** [comment]
A copy on the same drive is never a backup.  What happens when a drive breaks down? 

Also I don't think it work will work as will require the user to create the portion and I don't think we should do it via a script.. With out user notifying.. 

I am currently working on incremental backups via Restic and it supports remote backups as well..  Then you have the advantage for incremental backups + remote location and it is about 90% faster then the current method..

**Comment by sistemi-nv** [comment]
> A copy on the same drive is never a backup. What happens when a drive breaks down?

I agree. You have to always backup to a partition on different drive. But this also apply to HestiaCP backup script as it is now unless you choose FTP method.
Anyway, there are at least two different type of backup purposes: one is for disaster recovery and should be always stored in different "media";  another backup purpose is intended to go back in time, and this one could be stored on the same media where actual data are.
On the approach I suggested, nobody forbids to remotely copy the backup after it finishes, exactly as HestiaCP does if you choose the FTP option instead of the "local". Or you can have both, if you want.
My suggestion was focused on maintaining low as possible the disk occupancy when storing local backups.

> Also I don't think it work will work as will require the user to create the portion and I don't think we should do it via a script.. With out user notifying..

That's a good point. Also installing zfs utilities is not intended for regular users. But in my opinion only a pro should manage a web-hosting platform.
Anyway, I think the same result (for local backup low space occupancy) can be achieved via cp --links method. I use this approach for my PC backups and I can always have a "differential" backup without the need of restoring subsequents backup one by one since the last full backup.
Obviously, if the media fails on the disk sector where data actually are written, all the other copies are useless.

> I am currently working on incremental backups via Restic and it supports remote backups as well.. Then you have the advantage for incremental backups + remote location and it is about 90% faster then the current method..

This is a very good new. I'm glad to hear about it. Regular users will have some problem in deploying Restic on the remote side or find providers offering storage space with that service. But for pros, that should not be a problem.

In the meantime, I'll try to understand exactly which directories are to be backed up in HestiaCP to have a full restore, and how to retrieve variables parsing the configuration files. This will be the hardest part to setup a script to backup with the approach I suggested.

That said, I love so much HestiaCP and I appreciate your hard work :D Thank you!

Regards
Giuliano

**Comment by jaapmarcus** [comment]
> This is a very good new. I'm glad to hear about it. Regular users will have some problem in deploying Restic on the remote side or find providers offering storage space with that service. But for pros, that should not be a problem.

Restic supports both Local, (S)FTP and Rclone and there are enough offerings for cheap and affordable storage. So even for a normal user it should be no problem to set it up...

See: https://github.com/hestiacp/hestiacp/pull/3960 

There is a file added v-backup-user-config that copies all the config the /home/user dir

**Comment by sistemi-nv** [comment]
I'm experimenting a little modification of the v-backup-user script to avoid disk space wasting during backup, and it seems to work.
The main problem seemed to me the copy of massive user data  (web contents and emails) before compression.
The actual backup script copies data to a tmp dir, then compress it, then copies to backup final destination.
I modified the location of the tmp dir so that it is created on the same filesystem of original data instead of creating it on the backup folder; this guarantee useage of hardlinks:

@- tmpdir=$(mktemp -p $BACKUP_TEMP -d)
@+ tmpdir=$(mktemp -p $HOMEDIR -d)

Then I modified EACH entry where $HOMEDIR/$user data are copied so that hardlinks are usedinstead of normal copies:
@- cp $HOMEDIR/$user/....
@+ cp -l $HOMEDIR/$user/....

Of course, system users settings and databases are actually copied because them are'nt on the same filesystem of the tmp dir, but usually them are very small compared to the whole user data.

Then, the script continues normally copying the backup to the final destination (locally in another filesystem if the backup dir is mounted via bind, and on a remote FTP if configured) and then the tmp dir is deleted.

This way less hdd space (those required for compressed data) is used for backup manipulation.
The space needed will never be greater than the actual space occupied by user's data.

Does anyone see drawbacks in this approach?
