### ISSUE TITLE
Feature Request: improve default security

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#164]
Remove or disable the firewall rule that opens up mysql port 3306. Users may add it later if they need it. 

When a new mysql user is created, only add the user for localhost as default. Do not create additional user for host = "%". Users may add this later if they need it.

**Comment by ioannidesalex** [comment]
@plutocrat The firewall rule that opens MySQL port 3306 has been already removed. Please check the below commit:
https://github.com/hestiacp/hestiacp/commit/0c093c8e2c1196d00595ec11994e188574a517a5

Regarding MySQL remote users, I think it is not necessary to remove this, since MySQL is by default listening to localhost only and port 3306 is closed. Keeping them there makes things easier (while not compromising security) in case a Hestia user changes his/her mind and would like to allow remote connections.

**Comment by ScIT-Raphael** [comment]
Infact that we've already removed the incoming traffic for 3306, I'll close the request for now. Please feel free to reopen it at any time or create a new (feature) request.

**Comment by JOduMonT** [comment]
@plutocrat 

you could force mysql to allow connection only by socket
by adding `skip-networking ` in your /etc/mysql/my.cnf

than you will have to use `localhost:/var/run/mysqld/mysqld.sock` instead of `127.0.0.1:3306`
not only you will gain in security but you will also optimize your network stack

#### Beware not every php application are developped to support connection via socket.
