### ISSUE TITLE
[FEATURE] Implement Jeff Starr’s 6G/7G firewall rules

### ISSUE THREAD

**Issue by dyrer** [hestiacp/hestiacp#1644]
**implement Jeff Starr’s 6G/7G firewall rules**
Last year WordPress increased a lot, I think if HestiaCP can implement 7G Firewall rules will be one step forward for security issues

**Describe the solution you'd like**
Rules and information are at[ 6G/7G firewall rules](https://perishablepress.com/7g-firewall/)

**Comment by ScIT-Raphael** [comment]
Hi @dyrer 

Thanks for your suggestion, due to the fact, that it is a custom .htaccess file, we are not able to implement it by default. It would make more sense, if every admin itself decide what he want to have to protect his website. Also we already provide an option to block known malicious ips over the iplist function (https://github.com/hestiacp/hestiacp/pull/819), in addition, i would suggest wordfence for protecting wordpress installations.

**Comment by jlguerrerosanz** [comment]
Hello @ScIT-Raphael web application hardening is becoming more important.

Since this implementation has been **ported to nginx** and since it should be easy to toggle activation / deactivation, I think this could be a great security and resource-saving addition.

https://perishablepress.com/7g-firewall-nginx/#alternate
