### ISSUE TITLE
Let Encrypt failing in Web Interface (Let's Encrypt acc registration failed)

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#165]
### Operating System (OS/VERSION):

Ubuntu 18.04.2

### HestiaCP Version:

0.9.8 Release 26

### Installed Software (what you got with the installer):

Default Install

### Steps to Reproduce:

Enable SSL on a site and choose Lets Encrypt support option then click save

**Comment by ScIT-Raphael** [comment]
Just checked on one of our Ubuntu test servers, running 18.04.2, apache2+nginx. Can't repoduce your issue, but you need to have a valid e-mail address set in the hestia user you want to setup let's encrypt. Also you need a properly set and valid dns record.

I will close it for now, please check your email address and let me know if it works. If you need additional help, please send your server credentials to info@hestiacp.com so that we can have a short look.

**Comment by johnnyq** [comment]
gotchya i fixed it, I gave it an email that doesnt exist yet.
