### ISSUE TITLE
[BUG]File-manager button "Exit to Control Panel" not visible after uploading file

### ISSUE THREAD

**Issue by andreas-lindgren** [hestiacp/hestiacp#1669]
**Describe the bug**
If i upload a file with the build in file-manager and drag it instead of using the upload button, the button "Exit to Control Panel" will disappear. If i reload the page the button will be visiale again.

**To Reproduce**
Go to the folder public_html. Drag your file so it uploads to the public folder. Now the button "Exit to Control Panel" should disappear.

**Screenshots**
![hestia01](https://user-images.githubusercontent.com/74539925/110820937-4178ae80-8298-11eb-9449-3b9797a2de75.jpg)
![hestia02](https://user-images.githubusercontent.com/74539925/110820952-44739f00-8298-11eb-95eb-9e53dfc4f884.jpg)

**Operating system:**
I tested this with mac os 10.14.6 on the server i have Debian 10.

**Hestia Control Panel version:**
Latest stable version (1.3.3)

**Comment by jaapmarcus** [comment]
This issue is caused due Vue.js is reloading the Dom structure. 

https://github.com/hestiacp/hestiacp/blob/0678bde2c832da2d015c1df17922e0ac8f743bb0/install/deb/filemanager/filegator/configuration.php#L53-L71

HestiaCP hacks the text in with a small piece of code. How ever it doesn't get reset after Vue.js resets it Dom structure. 

The link is still working fine as this is a visual issue only.

**Comment by andreas-lindgren** [comment]
Okej

Thank you for the information.
