### ISSUE TITLE
[BUG] hestia-php / hestia-nginx update failed - Debian 9 (Stretch)

### ISSUE THREAD

**Issue by robiul-shagor** [hestiacp/hestiacp#1676]
**Describe the bug**
In the latest auto-update Hestia cp control panel not start, 

here is the current report - 

● hestia.service - LSB: starts the hestia control panel
   Loaded: loaded (/etc/init.d/hestia; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-03-16 06:49:49 UTC; 17s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 26390 ExecStart=/etc/init.d/hestia start (code=exited, status=1/FAILURE)
      CPU: 10ms

Mar 16 06:49:49 server.softhopper.studio systemd[1]: Starting LSB: starts the hestia control panel...
Mar 16 06:49:49 server.softhopper.studio hestia[26390]: Starting hestia-nginx: hestia-nginx/usr/local/hestia/nginx/sbin/hestia-nginx: /li
Mar 16 06:49:49 server.softhopper.studio hestia[26390]: /usr/local/hestia/nginx/sbin/hestia-nginx: /lib/x86_64-linux-gnu/libc.so.6: versi
Mar 16 06:49:49 server.softhopper.studio hestia[26390]: /usr/local/hestia/nginx/sbin/hestia-nginx: /lib/x86_64-linux-gnu/libc.so.6: versi
Mar 16 06:49:49 server.softhopper.studio systemd[1]: hestia.service: Control process exited, code=exited status=1
Mar 16 06:49:49 server.softhopper.studio systemd[1]: Failed to start LSB: starts the hestia control panel.
Mar 16 06:49:49 server.softhopper.studio systemd[1]: hestia.service: Unit entered failed state.
Mar 16 06:49:49 server.softhopper.studio systemd[1]: hestia.service: Failed with result 'exit-code'.

in the update process, I got the email for  -
Error: hestia-nginx update failed
Error: hestia-php update failed

after that hestia control panel not start. Could u please tell me how can I resolve it.? I don't want to loose any data, otherwise I will reinstall it.

**Comment by ScIT-Raphael** [comment]
Hi @robiul-shagor 

Thanks for the bug report. There was a wrong package shipped for hestia-nginx on debian stretch (9), which affected 259 installations with what you wrote above.

Please have a look at our forum, we already placed a how to resolve it: https://forum.hestiacp.com/t/heads-up-for-debian-9-stretch-users-with-auto-update/3017/

In short form, you need to run this commands:
```
apt update
apt remove hestia-nginx -y
apt install hestia-nginx -y
```

As soon as you've run them, hestia backend will be back online. Sorry for the troubles we've generated!

I'll let this bug report open, so it will be visible for the other users.

**Comment by robiul-shagor** [comment]
Thank you so much, Issue resolved

**Comment by ScIT-Raphael** [comment]
Let us keep the issue open, so potential other users of the 258 affected servers can see it aswell :).

**Comment by tudorr89** [comment]
In some cases you can encounter the following:
`Setting up hestia-nginx (1.19.8) ...
Job for hestia.service failed because the control process exited with error code.
See "systemctl status hestia.service" and "journalctl -xe" for details.
invoke-rc.d: initscript hestia, action "start" failed.
● hestia.service - LSB: starts the hestia control panel
     Loaded: loaded (/etc/init.d/hestia; generated)
     Active: failed (Result: exit-code) since Wed 2021-03-17 10:44:00 EET; 69ms ago
       Docs: man:systemd-sysv-generator(8)
    Process: 3047886 ExecStart=/etc/init.d/hestia start (code=exited, status=127)
      Tasks: 2 (limit: 4685)
     Memory: 2.7M
     CGroup: /system.slice/hestia.service
             ├─3045248 nginx: master process /usr/local/hestia/nginx/sbin/hestia-nginx
             └─3045249 nginx: worker process

Mar 17 10:44:00 svr1 systemd[1]: Starting LSB: starts the hestia control panel...
Mar 17 10:44:00 svr1 hestia[3047886]:  * Starting hestia-nginx hestia-nginx
Mar 17 10:44:00 svr1 hestia[3047886]:    ...done.
Mar 17 10:44:00 svr1 hestia[3047886]:  * Starting hestia-php hestia-php
Mar 17 10:44:00 svr1 hestia[3047891]: /usr/local/hestia/php/sbin/hestia-php: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
Mar 17 10:44:00 svr1 systemd[1]: hestia.service: Control process exited, code=exited, status=127/n/a
Mar 17 10:44:00 svr1 systemd[1]: hestia.service: Failed with result 'exit-code'.
Mar 17 10:44:00 svr1 systemd[1]: Failed to start LSB: starts the hestia control panel.
dpkg: error processing package hestia-nginx (--configure):
 installed hestia-nginx package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Errors were encountered while processing:
 hestia-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)`

If that is the case, make sure to run: 
`apt install -t focal libzip5 libzip-dev`

**Comment by BRNKR** [comment]
same problem with ubuntu 20.04

Saw your Update 1.3.4. Went to hestiaCP Update Panel and clicked on update. Afterwards i have updated my system with 'sudo apt update && sudo apt upgrade". nginx was not able to bind to port. your apt.hestiacp.com repo went down. now i ve updated again and reinstalled nginx. everything is working again. thanks

**Comment by jaapmarcus** [comment]
Hopefully most users have upgraded by now

**Comment by povnurb** [comment]
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.
