### ISSUE TITLE
[FEATURE] Wildcard certs available to all subdomains of a domain

### ISSUE THREAD

**Issue by tlcd96** [hestiacp/hestiacp#1684]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
- Creating an option for lets-encrypt to generate a wildcard to be used, for the below reason, on the panel.
- Creating an option to use wildcard if available for subdomains if the parent domain has a wildcard certificate. This can also be applied to mail.{domain.tld}, etc...

**Describe alternatives you've considered**
manually sim-linking domains it's very tedious and a waste of time.

**Additional context**
1. This would simplify the user <=> shell interaction,
2. This would be very useful for many hestia users.
3. Nothing more, I think that the solution description it's enough to understand what is being requested.

**Comment by ScIT-Raphael** [comment]
I personaly don't think that a lot of hestia users are using let's encrypt wildcard certificates - due to the fact, that you need a dns validation process which is currently only working, if you run your own nameserver cluster.

On the other side, it would be a good idea to not generate additional certs, if there is a wildcard available - but there could also be a problem, that you will mix mail and web. Just in case someone wants to split his webdomain to another server, he would also move away his let's encrypt cert which will then stop the mail ssl functionality or let the cert outdate.

I'll discuss it with the team, but my current opinion is, that we should not mix web and mail certificates - also I think it's not worthable for the time which is needed to develop it.

**Comment by ScIT-Raphael** [comment]
We just had time to discuss in the dev chat: With the reasons above we decided that we will not implement this within an acceptable timeframe. So I'll going forward to close the issue, thanks for the idea and your contribution!
