### ISSUE TITLE
Add Open Web Analytics in place of awstats and webalizer or as an option

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#169]
http://www.openwebanalytics.com/ seems like a much more modern free opensource option to awstats and webalizer

**Comment by ScIT-Raphael** [comment]
We will discuss this internaly, because we would have to replace one of the two analytic tools - 3 of them would be to much :). I think the most user are using google analytics or similar external software.

I will close the feature request for now, it is already in group discussion. If we will implement it, i would reopen the request.
