### ISSUE TITLE
[BUG]The panel is not installed

### ISSUE THREAD

**Issue by shystriknsk** [hestiacp/hestiacp#1700]
The panel is not installed, apache2 does not start on Debian 9 and nginx does not start on Ubuntu 16.04 I have already tried many methods that there is still a problem that repeats. I didn't have enough nerves I went back to the vesta cp

**Comment by ScIT-Raphael** [comment]
I would strongly suggest to install hestia on a current system, ubuntu 16.04 will be dropped with the next release - also there are already two new versions (18.04, 20.04). If you're interrested, please share more informations about what "methods" you tested, what fails and what happens during the install - with the current informations, this sounds more like a support case.

The installation on debian 9, 10, aswell for ubuntu 18.04, 20.04 (probaly 16.04 aswell) has been tested when we shipped the latest release.

Due to the current security issues on vesta, i strongly suggest you to not switch back to it...

For now, I'll close the issue because we don't have enough informations. Please feel free to provide them here, or maybe better use https://forum.hestiacp.com .
