### ISSUE TITLE
Feature Request: 1 Click Wordpress installs

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#171]
1 click word press install when setting up a new site in the web interface

Downloads latest wordpress set permissions and create database

**Comment by ScIT-Raphael** [comment]
We removed the softaculous installer because we did not want to have any encrypted code inside our project. At the moment, there is no plan to implement such a feature.

I will close the question for now, if you will have any additional one, feel free to reopen the issue.

**Comment by johnnyq** [comment]
I was not a big fan of softaculous either. But couldn't it be done with custom scripting within the web panel.

**Comment by ScIT-Raphael** [comment]
Yes it could be done, but you will need to do it for every software. That's a lot of maintenance, working and testing - due to changing software. That's also a reason why VestaCP has choosen softaculous as external "provider" to solve the request. As I already described we do not want to have any encrypted code in our project :).

We've the focus more on a secure and stable control panel, I will keep your idea in mind and discuss with the team - but at the moment we will not have any free time to implement it. If you want to create such a script, we would be happy if you share it with us using a pull request!

**Comment by hanzicode** [comment]
John, I tried this which is not one-click install but still pretty easy to do: https://mighil.com/bash-script-to-install-wordpress-on-vesta-cp
