### ISSUE TITLE
[FEATURE] Custom backup temp directory

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#1731]
**Is your feature request related to a problem? Please describe.**
Yes. When you ask for a backup, you need in the worst case 2 times the space of the account to create the backup: Create the temp directory and then the .tar file.

If the user has own script do call v-backup-user, will be good to have a parameter to provide the directory of temp files and where the .tar will be created. Usually the user has another partition with more space because is very common in cloud/vps services to buy extra volume to manage the backups to avoid fill the / system.

**Describe the solution you'd like**
Two parameters: where to create backup temp files and where to save the backup.

**Describe alternatives you've considered**
At least one parameter to customize both directories.

**Comment by jaapmarcus** [comment]
I don't see the need for an for a custom temp directory 

The backup directory can be moved via
https://docs.hestiacp.com/admin_docs/backups.html#how-to-change-default-backup-folder

**Comment by franciscopaniskaseker** [comment]
@jaapmarcus please reconsider. third backup scripts need that. the workaround about bind other directory under /backup is not a complete solution.

**Comment by jaapmarcus** [comment]
We are considering a system setting that allows users created backups placed under the users backup.

Users can only call the script via WebUI if we need to expend the system we need to improve the current WebUI 
It is currently not possible to call it via a third way.

For a custom location do we want to expand it to ftp, sftp, whatever location the system becomes to difficult and the time invested does not outweigh the usage for new features. 

 Because a custom folder will be only under the user home dir.

For "save" location You are able to mount backup folder to a larger disk / or even a remote location. It is what you wanted.

**Comment by franciscopaniskaseker** [comment]
I am aware about UI aspects, but I am talking just about the CLI v-backup-user to have a optional parameter that will provide the directory to store the backup.

Using bind alternative if I have multiples targets, will be hard to manage all the bind needed and some backup tools does not do that.

**Comment by ScIT-Raphael** [comment]
@franciscopaniskaseker Please feel free to implement it on your own fork, then provide a pull request - so we can discuss if we want to implement it. The request itself has been declined after discussion with the team, the decission will not be changed.
