### ISSUE TITLE
Proxmox LXC ubuntu 18.04.2 Empty netplan configuration directory

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#175]
I get the following error with ubuntu LXC under proxmox im able to bypass it with the -f

root@web01:~# bash hst-install.sh
Please wait a few seconds, we update your repository before we start the installation process...
Install missing apt-add-repository...
!!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!!

Noticed a empty netplan configuration directory.
You may have a network configuration file using systemd-networkd,
we strongly suggest to migrate to a fully netplan configuration.

You can leave this like it is, but you will be not able to use
additional ips properly

If you want to force installation run this script with -f option:
Example: bash hst-install-ubuntu.sh --force

!!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!!

Error: Noticed unused netplan configuration.
root@web01:~#

**Comment by ScIT-Raphael** [comment]
Proxmox does create the ip configuration inside a systemd configuration file, usualy placed under /etc/systemd/network/. The problem is, that the configuration is not inside the netplan directory, but netplan is installed. Now the easiest way would be to remove the systemd network configuration, add a propper netplan configuration in /etc/netplan/10-default.yaml (examples: https://netplan.io/examples).

As soon as you've a netplan configuration, the message will not show up anymore. You could also leave it like it is, but you can't use additional ips.
