### ISSUE TITLE
[Bug] www alias not created when adding a double dot TLD domain

### ISSUE THREAD

**Issue by manuelserol** [hestiacp/hestiacp#1750]
**Describe the bug**
When adding a new domain with double dot TLD like .com.au the www alias is not created

**To Reproduce**
Add new domain with double dot TLD

**Expected behavior**
www alias to be automatically created

**Operating system:**
Debian 10

**Hestia Control Panel version:**
1.3.5

**Comment by shankarnewton** [comment]
# Ticket Status Update

![Generic badge](https://img.shields.io/badge/Ticket_Status-Resolved-<COLOR>.svg)

## RCA
Following is the Root Cause Analysis of this ticket.
- Inference 1 and its details
- Inference 2 and its details
- Inference 3 and its details
- Inference 4 and its details
- Inference 5 and its details

## Temporary Work Around
Following is the brief summery on action points done to minimise business loss as part of temporary work-around.
- Step 1 & its action points.
- Step 2 & its action points.
- Step 3 & its action points.
- Step 4 & its action points.
- Step 5 & its action points.


## Permanent Solution
Following is the brief summery on action points done for the permanent solution.
- Step 1 & its action points.
- Step 2 & its action points.
- Step 3 & its action points.
- Step 4 & its action points.
- Step 5 & its action points.

/spend 30m
