### ISSUE TITLE
[FEATURE] Daily health check

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1781]
Sometimes some services can fail and we don't get to discover it before they start to have consequences.

To prevent that from happening Hestia could have a cron job that checks
- nginx -t
- exim -bV
- apachectl configtest
- and some other active services...
- ...
- df -h

If there is a problem detected we could take two actions:
- Display a big red box after loging into the server
- Send an email to the administrator

**Comment by archergod** [comment]
In extension we can have a health page [optional to make public] or Feed if you have to manage more than one server. Is good option too.

**Comment by franciscopaniskaseker** [comment]
I can do some script that generate those kind of informations. I can print some JSON with status of important informations. And this JSON can be used by zabbix or some vestacp health page.

**Comment by jlguerrerosanz** [comment]
That's great!

Now we've got to decide which tests are interesting.

- load average
- free space
- nginx -t (so it doesn't fail upon restart or the next letsencrypt renewal)
- apachectl configtest (if apache is configured)
- exim -bV

**Comment by jaapmarcus** [comment]
All those  data are not relevant for a daily health check. Best way is to implement a monitoring system like Nagios / Incanga2 / Zambit and monitor it constantly we should make sure that an faulty configuration should never reach live config.

**Comment by jaapmarcus** [comment]
Just to Clerafy. If an server goes down for what some reason an daily health check if worth less.  The health check will never reach his end location before it goes down. 

For Exim, Dovecote, sshd or any other service  we need to implement an config test before we restart the said service. This ensures when a service will get reloaded / restarted the service will remain available be fore it goes down (Apache2 for example) or even just reloads without an warning (Nginx).. It happens me to many times an config error in ssh locked me out due to  config error. 

Load average for moment at midnight for example is worth less. If we need a load value we need to implement an full time monitoring. Easiest way is to implement a monitoring system like Nagios / Incanga2 or anything else.  We could maybe setup an script that does the same when the load is xx percent of total cpu but it depends on the number of cores. Hard to setup.

<img width="334" alt="Screenshot 2021-05-14 at 10 17 07" src="https://user-images.githubusercontent.com/9754650/118242522-bab19f00-b49d-11eb-9d7f-bad85780987d.png">

The daily health check for Diskspace means nothing 10% free space on a 10tb disk is something else then an 10% of a 10 gb disk. Both can cause issues but on a 10TB disk you have 1TB free on a 10gb only one.. So with cases the response should be different. 

Sending a daily email with out a reason is worthless it will only create an alarm blindness.

**Comment by jlguerrerosanz** [comment]
Thank you @jaapmarcus for your response. I understand that we share the same concerns.

From here on, I am only going to share my opinion but I don't want to change yours or force you into developing this solution. I am just sharing my thoughts.

And maybe this is out of the scope of the project. The thing that I can think of is to **have a configurable threshold** so that **the alarm is only triggered when it is meaningful.** For example: for the free space, I think that we would all agree that the alarm should 100% of the times trigger when the disk is below 300MB.

The other thing that can be useful is to know those indicators and to **see the indicators upon login**. No alarms at all. Only that information so you can act upon it.

**Comment by jaapmarcus** [comment]
Setting up triggers / limits is a disaster how current Hestia config files are currently working. I do agree we should create more information regarding disk usage  and that some information is well hidden in the system and to be useful we need to find a way to convert the information in more useful information. As the current output is just plain text and mailing it to the user is just worthless as no body will read the information and if an true error happens it will get ignored

<img width="784" alt="Screenshot 2021-05-14 at 10 43 16" src="https://user-images.githubusercontent.com/9754650/118245834-8c35c300-b4a1-11eb-9b27-6366212dedbd.png">

If uptime matters spend the effort to setup a monitoring system it will payout the time spend...

**Comment by jlguerrerosanz** [comment]
I have just had a look at the server information provided in Hestia (I usually don't)

Maybe a minor change:
https://my.server.com:8083/list/server/

![image](https://user-images.githubusercontent.com/8811720/118251345-c0ac7d80-b4a7-11eb-939a-a28acd5e978a.png)
