### ISSUE TITLE
[FEATURE] Change name of fail2ban jail 'recidive' for clarification

### ISSUE THREAD

**Issue by plutocrat** [hestiacp/hestiacp#1826]
Just a suggestion, as the lingua franca* of Hestia is English, it might be a good idea to rename the 'recidive' jail, iptables rule etc to 'repeat-offender' or some other more easily understood term. I believe 'recidive' is Spanish, and although English has the term recidivist, its not a term widely understood. 

I'd imagine it wouldn't be necessary to change existing installs, but going forward it might be useful for people to understand its purpose. 

\* Ironic use of latin!

**Comment by ioannidesalex** [comment]
Recidive is a term used by Fail2ban itself. It’s not something we just came up with :)

**Comment by jlguerrerosanz** [comment]
I was going to say that recidive is NOT a Spanish word because I didn't know it but I looked it up in the dictionary and recidive is strangely a Spanish word BUT it is the conjugation of the verb recidivar in the subjunctive mode.

It is only used in medicine to express a sickness that comes back again after recovery.

It is in fact Latin.
