### ISSUE TITLE
[FEATURE] Add DNS mode to Let's Encrypt approval

### ISSUE THREAD

**Issue by Revertron** [hestiacp/hestiacp#1921]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Let's Encrypt functionality works only in HTTP/HTTPS mode, and has no DNS mode.

**Describe the solution you'd like**
All major registrars and DNS providers support APIs that are used in such projects like [acme.sh](https://acme.sh), and it gives more freedom.

**Describe alternatives you've considered**
`acme.sh` can do all this stuff and more. Maybe it is possible to just use it?

**Comment by tlcd96** [comment]
I want to agree, but hestia has a part that does the certificate by DNA, on wildcards.
E.g.: v-add-letsencrypt-domain <user> domain.tld *.domain.tld
Sorry if the command it's not fully correct but I'm on mobile replying.

Yeah, it would be easier if hestiacp contributed with the procedure for hestiacp on acme.sh and would be a better option, because they only would need to keep the support for the api's that hestiacp creates for acme to work.

Basically they would need to tell the system the DNS records, tell the DNS to restart (sometimes reload does not do the trick) and verify the hashes that's automated on the acme.sh, then, if successful, they would need to copy the certificate and the rest ( I do t remember if acme generates all the files - CRT, ca, key, pem)

It's a bit easier said than done, I've tried before with vestacp, they refused, I don't have the time or will to make another file like that, to be refused by the hestiacp team and/or by the acme team.

Also everything I suggest as a feature is like a bullet on my feet, so... Good luck mate if they accept this feature request.

For example, I've sugested that the subdomains and domains to be organized like a tree and not like loose files, and to be able to use wildcard domains with that in mind. Refused. Mobile friendly? Refused, use if available wildcards on email, refused, etc...

**Comment by ScIT-Raphael** [comment]
First thing said: Hestia does already support wildcard certificates, but you need to have the dns managament done with hestia aswell - @skullwritter is completly right here.

I also had the idea to integrate the certificate generation with acme.sh, it would give us more flexibility and also the possibity to choose another authority instead let's encrypt.

> Also everything I suggest as a feature is like a bullet on my feet, so... Good luck mate if they accept this feature request.

Feature requests are always declined with a reason, this is nothing personal or anything else.

> For example, I've sugested that the subdomains and domains to be organized like a tree and not like loose files

Can't find that feature request. But for the first look, it would be probaly complicated to handle.

> and to be able to use wildcard domains with that in mind. Refused. 

Can't find that specific feature request aswell. Currently you are already able to use a wildcard, but you need to set it in alias tab. This will probaly also not change due to the way hestia has built its domain management (so probaly aswell "rejected" due to the needed time for rewrite a lot of code vs. usability).

> Mobile friendly? Refused,

Mobile friendly hasnt been refused. We are aware and we also want to have a mobile friendly version of hestia - but as soon as you will start to work on it, you will notice, that with the current interface and the way it has been developed, it's impossible to build a propper mobile compatibility. Our target is to rewrite the interface with a propper framework which then automatically gives the option to do a good mobile integration. (Related issue report https://github.com/hestiacp/hestiacp/issues/1906). It could have been written with a few more words :).

> use if available wildcards on email, refused

Also not found in issues. A potential reason to decline is that we do not focus that hard on email, nearly non of our main devs is using the mail function of hestia. Also myself I switched the most of my mail parts to O365 due to mail delivery problems.

> etc...

What I've found for etc... would be https://github.com/hestiacp/hestiacp/issues/1907, as written we've shipped a redirect function with 1.4.0. If you want to enable that specific function, you can just toggle it on and set it to the backend url. As also written, it could lead to a potential security issue, when you just forward all traffic to the interface - some users may want to "hide" their operating port. 

I hope I was able to clear your bad feelings a bit out @skullwritter. Please feel free to start somewhere and support hestia with your contribution. As written, we're open minded for a rewrite of the ssl generation engine to support acme.sh, or maybe even a switch to have both. It's also not that we close issues without any reason, mostly "time" is an excuse because we are limited with it due to the size of our team (which we want expand aswell).

Edit: Ok, found the other referenced issues/prs, they are nearly a year old so I'll skip linking or further updating my post.

**Comment by jaapmarcus** [comment]
> Mobile friendly? Refused
 
I don't want to spend xx days spending on a mobile improvement. And then spend the a little more again on a "New" and improve design again  including a lot of UI / Other improvements. Current design I don't want to spend the time on it... 

But if there is an UI / Designer in the house.  https://github.com/hestiacp/hestiacp/pulls for some ideas..

**Comment by jaapmarcus** [comment]
> **Is your feature request related to a problem? Please describe.**
> I'm always frustrated when Let's Encrypt functionality works only in HTTP/HTTPS mode, and has no DNS mode.
> 
> **Describe the solution you'd like**
> All major registrars and DNS providers support APIs that are used in such projects like [acme.sh](https://acme.sh), and it gives more freedom.
> 
> **Describe alternatives you've considered**
> `acme.sh` can do all this stuff and more. Maybe it is possible to just use it?

For DNS hosted within  HestiaCP it might be possible to add the feature it will probably work fine. How ever for Remote DNS providers like Cloudflare or Godaddy users have to pass trough API details every time when they create a new Web domain. It doesnt make sense for a user experience... It makes only sense we have a system available that is capable to create the DNS zones. But again limited resources an time...

**Comment by tlcd96** [comment]
@ScIT-Raphael 
> > Mobile friendly? Refused,
> 
> Mobile friendly hasnt been refused. We are aware and we also want to have a mobile friendly version of hestia - but as soon as you will start to work on it, you will notice, that with the current interface and the way it has been developed, it's impossible to build a propper mobile compatibility. Our target is to rewrite the interface with a propper framework which then automatically gives the option to do a good mobile integration. (Related issue report https://github.com/hestiacp/hestiacp/issues/1906). It could have been written with a few more words :).

There is a way with css value property and data attributes for that, I'll will see and try to show it in a example if I can today, at 20 -1 UTC, (currently 07:37) it's not complicated, but to apply to hestiacp will be a pain in the rear.

Another thing is with responsive tables that can be done with the same in mind and with a bit of javascript to toggle an active state that will show the info when active (accounts for example), I've did it before but I don't remember the javascript for that. I'll try that too in the example if I can make it as said above.

**Comment by Revertron** [comment]
The main problem with local DNS is that I use PowerDNS and its API is on another host.

**Comment by tlcd96** [comment]
@ScIT-Raphael @jaapmarcus 
>  > Mobile friendly? Refused
>  
> I don't want to spend xx days spending on a mobile improvement. And then spend the a little more again on a "New" and improve design again  including a lot of UI / Other improvements. Current design I don't want to spend the time on it... 
> 
> But if there is an UI / Designer in the house.  https://github.com/hestiacp/hestiacp/pulls for some ideas.. 
> 
>  

Is this development already in progress or is on the board of to-do? Cause if is already in development the example I mentioned above will be unnecessary....

**Comment by tlcd96** [comment]
@ScIT-Raphael @jaapmarcus open again the mobile friendly feature request cause this isn't the place to talk about that, sorry @Revertron , my bad.
Powerdns on another machine... I think that that will be kinda of a problem.

**Comment by jaapmarcus** [comment]
@skullwritter  done

> The main problem with local DNS is that I use PowerDNS and its API is on another host.

That is the main issue to solve is that we need to implement a way to allow connecting with different DNS "providers" / software to allow it and make it work....

**Comment by Revertron** [comment]
> That is the main issue to solve is that we need to implement a way to allow connecting with different DNS "providers" / software to allow it and make it work....

[acme.sh](https://acme.sh/) already supports a very big number of them.

**Comment by jaapmarcus** [comment]
We are not able to change the current system due to time limitations. Ipv6 support, changes to Postgresql / pgadmin have a higher priority. Feel free to fork Hestia an make the changes your self... 

acme.sh is not a drop in replacement as it still requires changes how every thing is handled. 

I am going to close the issue as we are not able to implement this feature within the next years unless more users are willing to invest their time into it..
