### ISSUE TITLE
[FEATURE] Prevent nginx.conf to be overwritten upon update

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1963]
Many people ask in the forum every week about this topic.

We could try something like this:
dpkg-divert --divert /full_path/file_to_preserve.packaged --rename /full_path/file_to_preserve

Or change the nginx installation directory so it doesn't get overwritten.

**Comment by ScIT-Raphael** [comment]
You need to set the nginx.conf overwrite actively to yes, by default it suggests no. We are aware that a few people decided to overwrite this file and got issues due to it. BUT: We strictly communicate that we develop hestia as solution for sysadmins, if you are not aware what you're doing, there is zero reason to overwrite a config file - keep the default and you're good to go.

The amount of reports got increased due to the fact, that nginx shipped a new package (which had a new nginx.conf) a day before we shiped a new hestia version. But over all, 4-6 reports on 11k active arent "much".

Changing the nginx installation directory would go into a own compiled version, as explained we do not have any interrests to provide custom compiled packages.

So we will not going to protect the nginx.conf in a additional way and I'll close your request.

**Comment by jlguerrerosanz** [comment]
Okay. I was just suggesting that you gave it a thought and you did. I'm fine with that. Thank you for your time.
