### ISSUE TITLE
[FEATURE] Add BuyPass to Hestiacp

### ISSUE THREAD

**Issue by benzntech** [hestiacp/hestiacp#2030]
**Is your feature request related to a problem? Please describe.**
BuyPass is a commercial entity that provides free standard SSL certificates using the ACME protocol, just like LetsEncrypt. One bonus is that their certs are good for 180 days, not just 90 days like LE.
Please include to Hestia

**Describe the solution you'd like**
Here is reference code which is used in the platform Install LAMP using shell script 
https://github.com/teddysun/lamp/blob/835417f9f529a2de1438ab0abe97fedb97fca4e2/conf/lamp#L258

https://github.com/teddysun/lamp/blob/835417f9f529a2de1438ab0abe97fedb97fca4e2/conf/lamp#L364

```
add_buypass(){
    if [ -d "${apache_location}/conf/ssl/${main_domain}" ]; then
        _info "Removing exist domain certificate..."
        rm -rf ${apache_location}/conf/ssl/${main_domain}
    fi
    _info "Starting create Buypass.com SSL Certificate..."
    . /usr/local/acme.sh/acme.sh.env
    /usr/local/acme.sh/acme.sh -m ${email} --issue --server buypass ${letsdomain} -w ${website_root} --days 170
    if [ $? -eq 0 ]; then
        ssl_certificate="${apache_location}/conf/ssl/${main_domain}/fullchain.cer"
        ssl_certificate_key="${apache_location}/conf/ssl/${main_domain}/${main_domain}.key"
        _info "Created Buypass.com SSL Certificate success"
    else
        _error "Error: Create Buypass.com SSL Certificate failed"
    fi
}
```

**Comment by jaapmarcus** [comment]
Let time I investigated the possibilities it still required a lot of changes / differences between LE and BuyPass

**Comment by bet0x** [comment]
@jaapmarcus @benzntech There is a way to get a doc or a statement on if this will fly over time? They seem not to have anything good except for the 180 days vs 90.

https://www.buypass.com/ssl/products/ssl-evident

**Comment by ScIT-Raphael** [comment]
I'm not against flexibelity at all, so support BuyPass would be an option. The problem is that we currently use a custom api specialy build for lets encrypt. The only way to support this, would be to throw out this script and replace it with acme.sh.

Also take care with your script and manualy overwrite the cert files, I'm not sure how exactly it will react after a rebuild, there is the possibility that it will be overwritten.

Until now, I don't see any big advantage of going the hard way and start using acme.sh, expect the 180 days cert time and the additiomal flexibility. I'll discuss it with our dev team, we may also close the request.

**Comment by jaapmarcus** [comment]
Did some checks any way but  there are some minimal changes that need to be sorted out first. If somebody is willing to invest the time feel to do so...
