### ISSUE TITLE
Feature Request: Cron Script to remove trash and spam every 30 days from all users mailboxes

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#206]
This could be useful, a lot mail users choose not to empty their trash and spam, this could could help with the build up tremendously.

**Comment by hrvylein** [comment]
Is spamassassin learning right now? My old vesta installation didn't recognize too much spam even every incoming mail had the sa header.

**Comment by johnnyq** [comment]
hello @hrvylein try setting your spam score lower than the default 50 goto Server - exim4 - configure - Set SPAM_SCORE = 30

**Comment by ScIT-Raphael** [comment]
Just checled your request, you could do this using autoexpunge=<time>
 (https://wiki2.dovecot.org/MailboxSettings) in your dovecot configuration for the requested folders. I think we should keep this step manually - every user should decid3 on it's own, if he want to implement autoexpunge or not. Because of that reason, I will close your feature request, please feel free to try our the above in dovecot integrated feature and let us know, if you've any additional request.
