### ISSUE TITLE
Feature Request: CalDAV/CardDAV/ActiveSync Integration

### ISSUE THREAD

**Issue by xXKynarethXx** [hestiacp/hestiacp#211]
As discussed at serghey-rodin/vesta #1559, I would love to see an integration of sogo to vesta/hestiacp.
At the moment, I am completely new to vesta&hestia and can't really figure out what to choose.
It seems like vesta team isn't active at the moment (see forums, github, or even the chat), does someone know, if it's no longer continued or sth?
Thanks!

**Comment by hrvylein** [comment]
I would switch over to hestia. Vesta lacks development and has had or maybe has severe security problems.

**Comment by ScIT-Raphael** [comment]
I will discuss your request with the team, basicly we do not want to "overload" hestia with to much integrations and incldued software.

**Comment by johnnyq** [comment]
I like SoGo, but I agree with the overload, maybe make it optional and even add Activesync which could also be optional. This will allow for PUSH email and contact and calendar integration, as well as easy email setup using the exchange protocol.

**Comment by xXKynarethXx** [comment]
I love sogo for exchange and the very nice frontend. But I can understand if it would be too much overload. I would take sogo instead of roundcube (even if rc is using less performance)!
Please update, when a decision is made! Thanks for your quick answer!

**Comment by xXKynarethXx** [comment]
> I would switch over to hestia. Vesta lacks development and has had or maybe has severe security problems.

Thanks for ur answer. I will take a closer look at hestia, because vesta is facing some real problems with SFTP backups and hestia looks far more promising. I didn't even get an answer from vesta staff.
Thank you all!

**Comment by ScIT-Raphael** [comment]
Just had a short talk with the team; we plan a function called v-add-mail-domain-ssl, similar to v-add-web-domain-ssl that creates a few domain names (mail/smtp/pop.domain.tld) with valid ssl certificates and add the certificate file to exim (https://github.com/hestiacp/hestiacp/issues/168).

We play now with the idea, to implement also webmail.domain.tld and point it to roundcube webmail OR sogo. We will checkout and work on a integration with sogo, but no promise: We do not know yet if it would work!

**Comment by johnnyq** [comment]
@ScIT-Raphael that is awesome news!!!

**Comment by ghost** [comment]
Hi everyone,

After discussing this further with the team and evaluating implementation and impact, we're taking a look at mail and synchronization under a closer microscope and have agreed that contact and calendar sync needs to be included. 

Ultimately, we want to provide a server platform that is both functional and easy to manage within a lightweight and secure package. Due to size and complexity of the codebase SoGo would add more strain on our development efforts. That being said, we are working on backend development for bringing important features like mail/contact/calendar sync via DAV & Exchange ActiveSync, multi-domain SSL, and other enhancements to the mail stack that ships with Hestia.

Stay tuned and thanks again for your feedback!

**Comment by johnnyq** [comment]
SUPER!!

**Comment by beli42** [comment]
absolutely the correct decision! please keep focus on the core and its features and integration to the admin interface. there's enough todo.
sogo is too much on the application level; although it's really nice ;-)

**Comment by JOduMonT** [comment]
personally, I see SOGo, roundcube, rainloop and ... as an apps like wordpress.

Such as an example I always remove roundcube, phpMyAdmin and webalizer when I ~~install~~ was installing vesta.

I'll probably focus on integrating Docker with Hestia than any apps, with any preference will be easily maintainable and will be well serve by Hestia.

**Comment by ghost** [comment]
Hey @jodumont,

Thanks for your feedback. While we will be shipping a customized webmail client in Hestia to align with the work we are doing to our mail subsystem (based on Roundcube, but with a focus on user friendliness, clean design, with mobile support) it will be optional during install. 

Already in the **develop** branch, we have made changes so that if Dovecot/Exim are not installed then Roundcube is excluded, and the option to turn webmail on/off and use other clients in an easier fashion is also in the works. 

We know that the mail stack is a pain point right now for both Hestia and the upstream Vesta project, and that many users are expecting to have what is now considered basic functionality such as Calendar & Contact synchronization and push e-mail support on mobile devices, in addition to valid SSL certificates for every hosted domain and not relying on the host's certificate. 

You'll also be happy to hear that Webalizer has been removed in favor of awstats as the default statistics package moving forward, and you'll see this change with the next release. 

If you have any more ideas, please feel free to let us know, we certainly appreciate it! :)

**Comment by JOduMonT** [comment]
@kristankenney your caldav/carddav implementation is from scratch or base on something like radicale or baikal ?

because, just to mention another great project who's focusing on email [modoboa](https://modoboa.org) built almost everything from scratch except for the webmail and the calendar part which it relay on radicale.

**Comment by JOduMonT** [comment]
@kristankenney I just explored the [shared-mailboxes](https://github.com/hestiacp/hestiacp/tree/mail-shared-mailboxes) branch, this is a great idea which makes linux mail stack really able to compete with exchange and others _outlook compatible server_.

**Comment by ghost** [comment]
Our goal is to provide a mail solution that sits well above basic POP/IMAP but below Exchange, with more features being evaluated and added as time goes on. The fact is due to limitations of certain subsystems, true Exchange functionality may never be 100% possible but if we can provide a stack that's simple, easy enough to administer with all related services sharing a single sign on then I believe that will satisfy the needs of most users.

**Comment by thiagoalcav** [comment]
> personally, I see SOGo, roundcube, rainloop and ... as an apps like wordpress.
> 
> Such as an example I always remove roundcube, phpMyAdmin and webalizer when I ~install~ was installing vesta.
> 
> I'll probably focus on integrating Docker with Hestia than any apps, with any preference will be easily maintainable and will be well serve by Hestia.

...maybe use portainer.io as a backend container tool...

**Comment by JOduMonT** [comment]
@thiagoalcav yes a lot of projects (Nethserver, OMV5,...) goes this way howerver, the main game is at the proxy level, if you transfert/use NGINX as a container than everything is fine you just need a docker-compose companion like [this](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) but you also add a level of abstraction which increase security and weight on the TCP stack. My original plan was to generate proxy config for nginx (on the host) and using UNIX Socket instead of TCP socket. Technically [this project](https://github.com/jwilder/docker-gen) handle it but I must admit, I just decide to use Hestia when it sweet me and Docker for project which require less security and responsiveness, ...

### but docker is totally off topic

**Comment by johnnyq** [comment]
Im super excited about the mail features coming to 1.1.0 This is SO much needed in the opensource community as Office365 and G-Suite seem to be taking over at an alarming rate. I can still remember the days when the internet was all about diversity. Well anyway the Biggest mail features im really looking forward to are

- IMAP Mail Folder Sharing
- Calendar Integration and sharing
- Contact Integration and sharing
- ActiveSync

Another Feature could be mail groups within a domain (Permission Level Stuff)

For example HR IMAP folder is shared amongst the HR Group or Accounting Calendar is only shared amongst the accounting group etc)

Im so excited the team at Hestia are really making great progress, they work so well as a team, Extremely fast and quick responses, and Excellent development time! Way To Go keeping us Librerated from the Goliath Hosting Providers!! You guys are very much indeed needed in the opensource community.

**Comment by johnnyq** [comment]
looks like roundcube 1.4 RC2 came out today! =]

**Comment by ghost** [comment]
If anyone is able to help us with implementing Radicale or another lightweight and reliable CalDAV/CardDAV backend, please submit a pull request or email info@hestiacp.com.

**Comment by layanto** [comment]
> If anyone is able to help us with implementing Radicale or another lightweight and reliable CalDAV/CardDAV backend, please submit a pull request or email info@hestiacp.com.

I use Baikal for CalDAV and CardDAV with hestiaCP as a web domain. For web based calendar connecting to Baikal's CalDAV, I use Agendav.

**Comment by jaapmarcus** [comment]
This issue is already open for almost 2 years and with the "cheap" exchange plans never going to be resolved. Feel free to create an pull  request if they want
