### ISSUE TITLE
[Bug] SSL error 10 at 3 depth lookup: certificate has expired"

### ISSUE THREAD

**Issue by buxjr311** [hestiacp/hestiacp#2164]
sudo /usr/local/hestia/bin/v-add-letsencrypt-host
O = Digital Signature Trust Co., CN = DST Root CA X3
error 10 at 3 depth lookup: certificate has expired"

**Comment by jaapmarcus** [comment]
There seems to be a bug with Lets encrypt it self...

For some reasons openssl verify can't verify the certificate. Errors seen:

O = Digital Signature Trust Co., CN = DST Root CA X3
error 10 at 3 depth lookup: certificate has expired

But also:

C = US, O = Internet Security Research Group, CN = ISRG Root X1
error 2 at 2 depth lookup: unable to get issuer certificate

Issue is caused by:

https://community.letsencrypt.org/t/help-thread-for-dst-root-ca-x3-expiration-september-2021/149190/540

**Comment by jaapmarcus** [comment]
We have made some changes it should be fixed

**Comment by gorfreed** [comment]
It's not just so you know. I am experiencing the same problem. 

C = US, O = Internet Security Research Group, CN = ISRG Root X1
error 2 at 2 depth lookup: unable to get issuer certificate

Certificates for sites are issues without a problem on the web interface.

**Comment by ScIT-Raphael** [comment]
As @jaapmarcus already wrote, the issue has been fixed for main branch. Will be included in the 1.5.0 release which will follow around next week.

**Comment by gorfreed** [comment]
But why closing the Github issue then? I mean, how do you verify with your users if this has been indeed resolved when you go live then? "We have made some changes it should be fixed" does not tell me anything about "has been fixed for main branch" either and made me look around for solutions while there was nothing to do but wait for your update. l

**Comment by wojsmol** [comment]
@gorfreed Related PR https://github.com/hestiacp/hestiacp/pull/2197

**Comment by jaapmarcus** [comment]
> But why closing the Github issue then? I mean, how do you verify with your users if this has been indeed resolved when you go live then? "We have made some changes it should be fixed" does not tell me anything about "has been fixed for main branch" either and made me look around for solutions while there was nothing to do but wait for your update. l

We have verified the bug on our own local machines. Identified what the root cause is and why this bug happens.  It happens due to the fact that LE has updated there certificates.

After that verified the patch on local machine and multiple users have tested it after questions regarding this issue via other methods then Github.

If we keep the issues open "after" an bug has been patched and wait until it has be released it will be unclear what the outstanding issues still are. 

Yes we sometime forgot to link the towards the pull request but on the other hand we are also humans and we make mistakes. 

All issues are closed when a Pull request has been merged into the main branch. Also there was an issue (https://github.com/hestiacp/hestiacp/issues/2195) exactly like this one as I remember there was still an issue but couldn't find it quickly this issue report. 

If you don't like this method feel free to run your own project with the scale of this...

**Comment by wojsmol** [comment]
> as I remember there was still an issue but couldn't find it quickly this issue report.

The issue was reported during our debug session on discord - https://discord.com/channels/737721354937303161/738055454285889597/902674214811758643 - at the beginning.
