### ISSUE TITLE
Bug: Error Message on installation routine (LXC only)

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#221]
### Brief issue description:
A error message appears on hestia installation routine.

### Operating system distribution and release:
Ubuntu 18.04 LTS, Proxmox LXC

### HestiaCP Version:
0.9.8-28

### What software is installed?
hst-install.sh --multiphp yes

### Additional notes:
chattr: Operation not permitted while setting flags on /home/admin/conf

**Comment by ScIT-Raphael** [comment]
Looks like this is a proxmox lxc issue only, will be closed for now: https://forum.proxmox.com/threads/issue-with-chattr-inside-lxc-container.43381/

**Comment by JOduMonT** [comment]
@ScIT-Raphael 
It might worth it to mention this is only if your LXC is unprivileged

I believe than instead of redirecting the error through [/dev/null](https://github.com/hestiacp/hestiacp/search?q=chattr&unscoped_q=chattr)
the user should be noticed at the end of the installation than he could decide to do or not
a `chattr +i` from the host (proxmox)
and execute something similar of this  `root@proxmox: chattr +i /pool/data/subvol-100-disk-0/home/admin/conf`

**Comment by ScIT-Raphael** [comment]
Thanks for the information, we will discuss this internaly.
