### ISSUE TITLE
Remove  CSS / JS in the default html page templates

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#226]
Can we please get rid of the CSS / JS in the default html page templates included in the latest version?

Hesita is a managment panel...not a CRM suite. We don't need such fancy things for something that is going to be deleted off anyways right after you create a domain.  JS is vulnerable and heavy, and just not needed here for this particular thing. I'd want to keep templates confined to a one single HTML file, you can much with it as well.  

I'm happy with all other things... even the fonts and icons included. This one thing is just overloaded extra.  Can we please make the templates into single HTML without any JS and inline CSS.

Thanks alot.

**Comment by johnnyq** [comment]
@mehargags I must say I do really like the new pretty html templates, but your right it may be a little much

**Comment by ghost** [comment]
Hi @mehargags,

Thanks for your feedback regarding the updated default page templates. 

We are currently utilizing the Bootstrap framework for responsive page layout across the whole template set (document errors, unassigned hosts, suspended sites, and the skeleton itself for creating new domains) and have chosen to provide these files locally instead of using the upstream CDN for availability. Right now there is some duplication of these files across the template set, which will be consolidated in an upcoming release to reduce the amount of space used.

This topic will be reviewed again for a future release as we continue to work on various aspects of the overall UI & user experience to bring it up to date, including these templates and other areas.

**Comment by mehargags** [comment]
I really appreciate the efforts Kristan...  it is just that I want efforts to go in at the more productive and needed things. I'll submit a few very important UI changes in a few days that enhance UE and ease out operation. Kindly consider changing the templates to one single file html + a robots... like the original.

**Comment by ScIT-Raphael** [comment]
Please be informed, that there is already work in progress - you can find it under this branch: https://github.com/kristankenney/hestiacp/tree/ui-refresh-dark-mode

We will adapt the branches soon to the hestia main project, merge them to beta when finished and merge under master when released.
