### ISSUE TITLE
[Feature] Add custom folder location for "Quick Install App"

### ISSUE THREAD

**Issue by fawwazid** [hestiacp/hestiacp#2264]
### Describe the feature or change in detail

Hello Hestia Team,

Looks good to add a custom folder location for "Quick Install App".

Thanks.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
Can you describe a bit more, what the change should be? It currently doesnt sound that clear.

**Comment by jaapmarcus** [comment]
You can drop in Custom installers in the same dir as every thing else it will not get overwritten by default. 

How ever make sure to create a Backup as always!

**Comment by fawwazid** [comment]
> Can you describe a bit more, what the change should be? It currently doesnt sound that clear.

Choose a folder location like "public_html" or "public_html/wordpress".

![custom_folder](https://user-images.githubusercontent.com/38886966/144205925-04ff0afc-f3c5-4d64-9cdf-7b1fb0612260.png)

**Comment by jlguerrerosanz** [comment]
Might be useful to host different technologies under the same domain.

**Comment by ScIT-Raphael** [comment]
You still would need to be able to point to them, which probaly would need a custom template or an .htaccess file, just in the case you use multiple subdomains. An other way would be to provide the sites from domain.tld/site1/ and domain.tld/site2/, but also here, does this really make sense?

**Comment by jaapmarcus** [comment]
For Nginx only it might still cause issues. 

For Nginx + Apache2 it should not be a real issue

**Comment by jlguerrerosanz** [comment]
If it might cause issues it would probably not be worth it since this can be accomplished via subdomain instead of subfolder. The SEO implications should not be that big and if they are, the application could be manually installed.

**Comment by arielesp** [comment]
actually, I already had been implemented this idea customizing installer - add a field in form and setting others lines in php installer

at nginx setup only, really has the problem when using more then one system in subfolders... its mandatory a customizetion in vhost ... normally I do manually because I had a lot of custom changes in hestiacp for my use.

at apache, just set .htaccess and working fine multiple systems.

whatever, would be important the option to define folder to auto install scripts
