### ISSUE TITLE
[Feature] Move Task Monitor button to the TOP Panel

### ISSUE THREAD

**Issue by cyber0pog** [hestiacp/hestiacp#2266]
Please, move or copy Task Monitor button to the TOP Panel like in Vesta
I use it every day 100 times, I'm already tired of entering the settings every time
![2021-12-01_22-34-12](https://user-images.githubusercontent.com/76199533/144264472-0cf20187-f8d5-46e1-b6f4-9aef091a4c8c.png)

**Comment by jlguerrerosanz** [comment]
If there is a hook for that menu you could easily insert any link that you feel like.

**Comment by cyber0pog** [comment]
> If there is a hook for that menu you could easily insert any link that you feel like.

And, How to find this hook?

**Comment by fra81** [comment]
Also other button like Firewall can be added, buttons that an IT admins use daily

**Comment by jaapmarcus** [comment]
@S-T-A-L-K-E-R-II   Please keep the "issue" issue template in place they are here for a reason.

We had in the past a direct link to the /list/server/ how ever due to lack of space and so on smaller screens + certain translations. This has been removed 

How ever due to the limitations and zero support for responsive design unless we change the layout it will never happen. 

There is currently no "hook" to add a php file into it and replace the full menu order or links and unless we are going to a new framework it will probally never happen... 

You can however you can via an hook as for example: https://docs.hestiacp.com/customize_hestia.html#can-i-run-certain-command-before-and-after-update

or 

https://github.com/jaapmarcus/hestia-hooks/blob/main/hooks/post_install.sh#L7-L8

How ever no securities are provided that it is never going to change...

**Comment by cyber0pog** [comment]
I have fifty server servers and every time looking for this resource manager is a bad and inconvenient undertaking
Records & Statistics - The most useless buttons in my life!

+ Logo href == Records href - what??? 

Please, replace Records button to the Task Monitor button, thank you!

**Comment by ScIT-Raphael** [comment]
@S-T-A-L-K-E-R-II how about monitor your fifty servers with a monitoring tool like icinga2? It will help to prevent a lot of manual work on your side. As @jaapmarcus already wrote, there is a reason we didnt place the link there and also will not change this behaviour.

**Comment by cyber0pog** [comment]
Stupid fashion instead of administrative convenience, OMG, hello from the future!

**Comment by ScIT-Raphael** [comment]
The good thing is that the project is open source, if you are not happy with it, fork it and build your own project. You got all you need, proper reason why we will not change it and a way over the hooks, where you can customize it and place it for your fifty servers. Please accept that, otherwise you're also free to have a look for another webpanel.
