### ISSUE TITLE
[Feature] Imunify AV (free license) as a option

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2285]
### Describe the feature or change in detail

ImunifyAV has a free version that can be integrated with hestiacp or just run in the same way that phpmyadmin open to the user.

ImunifyAV has the best database signature to find common malwares installed in php code. it works much better than clamav+maldet+rkhunter+sophos together (and wordfence for wordpress users).

I already setup with some hestia install the stand-alone version ( https://docs.imunifyav.com/stand_alone_mode/ ) and it works very good together with hestia environment. 

ImunifyAV version has free updates and manual scans or automatic monthly scans.

This solution already have integration with plesk, cpanel, cyberpanel and directadmin, but I do not think hestia need to spend a lot of time to integrate in the interface. Just put an alias like phpmyadmin does.

I think it will be a big feature to help internet to be free of botnets. This is being the best free tool to find malicious code in paid and free panels, for sure.

I can help to implement that, but i do not think hestia will have problems to implement. The most impotant decision will be where to setup the files.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by ScIT-Raphael** [comment]
We just discussed this with the team and we dont want to implement non open source software by default. Also we currently do not have enough time to fullfill this request.

**Comment by jlguerrerosanz** [comment]
I would love to have a better solution. In my experience immunify slows the server a lot. At least servers with +100 domains.

There is this PHP process constantly scanning in the background.

However how about we try to use clamav since it is already installed? Not to be activated by default of course but to have an easy option to get it up and running would be greatm

**Comment by gOOvER** [comment]
ImunifyAV is really bad. I know this from Plesk and it's slow, with free Version, as hell. (Paid is faster ;) ) Great, that such a shit not will be implemented

**Comment by ScIT-Raphael** [comment]
> I would love to have a better solution. In my experience immunify slows the server a lot. At least servers with +100 domains.
> 
> There is this PHP process constantly scanning in the background.
> 
> However how about we try to use clamav since it is already installed? Not to be activated by default of course but to have an easy option to get it up and running would be greatm

I don't really think that there is a need to implement something for a one line command to start a scan or an two-three line command to also send a email on a hit. This is basicly the same as for monitoring disk usage or load, should be set from sysadmin.

Personaly I would even think that a scan of `/home/*/web/*/public_html` with maldet would make even more sense: https://www.rfxn.com/projects/linux-malware-detect/

But also here, turn it on by default is never an option - due to the load generation it produces, this needs clearly be done or set from admin side.

**Comment by franciscopaniskaseker** [comment]
The problem for me is how much malwares it can identify. Clamav is not good and Maldet is not very good like imunify. I always send everything that I found to clamav and Maldet, but the feedback is almost zero and they continue not identifying some bots.

I understand the hestia decision and seems good to to have some guidelines of development. I like that. But clamav and maldet are not enough, unfortunately.

**Comment by ScIT-Raphael** [comment]
Depends hardly on the use case, for hestia, most cases would be wordpress infections, never had something that didnt got found trough maldet. But yeah, there are also other, paid and free AV like bitdefender, eset, even defender for endpoint which will probaly do a great job - just nothing we will or should integrate by default.
