### ISSUE TITLE
Increase width of template selection drop-down to accomodate long template names

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#234]
![2019-04-07_16-17-27](https://user-images.githubusercontent.com/2650395/55682500-24bbf980-5952-11e9-8e6a-8df028f50121.png)
Request to increase width of template selection dropdown <Select> to 580px to accommodate long template names. 

pls check screenshot  https://imgur.com/a/slatlHZ
![image](https://user-images.githubusercontent.com/2650395/55682493-07872b00-5952-11e9-8d10-9aeb6a377cd9.png)

**Comment by ghost** [comment]
Hi @mehargags,

Thanks for your feedback; this UI issue along with many others (such as the amount of wasted space and overall presentation of information) will be resolved by the interface refresh that is scheduled for an upcoming release. 

I'll close this for now, but if you have any other questions/concerns or comments please feel free to let us know and have a fantastic day. :)

**Comment by mehargags** [comment]
Hi Kristan,
Can you show me a preview of the UI improvements already under development ? Would be good if the core team can preview and share some thoughts while things are still in development. Infact I have some mockups already that could give you good clues about practical design.

Thanks

**Comment by ghost** [comment]
@mehargags,

There is currently an updated version of the user interface available in the **develop** branch, and a larger refresh planned when work on core functionality has been completed. If you would like to test code from this branch, first install a stable build using the master installer URL on a test server, log out and back in to refresh the environment, and then run the following commands:

`wget https://raw.githubusercontent.com/hestiacp/hestiacp/develop/src/hst_autocompile.sh`
`bash hst_autocompile.sh --hestia`

Enter **develop** for the branch and enter **y** to install.

If you have anything that you'd like to contribute, please submit a pull request so that it can be reviewed. Thanks for your feedback and have a great day.

**Comment by mehargags** [comment]
I tried to do that... on a fresh Ubuntu 18
After a few scrolls it gave me 
`
dpkg-deb: building package 'hestia' in 'hestia_0.9.8-29_amd64.deb'.
dpkg: error: cannot access archive '/home/gags/*hestia*.deb': No such file or directory
`

**Comment by ghost** [comment]
Please download hst_autocompile.sh again, it has been updated to correct the build directory where the *.deb packages are placed.

**Comment by mehargags** [comment]
yeh I managed to get it working... UI changes look cool. I do have a few suggestions Kristan, can we have a direct chat on skype for faster and easier communication ?  I have mocked up a few things, not sure where to attach them for you to consider it in roadmap
