### ISSUE TITLE
Changing Password does not work when using weak passwords?

### ISSUE THREAD

**Issue by NicolasLoew** [hestiacp/hestiacp#237]
### Brief issue description:
Issue with changing/setting passwords. When I choose a weak password (e.g. for testing purposes) it won't work. So try using smth. really easy "testing" or "abcdefgh". It says "Changes have been saved successfully" but when I try to login with the new password it won't work. Using the previous password however, it does. Also when using the "Generate" button for generating a secure password, it always works. This leads me to believe that there is some issue with small passwords. Now, this was only for testing, but if a client was changing his password to a weak one and try to log in again it'd be a problem as there is no message that says "You need to use a stronger password" or something similar.

### Steps to Reproduce:
1. Log into HestiaCP with a User Account
2.  Click on username at the top
3. Edit Password to a weak password, e.g. "testing".
4. Save changes.
5. Log out.
6. Try logging in with the new password.

### Expected behavior:
Pw should be changed.

### Operating system distribution and release:
Ubuntu 18.04 LTS, Vultr VPS

### HestiaCP Version:
Latest, 0.9.8-28

### What software is installed?
Standard install without any edits.

### Related issues or forum threads:
- 

### Additional notes:
Otherwhise good work guys! Lovin' the panel :)

**Comment by ScIT-Raphael** [comment]
Thanks for your input @NicolasLoew, it just looks like there is a bug in "edit user" interface, that appears on user only - admin works well. We will get it fixed soon!

**Comment by NicolasLoew** [comment]
Thank you for the swift response @ScIT-Raphael  :) Can you post again when it has been fixed?

**Comment by ScIT-Raphael** [comment]
Just pushed a commit, there was a mistake due to copy and paste the function code from admin to user templates: https://github.com/hestiacp/hestiacp/commit/b325dcd9d9ea6c5941f171c6056a3beb0e1829e7

It's currently in dev branch, will be tested in beta and released in master with a new version of hestia. If you want to test the file on your own, just replace the existing one in /usr/local/hestia/web/templates/user/edit_user.html.

Due to the fixed issue, I will close this ticket. Please feel free to reopen/recomment it or create a new one if you have any additional questions or further issues. Again thanks for your contribution!
