### ISSUE TITLE
[Bug] PhpMyadmin cannot login

### ISSUE THREAD

**Issue by ystartgo** [hestiacp/hestiacp#2420]
### Describe the bug

 mysqli::real_connect(): (HY000/1045): Access denied for user 'yntpcomy_mood699'@'localhost' (using password: YES)

### Tell us how to replicate the bug

Click db list page https://domain/list/db/
choose one db click phpmyadmin button redirect to login page ,show need to username and password  hestia-sso.php is not work.
try to use  username and password show  
mysqli::real_connect(): (HY000/1045): Access denied for user 'dbaccount'@'localhost' (using password: YES)
try to use  account : pma and password can login .

### Which components are affected by this bug?

Database (MariaDB, PostgreSQL)

### Hestia Control Panel Version

1.5.8

### Operating system

Debian 10.11 (x86_64)

**Comment by jaapmarcus** [comment]
For One click login https://docs.hestiacp.com/admin_docs/database/phpmyadmin-sso.html

With yntpcomy_mood699 and the database password it should work. 

Try otherwise 

mysql -uyntpcomy_mood699 -p localhost in command line 

We have not made any changes with database related things so please provide more info...
