### ISSUE TITLE
[Bug] Problem Server Error 500

### ISSUE THREAD

**Issue by Vladisaz** [hestiacp/hestiacp#2422]
### Describe the bug

I have a domain name along with a 202 character subdomain. Your panel does not accept this length and returns a 500 server error.

### Tell us how to replicate the bug

This is a panel error, I can not fix this error.

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

 v1.5.8

### Operating system

Debian-10

### Log capture

```shell
To test you need to create subdomains with a domain of at least 202 to 256 characters.
```

**Comment by ScIT-Raphael** [comment]
Please share the related weblog part for the 500 internal.

**Comment by jaapmarcus** [comment]
Please check /var/log/hestia/nginx-error.log
And 
/var/log/hestia/error.log

Also 

2022-02-17 15:08:41 v-add-web-domain  'user' 'ewcsqrwr2xc7rsslgipebr1fw5za52ixokgs2ajsolpd16pxeszf9r8umyigqqdsphkf6hxktblkxo6zgv4ek2mvqs1u7smmykrusc4bddj0qfnmzhoz80kmj97gshsgsh0ajs9dji1zefc1koqgfztoyosol8u1fi1co0dyz5nb8nsg0gnv347sip6rlpjenagapkyod9d9ltfbxsurmr9s43afi9huznkov8qy5rxek3fyjzduocci5cbczimz.net' 'xxxx' 'yes' 'www.ewcsqrwr2xc7rsslgipebr1fw5za52ixokgs2ajsolpd16pxeszf9r8umyigqqdsphkf6hxktblkxo6zgv4ek2mvqs1u7smmykrusc4bddj0qfnmzhoz80kmj97gshsgsh0ajs9dji1zefc1koqgfztoyosol8u1fi1co0dyz5nb8nsg0gnv347sip6rlpjenagapkyod9d9ltfbxsurmr9s43afi9huznkov8qy5rxek3fyjzduocci5cbczimz.net' ''

Seems to work fine. Please provide with method to reproduce the error...

Also please remind subdomain maximum length is 63 chars / part and max 256 overall length

**Comment by jaapmarcus** [comment]
The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.

For example, the following strings identify hosts in the Internet:

https://www.ietf.org/rfc/rfc1035.txt

**Comment by Vladisaz** [comment]
Here is an example link

**Comment by ScIT-Raphael** [comment]
Please check @jaapmarcus post and provide the related weblog, an example link doesnt provide anything else expect the 500 error code...

**Comment by jaapmarcus** [comment]
For Nginx / apache2

/var/log/nginx/domains/domain.com.error.log or 
/var/log/apache2/domains/domain.com.error.log

**Comment by Vladisaz** [comment]
> jaapmarcus
I'm not an experienced server user, write me a telegram  , I can't see the folder /var/log/hestia/error.log in the root of the server

**Comment by ScIT-Raphael** [comment]
The issue is related to the nginx fpm socket which itself has a lower, possible length than the domain name definition itself.

You will probaly find such a line in your logs:

`nginx: [emerg] too long path in the unix domain socket in upstream "unix:/run/php/php7.4-fpm-legalrc.com.garant-ofitsialnyy-garant-foruma-legalrc.garant-ne-torguyet-i-nichego-ne-prodayet.xxx.xx.sock"`

We also discussed it within our team: A potential fix would take multiple hours including the testing. Infact this is basicly a "one in a life time"-use case, we decided to not invest that much to fix the issue. If you want to sponsor fixing it, please feel free to step in contact with us over discord.

**Comment by jaapmarcus** [comment]
Did some investing and there is an limit of max 104 letters for sockets in Linux

By default we use 

unix:/run/php/php7.4-fpm-sub.domain.com.sock or unix:/run/php/php7.4-fpm-domain.com.sock 

This would give a limit for 74  (104 - 30 (unix:/run/php/php7.4-fpm-.sock)) for characters of the domain name + subdomain name.


In normal use case the max length for a domain is 63 + about 9 for the extension.. For those domains it will work fine. 

Option 1: 
Add an alias ( waytolongtomakesense.domain.com.domain.com.domain.com.domain.com) to   waytolongtomakesense.domain.com.domain.com.domain.com.domain.com

Option 2 if there is allready a domain active for:

Create an short subdomain and add  waytolongtomakesense.domain.com.domain.com.domain.com.domain.com as alias


It is possible to fix but it would mean we need to create a random sock file that can't already and extra code to verify that or  forget about it and don't care for such use cases... 

Current vote is for the last one... Other alternatives works fine ...

**Comment by Vladisaz** [comment]
Well, if you are not interested in the future of your product, then I will just go to the ISP manager panel, where all the problems have already been solved

**Comment by ScIT-Raphael** [comment]
> Well, if you are not interested in the future of your product, then I will just go to the ISP manager panel, where all the problems have already been solved

It isnt a "product" for us, we dont sell it or even earn enough money which will give us a normal paid revenue. We invest a lot of time in development and support, considered against the income trough donations we reveive, we probaly work for ~0.02 USD / hour.

I clearly have zero issues with your decission, to switch over to isp manager panel. Still we work on that project, because we like and love it, aswell as use it for our own infra. Sharing the source code, providing apt repo and support trough discord and forum is all for free - so take it like we provide it, or, as you've already written, use another product.

**Comment by Vladisaz** [comment]
I just pointed out your shortcomings, and it's up to you to correct them or not.

**Comment by jaapmarcus** [comment]
Fixing this issue would break existing installs and to risky for us. For +15k installs and +2k issues + 5k questions on the forum and discord you are the first with this issue. 

You can alter the limit set in Linux it but this is not a bug in Hestia it self...
