### ISSUE TITLE
[Bug] Mail SMTP relay + Forwarding to an external location doesn't work

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2518]
### Describe the bug

If you are using SMTP relay and want to forward to an other email address outside the current domain it will break. 

Some config changes need to be made to make it possible... 

### Tell us how to replicate the bug

Add mail domain
Enable SMTP relay 
Create a new mail account + forwarder to outside domain.

And send a email from an external source to email@domain.com and see it fail

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.4.0 and >

### Operating system

N/A

**Comment by jaapmarcus** [comment]
It looks like we need to add support for SRS at some point to allow support for it

**Comment by LucentW** [comment]
Hey @jaapmarcus,
chiming in to report that I'm impacted too by a similar issue, but can't really tell if it's the same one by reading your issue description.

What it's happening for me is that I have the SMTP relay enabled and a local mailbox with a forwarding to an external address. What happens is that Exim tries to deliver it on its own instead of relying on the relay, which _per se_ isn't directly related to SRS.

Obviously SRS would be a neat addition to prevent SPF mismatches.

**Comment by tegola** [comment]
I'll go out on a limb and say that me, @jaapmarcus and @LucentW have the same exact issue. I, too, am using using an SMTP relay (Mailgun) and a local mailbox with forward to an external address.

What happens is that the local mailbox correctly receives mail, but received messages are not forwarded to the external address.

**Comment by jaapmarcus** [comment]
Receiving works fine but the smtp relays blocks the email

**Comment by mrwinni** [comment]
Just starting to use hestiacp. I am completely overwhelmed how easy the setup process was and how smoothly everything works. Big thanks to everyone involved in this project!!!

The first problem I face is this one, using the SMTP relay from mailjet.
Any news on this yet?

**Comment by dyrer** [comment]
I am also have the same problem using sendinblue, no forward

**Comment by chriscapisce** [comment]
May I ask if this is (still) on the radar to be added/solved? @jaapmarcus you wrote before that it would require SRS and possibly a config rewrite/ more work. Would it take a lot of time to include this functionality? I ask because I see that [this](https://github.com/hestiacp/hestiacp/pull/3197) attempt to merge a commit was blocked.

**Comment by jaapmarcus** [comment]
Yes the  will solve the issue but it will not work on any exim that Is currently use.. 

When Debian 12 gets released will start testing and implementing it

**Comment by chriscapisce** [comment]
Thank you for your reply!

**Comment by dyrer** [comment]
There will be fixed only on Debian, but also on Ubuntu distros

**Comment by jaapmarcus** [comment]
It depends on Exim version...

**Comment by chriscapisce** [comment]
Which will presumably work on Ubuntu 22.04?

**Comment by jaapmarcus** [comment]
Support will be added for 1.8 for Ubuntu 22.04 or Debian 12

**Comment by chriscapisce** [comment]
Thanks for this @jaapmarcus! Will this also solve the smtp relay issue with auto-reply from within Roundcube?

**Comment by jaapmarcus** [comment]
Probally haven't tested it yet .. 

After it has been merged I will prepare a beta release

**Comment by chriscapisce** [comment]
Thanks again! 🙏
