### ISSUE TITLE
suggestion for mysql/mariadb datadir

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#255]
instead of forging `datadir=/var/lib/mysql`
why not `datadir=/home/mysql`
as most user probably have the reflex to make a big `home partition` _if they partition_ for their users

#### Another consideration
this project use /home to store web and mail data, so why not concentrate the data into a specific point ?

#### as an example
at hetzner, and other cloud provider such as  DigitalOcean and others;
you just have to install the OS than make a extensible volume for /home
your server is more flexible than ever.

**Comment by ScIT-Raphael** [comment]
@jodumont thanks for your input, I will discuss this with our team and inform you as soon as possible.

**Comment by johnnyq** [comment]
thats a good idea! @jodumont

**Comment by ScIT-Raphael** [comment]
@jodumont we've discussed this with our team and will implement it as soon as possible.

**Comment by ScIT-Raphael** [comment]
We rediscussed that feature request and came over, that we don't want to take the risk moving the data location for existing servers. Also we do not want to need to maintain two different data locations which also will produce an inconsistency between the systems. Due to that reasons, I'm going to close your feature request - sorry that it took that long!
