### ISSUE TITLE
[Feature] Mail Quota per package for different intervals

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#2579]
### Describe the feature or change in detail

We would like to set a mail quota per package, something like 50 mails a day for basic users, to forestall abuse and create a pricing structure.

I have found https://forum.hestiacp.com/t/limit-sent-emails/4086/2 and https://github.com/hestiacp/hestiacp/issues/777 but it does not seem like there is a user-/package-specific option.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Setting / user package shouldn't be an issue +/-  30 min of work. 

I don't know how easy it is to make settings xx mails / 1 hour for 1 user 
And xx mails / day for different user 


For: https://github.com/hestiacp/hestiacp/issues/777
is only set at account level when a user create an mailbox. 

https://forum.hestiacp.com/t/limit-sent-emails/4086/2
Can be set on domain level / server level or "mail" box. 



If we are going to implement it we should check first at "Mailbox" level
Domain
User account
Server

**Comment by xeruf** [comment]
You don't seem to have an email available either on your site or on Github, the contact form of https://eris.nu/ is broken (401 Unauthorized upon submission) and https://schipbreukeling.nl/ is also empty. How can I contact you about this? :sweat_smile:

**Comment by jaapmarcus** [comment]
Please send an email to info@hestiacp.com

**Comment by xeruf** [comment]
We are considering to switch to Postfix from EXIM due to perceived performance issues.
I have discussed with various people and they all recommended Postfix, making me wonder why EXIM is the default?

Would that make a difference on the implementation of this feature?

**Comment by jaapmarcus** [comment]
It was already since Vesta. So you should ask Sergey. 

We don't plan to replace it with something else or add support for a 2nd mail server. 

And I would prefer to see ipv6 support than replacing exim with a different mail server.

I never used Postfix so I really don't know. As we don't plan to add support for Postfix. I am not going to research it.

Support for setting per package has been added for some time I think it will be released with 1.7 I am correct. For the other there is probally not enough demand. 

Will close this issue. 

If you don't like the current stack we use the are probally 100 different control panels with different stacks..

**Comment by xeruf** [comment]
We have searched for a while, and there are actually rather few well-functioning general-purpose control panels out there.
But I thought there was Postfix available as an alternative in the setup?

**Comment by xeruf** [comment]
Thank You, the per-package option in 1.7 is fine :)
