### ISSUE TITLE
[Bug] Owncloud proxy template crashes apache2

### ISSUE THREAD

**Issue by Kissadere** [hestiacp/hestiacp#2629]
### Describe the bug

There's something wrong with this templates which prevents apache2 to listen on port 8443 after enabling this template on the web panel.

### Tell us how to replicate the bug

1. Copyt owncloud.tpl and owncloud.stpl from /usr/local/hestia/data/templates/web/nginx/php-fpm to /usr/local/hestia/data/templates/web/nginx/

2. Select that template from the web panel

3. Reboot your server and/or restart apache2

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.5.15

### Operating system

Ubuntu 20.04.4 LTS x86_64

**Comment by ScIT-Raphael** [comment]
You cant use this template, its for nginx only! Please have a look at https://docs.hestiacp.com/admin_docs/web.html#how-do-web-templates-work

I even think that owncloud can be runned on a
apache2 and nginx without any modifications. If you need them, copy the default.tpl/stpl file to owncloud.tpl/stpl and adjust it there.

Due to the template you probaly let nginx bind port 8443 which would explain the error output on discord.

Going to close the issue, because there is no bug - all runs as expected.
