### ISSUE TITLE
Logouts after short interval

### ISSUE THREAD

**Issue by saharakks** [hestiacp/hestiacp#2770]
### Describe the feature or change in detail

I have been logged out of admin panel after short interval this happens only with few website include HestiaCP, I found that it is due to some kind of configuration at  server on ISP side or you can say a security feature on ISP side which changes my WAN address after short interval for some purposes. Is it possible to have an option where i will be able to login based on session-id or something else not IP based or able to opt out such setting.

Thanks

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
We currently use combination of an Session id + Ip address to see if the user is logged in or not. This is to prevent if users session cookies got stolen then  it is still hard to abuse them.

**Comment by saharakks** [comment]
what about an option to enable or disable such option

**Comment by ScIT-Raphael** [comment]
an option would produce a security issue which personaly doesnt make any sense to me. If you have such changing public ip, you may consider a vpn to a jump in server - would also be good because you can whitelist that ip and harden the access even more. Currently, we do plan to implement a function to disable security checks.
