### ISSUE TITLE
[Delete]

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#2880]
Delete, found solution in another forum

**Comment by jlguerrerosanz** [comment]
This is already allowed. Please read the docs.

**Comment by roxyschram** [comment]
Okay, I have the latest and it's not allowing me. I have searched through the docs at https://docs.hestiacp.com and found nothing that resolved my issue. I tried keywords like, subdomains, domains, developement, sub accounts... no resolve. Maybe the docs need updated?

**Comment by roxyschram** [comment]
For example. account #1 as domain.com and account #2 I try to put DEV.domain.com and it tells me **domain.com** already exists. It doesn't say dev.domain.com exists.

**Comment by roxyschram** [comment]
So using the search feature on docs.hestiacp.com returned nothing useful, searching the exact same keywords in bing returned a page with how to do it in ssh. Not what I would called implemented feature since most people that manage accounts aren't going to be the same person that manages the software of the server through the terminal. I would really like to see this made able to manage through the panel itself.

**Comment by jlguerrerosanz** [comment]
Google: " hestiacp Correct process for creating a subdomain"

**Comment by jaapmarcus** [comment]
https://docs.hestiacp.com/admin_docs/settings.html
