### ISSUE TITLE
Cloudflare SSL not displayed in Hestia / Web tab

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#289]
### Brief issue description:
Cloudflare SSL is not displayed in Hestia / Web tab.

### Expected behavior:
The SSL should be displayed.

### Operating system distribution and release:
Ubuntu 18.04 LTS

### HestiaCP Version:
0.9.8-28 (and earlier versions)

### Which branch are you using?
Master

### What software is installed?
Nginx + PHP-FPM

### Additional notes:
This issue happens only with Cloudflare SSLs. I wasn't able to replicate it with any other issuers.

The problem seems to be the .crt file provided by Cloudflare. If you put the -----END CERTIFICATE----- line in the same line with the last line of the crt (not below), Hestia displays the certificate correctly (itself) but without the additional information that there are below. But it's better than nothing.

SUBJECT:  
NOT_BEFORE:
NOT_AFTER:
SIGNATURE: 
PUB_KEY:
ISSUER:

**Comment by JOduMonT** [comment]
I was curious because I also use Cloudflare but I never notice this

### it is true

I just add public and private key + the CA
hestia did'nt complain and the SSL certificate is activated

![image](https://user-images.githubusercontent.com/5204724/59254758-18de0380-8c31-11e9-8ffd-451422b2bab1.png)

### but nothing appear when I visit the configuration

![image](https://user-images.githubusercontent.com/5204724/59254552-b422a900-8c30-11e9-9037-1f324fd9c058.png)

**Comment by JOduMonT** [comment]
also in that particular case
it seams impossible to use the option: `Enforce HTTPS connections for this site`

**Comment by ghost** [comment]
Force SSL has been fixed in the **develop** branch and we're aiming to get a new release published soon; we've delayed this one a few times on account of fixing some bugs that we would rather not ship on account of rushing it out the door. Hang tight and thanks for your patience.

**Comment by ioannidesalex** [comment]
Cloudflare bug still exists, right?

**Comment by Lupul** [comment]
@ioannidesalex yes cloudflare bug is still unresolved

**Comment by ScIT-Raphael** [comment]
Fixed on dev branch, special thanks to @Lupul!
