### ISSUE TITLE
[Bug] exim4: Unrouteable address (with local domain, but using third mail service)

### ISSUE THREAD

**Issue by franciscopaniskaseker** [hestiacp/hestiacp#2901]
### Describe the bug

The hestia server has two domains in different accounts:
a.com
b.com

Both were using external mail services (gmail) and they can talk with each other.

Then I migrated the b.com mail services to hestiacp and now b.com can talk with any external service (gmail, outlook, hotmail etc), but it can not talk with a.com anymore, and vice-versa.

```bash
root@mail:/var/log/exim4# exim -bt test@a.com
test@a.com is undeliverable: Unrouteable address
```

I do not apply any rate limit, but maybe is related with https://github.com/hestiacp/hestiacp/issues/2666#issuecomment-1160241281

### Tell us how to replicate the bug

1. setup domain a.com and b.com (examples)
2. setup a.com dns to use third service email and b.com to use local mail service
3. a.com and b.com will not talk with each other and exim will "return is undeliverable: Unrouteable address"

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.6.7

### Operating system

Ubuntu 20.04.5

### Log capture

```shell
root@mail:/var/log/exim4# exim -bt test@a.com
test@a.com is undeliverable: Unrouteable address
```

```bash
root@mail:/var/log/exim4# exim -bt a.com
a.com@xyz.com
    <-- a.com@mail.a.com
  router = dnslookup, transport = remote_smtp
  host xyz.com [a.b.c.d]
```

```bash
2022-09-01 08:39:29 H=mail-oa1-f46.google.com [a.b.c.d] sender verify fail for <test@a.com>: Unrouteable address
```

**Comment by ScIT-Raphael** [comment]
Probaly you've created a.com aswell as mail domain on the hestia host? if yes, remove that one.

**Comment by jaapmarcus** [comment]
Probably the other way around a.com ...  Exim will use local delivery about remote delivery

**Comment by ScIT-Raphael** [comment]
noticed my mistake and corrected it already ;). Going to close, not a bug.

**Comment by franciscopaniskaseker** [comment]
> Probaly you've created a.com aswell as mail domain on the hestia host? if yes, remove that one.

I removed and now is working. Maybe this can be a new feature to the future: select remote or local mail service, like cpanel does. But at least now we have this documented here. thank you!

**Comment by ScIT-Raphael** [comment]
It doesnt make much sense as emails can only delivered at one host, you need to decide if you want to use hestia or the external host. Don't know if it is worth the work, but if you would like to see the function, you could still sponsor it :).

**Comment by franciscopaniskaseker** [comment]
I am saying because is common to have external mail services today to reduce spam problems and costs (amazon ses, gmail suite etc), but own web server to also reduce costs. And this people are interested in hestiacp and other free panels.

I am always ask for people that are interested in the feature to sponsor it or to donate to the project to help to maintain the project. I just troubleshoot problems and fix them at the moment.

I do not think this feature is really needed if we can just remove the mail domain from there. i just said because cpanel and plesk offer this option, but this is an easy move to fix.

**Comment by ScIT-Raphael** [comment]
Its indeed common, but its not common to have the mail domain aswell on the webhost - there is no need to create it, just skip that part and all will work well :).

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/242df31a98f2ef2bed20157189b9b61592625f0e/install/deb/exim/exim4.conf.4.94.template#L266-L291

Replace:
domains = !+local_domains

with 

domains = *

And restart

**Comment by belkisparada30** [comment]
Si me pueden ayudar, tengo varias cuentas DNS con una IP en el Hosting Hestia, pero no está aceptando enviar correos a la cuenta de Hotmail.com:
<html>
<body>
<div id="message-header" style="box-sizing: border-box; margin-bottom: 1rem; color: rgb(44, 54, 58); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 class="subject" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 700; line-height: 1.2; font-size: 1.5rem;">Mail delivery failed: returning message to sender<span> </span><a class="extwin hidden-small" title="Abrir en nueva ventana" data-hidden="small" id="rcmbtnfrm100" role="button" href="https://mail.ventas.pacal.cl/?_task=mail&amp;_action=show&amp;_uid=12&amp;_mbox=INBOX" onclick="return rcmail.command('extwin','',this,event)" tabindex="0" aria-disabled="false" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent; cursor: pointer;"></a></h2><div class="header" style="box-sizing: border-box; display: flex;"><img src="https://mail.ventas.pacal.cl/skins/elastic/images/contactpic.svg" alt="Foto del contacto" class="contactphoto" onerror="this.onerror = null; this.src = 'skins/elastic/images/contactpic.svg';" style="box-sizing: border-box; vertical-align: middle; border-style: none; margin: 0px 1rem 0px 0px; border-radius: 50%; width: 4rem; height: 4rem; object-fit: cover; background: rgb(244, 244, 244);"><div class="header-content" style="box-sizing: border-box; min-height: 4rem; flex: 1 1 0%;"><div class="header-summary" style="box-sizing: border-box; margin-top: 0.25rem;"><span style="box-sizing: border-box; display: inline-block;">De<span> </span><span class="adr" style="box-sizing: border-box;"><a href="mailto:Mailer-Daemon@panel1.pacal.cl" class="rcmContactAddress" onclick="return rcmail.command('compose','Mail Delivery System <Mailer-Daemon@panel1.pacal.cl>',this)" title="Mailer-Daemon@panel1.pacal.cl" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent;">Mail Delivery System</a></span><span> </span>el<span> </span><span class="text-nowrap" style="box-sizing: border-box; white-space: nowrap !important;">2023-01-31 23:52</span></span></div><div class="header-links" style="box-sizing: border-box; margin-top: 0.25rem;"><a href="https://mail.ventas.pacal.cl/?_task=mail&amp;_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&amp;_uid=12&amp;_mbox=INBOX&amp;_framed=1&amp;_action=preview#headers" class="headers-details" onclick="return UI.headers_show(true)" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent; font-size: 12.6px; margin-right: 0.5rem; white-space: nowrap; display: inline-block;">Detalles</a><span> </span><a href="https://mail.ventas.pacal.cl/?_task=mail&amp;_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&amp;_uid=12&amp;_mbox=INBOX&amp;_framed=1&amp;_action=preview#all-headers" class="headers-all" onclick="return UI.headers_dialog()" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent; font-size: 12.6px; margin-right: 0.5rem; white-space: nowrap; display: inline-block;">Cabeceras</a></div></div></div></div><div id="message-content" style="box-sizing: border-box; color: rgb(44, 54, 58); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="leftcol" role="region" aria-labelledby="aria-label-messageattachments" style="box-sizing: border-box;"><ul id="attachment-list" class="attachmentslist" style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; background-color: rgb(252, 252, 252); border: 1px solid rgb(244, 244, 244);"><li class="message rfc822 eml" id="attach3" style="box-sizing: border-box; list-style: none; display: inline-flex; white-space: nowrap; line-height: 2rem; padding: 0px 0.25em; max-width: 100%;"><a href="https://mail.ventas.pacal.cl/?_task=mail&amp;_action=get&amp;_mbox=INBOX&amp;_uid=12&amp;_token=GbObhsUY2pKQKm0qrNoOfNstOkrKSfal&amp;_part=3" onclick="return rcmail.command('load-attachment','3',this)" onmouseover="rcube_webmail.long_subject_title_ex(this, 0)" title="" class="filename" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent; line-height: 2rem; height: 2rem; display: flex; overflow: hidden; padding: 0px 0.2em;"><span class="attachment-name" style="box-sizing: border-box; overflow: hidden; text-overflow: ellipsis; color: rgb(44, 54, 58);">Parte 3.eml</span><span class="attachment-size" style="box-sizing: border-box; color: rgb(115, 118, 119); padding-left: 0.25em;">(~689 B)</span></a><a href="https://mail.ventas.pacal.cl/?_task=mail&amp;_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&amp;_uid=12&amp;_mbox=INBOX&amp;_framed=1&amp;_action=preview#" tabindex="0" title="Opciones" class="button icon dropdown skip-content" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent; position: relative; line-height: 2rem; height: 2rem;"></a></li></ul></div><div class="rightcol" role="region" aria-labelledby="aria-label-messagebody" style="box-sizing: border-box;"><div id="message-objects" style="box-sizing: border-box;"></div><div id="messagebody" style="box-sizing: border-box;"><div class="message-part" id="message-part1" style="box-sizing: border-box; padding-top: 0.5rem; position: relative;"><div class="pre" style="box-sizing: border-box; font-family: monospace; font-size: 13px;">This message was created automatically by mail delivery software.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">A message that you sent could not be delivered to one or more of its<br style="box-sizing: border-box;">recipients. This is a permanent error. The following address(es) failed:<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">  <a href="mailto:belkisparada30@hotmail.com" onclick="return rcmail.command('compose','belkisparada30@hotmail.com',this)" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent;">belkisparada30@hotmail.com</a><br style="box-sizing: border-box;">    host hotmail-com.olc.protection.outlook.com [104.47.59.161]<br style="box-sizing: border-box;">    SMTP error from remote mail server after pipelined end of data:<br style="box-sizing: border-box;">    550 5.7.1 Unfortunately, messages from [185.234.69.116] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to<span> </span><a rel="noreferrer" target="_blank" href="http://mail.live.com/mail/troubleshooting.aspx#errors" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent;">http://mail.live.com/mail/troubleshooting.aspx#errors</a>. [DM6NAM12FT008.eop-nam12.prod.protection.outlook.com 2023-02-01T02:52:56.703Z 08DB03E3F757F606]<br style="box-sizing: border-box;"></div></div><div class="message-part" id="message-part2" style="box-sizing: border-box; padding-top: 0.5rem; position: relative; border-top: 1px solid rgb(244, 244, 244); margin-top: 0.5rem;"><div class="pre" style="box-sizing: border-box; font-family: monospace; font-size: 13px;">Reporting-MTA: dns; panel1.pacal.cl<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">Action: failed<br style="box-sizing: border-box;">Final-Recipient: rfc822;<a href="mailto:belkisparada30@hotmail.com" onclick="return rcmail.command('compose','belkisparada30@hotmail.com',this)" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent;">belkisparada30@hotmail.com</a><br style="box-sizing: border-box;">Status: 5.0.0<br style="box-sizing: border-box;">Remote-MTA: dns; hotmail-com.olc.protection.outlook.com<br style="box-sizing: border-box;">Diagnostic-Code: smtp; 550 5.7.1 Unfortunately, messages from [185.234.69.116] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to<span> </span><a rel="noreferrer" target="_blank" href="http://mail.live.com/mail/troubleshooting.aspx#errors" style="box-sizing: border-box; color: rgb(0, 172, 255); text-decoration: none; background-color: transparent;">http://mail.live.com/mail/troubleshooting.aspx#errors</a>. [DM6NAM12FT008.eop-nam12.prod.protection.outlook.com 2023-02-01T02:52:56.703Z 08DB03E3F757F606]<br style="box-sizing: border-box;"></div></div><div class="message-partheaders" style="box-sizing: border-box; padding: 0.25rem 0.5rem; margin: 0.5rem 0px -0.5rem; border-top: 1px solid rgb(244, 244, 244); background-color: rgb(252, 252, 252);">

Asunto | prueba 23:52pm
-- | --
De | belkis.parada@ventas.pacal.cl
Destinatario | Belkis Parada
Fecha | mar 23:52

</div><div class="message-part" id="message-part3" style="box-sizing: border-box; padding-top: 0.5rem; position: relative; border-top: 1px solid rgb(244, 244, 244); margin-top: 0.5rem; margin-bottom: 0.5rem;"><div class="pre" style="box-sizing: border-box; font-family: monospace; font-size: 13px;"><span style="box-sizing: border-box; white-space: nowrap;">ambas pruebas de correo</span></div></div></div></div></div>
</body>
</html>Mail delivery failed: returning message to sender 
Foto del contacto
De [Mail Delivery System](mailto:Mailer-Daemon@panel1.pacal.cl) el 2023-01-31 23:52
[Detalles](https://mail.ventas.pacal.cl/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=12&_mbox=INBOX&_framed=1&_action=preview#headers) [Cabeceras](https://mail.ventas.pacal.cl/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=12&_mbox=INBOX&_framed=1&_action=preview#all-headers)
Parte 3.eml
(~689 B)
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [belkisparada30@hotmail.com](mailto:belkisparada30@hotmail.com)
    host hotmail-com.olc.protection.outlook.com [104.47.59.161]
    SMTP error from remote mail server after pipelined end of data:
    550 5.7.1 Unfortunately, messages from [185.234.69.116] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [DM6NAM12FT008.eop-nam12.prod.protection.outlook.com 2023-02-01T02:52:56.703Z 08DB03E3F757F606]
Reporting-MTA: dns; panel1.pacal.cl

Action: failed
Final-Recipient: rfc822;[belkisparada30@hotmail.com](mailto:belkisparada30@hotmail.com)
Status: 5.0.0
Remote-MTA: dns; hotmail-com.olc.protection.outlook.com
Diagnostic-Code: smtp; 550 5.7.1 Unfortunately, messages from [185.234.69.116] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [DM6NAM12FT008.eop-nam12.prod.protection.outlook.com 2023-02-01T02:52:56.703Z 08DB03E3F757F606]
Asunto	prueba 23:52pm
De	[belkis.parada@ventas.pacal.cl](mailto:belkis.parada@ventas.pacal.cl)
Destinatario	[Belkis Parada](mailto:belkisparada30@hotmail.com)
Fecha	mar 23:52
ambas pruebas de correo

**Comment by jaapmarcus** [comment]
You ip is blocked. Don't keep spamming Github, Forum, Discord and email...
