### ISSUE TITLE
[Feature] Protect backup from rotation (deletion)

### ISSUE THREAD

**Issue by ww7** [hestiacp/hestiacp#2964]
### Describe the feature or change in detail

Missing this feature for years.

I think it can be based on file renaming with adding some suffix (`-retain`, `-p` etc).

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
It would mean we need to rewrite the backup system. I don't think it is something I want to invest time into it... 

Also other control panels don't offer such feature.

**Comment by ww7** [comment]
Why rewrite? 
Just skip deletion for files with `-retain` and simple function/button for rename selected backups.

**Comment by jaapmarcus** [comment]
Because we still need to keep track of all the retained files. How do we want handle it if a user has 3 backup limit and retained 3 backups? Stop back upping? 

https://github.com/hestiacp/hestiacp/blob/a34bbf712be04070986ea4115b39369f095f8fdf/func/backup.sh#L409-L422

Loops trough all the files owned by the user and delete if it is larger then x backups. 

If you want to keep the backups for longer download the backup instead...

**Comment by ww7** [comment]
Retained backups are not about rotation, they should not be taken into counting.
Just add
```sh
backup_list=$(echo $backup_list | sed '/-retain/d')
```

**Comment by ww7** [comment]
@jaapmarcus You rushed to close this request. This feature is not false and not wrong.
Will try to develop this feature himself.
