### ISSUE TITLE
[Feature] Make security the default, and easier to configure

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#3261]
### Describe the feature or change in detail

We are in 2023, and websites without SSL simply should not exist anymore.
So why not make SSL with Let's Encrypt the default, so clueless users still get decent security?
Or at least a config option to set such defaults?

Furthermore, bulk actions might include adding LE SSL to domains without it as well:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/13354331/218346669-56882906-b925-45d4-9968-74a9b2210330.png">

Why do mail domains not have DKIM enabled by default?
Why can I only configure SSL for the mail domain after creation?

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by johnnyq** [comment]
I agree it should absolutely be default to have lets encrypt. This could also be a setting that can be set to auto fetch an ssl cert on creation which by default it enabled but can be disabled.

**Comment by ScIT-Raphael** [comment]
Turn it on automatically will generate a lot of invalid LE certificate requests, which will lead to a LE400 or later to an LE429 (rate limit) error. With more than 36k active servers, we would bother the letsencrypt servers in a unnecessary way.

Also bulk actions are a bit complicated due to the error and timeout handling - it would need a lot of additional interface changes which we do not want to invest on the "old" version. We can rethink to add this options when we're going to do a rewrite.

I'm with you, that ssl is a must have for a website, but due to the explanation above, it should be still manualy enabled (or over the api with a script).

**Comment by xeruf** [comment]
> Turn it on automatically will generate a lot of invalid LE certificate requests

Why? I turn it on for every website and rarely get an error, if there happens to be a malconfiguration.

**Comment by ScIT-Raphael** [comment]
Its explained above, also related to proper dns records and so on - if you use hestia for staging or internal environment without proper setup, it will generate a fail. even if this is on around 10% of every case, its still alot.

**Comment by Digioso** [comment]
My current situation would for example cause an error.
I am in the process of migrating my websites from a webhoster to a virtual root server with HestiaCP.
I've configured all of my domains in HestiaCP already, but some of them are still running on my old webhoster. If HestiaCP would try to automatically activate SSL for them, it would fail, because I haven't updated DNS records yet.

**Comment by jaapmarcus** [comment]
The only solution that I can think of to allow this:

User adds new "ilovehestia.com"
We create a temporary nginx.conf_test file with string containing a request to:
http://ilovehestia.com/.well-known/hestia-test with random string
Returns 404 or any other error
- Cancel it an 

If it works it should amuse DNS and so on are properly set an  request SSL.

**Comment by xeruf** [comment]
so can we reopen this to continue the brainstorming?

**Comment by ScIT-Raphael** [comment]
I still don't see any advantage for it, as explained above. We currently have a lot of other "construction sites" to do and this feature isnt really a "must have".

**Comment by xeruf** [comment]
Lets Encrypt has shown how vital SSL is and how easy it can be.
Anything that can easily be done by a machine should be done by it.
The advantage is that even non-tech-savvy customers, when they create a domain, will get security without having to care about it.
And for staging environments there could be a flag to not enable it by default.

Yes the batch-editing can be outsourced to a script.

**Comment by xeruf** [comment]
Maybe a way to set the defaults for such forms would be handy, even just via config file or environment variable - usually when I create a web domain I want DNS & Mail Support with DKIM and Lets Encrypt SSL.
Currently it requires a bunch of unnecessary clicks to get all that.

**Comment by ScIT-Raphael** [comment]
Please feel free to provide a PR with the suggested function.

**Comment by xeruf** [comment]
This would be my idea for the form when adding a new web domain:

- [x] SSL via Let's Encrypt (Web and Mail)
- [x] DNS Support
- [x] Mail Support
  - [x]  DKIM

In our case, we would like all of these checked by default.
