### ISSUE TITLE
[Bug] backup exclusions exclude everything

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#3427]
### Describe the bug

In version 1.7.x ( tested in 1.7.1 ), v-backup-user dont respect exclude rule as 1.6.4
when
WEB='domain.com:public_html'

1.7.1 exclude all domain creation
1.6.4 exclude works fine, excluding only public_html content

### Tell us how to replicate the bug

run v-backup-user user with exclude rule set
WEB='domain.com:public_html'

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.1

### Operating system

Debian 11

**Comment by youradds** [comment]
The problem seems to be coming from:

```
	# Parsing domain exclusions
	conf="$USER_DATA/web.conf"
	for domain in $(search_objects 'web' 'SUSPENDED' "*" 'DOMAIN'); do
		exclusion=$(echo -e "$WEB" | tr ',' '\n' | grep "^$domain\|\*$")
		if [ -z "$exclusion" ]; then
			web_list="$web_list $domain"
		else
			echo "$(date "+%F %T") excluding $domain" | tee -a $BACKUP/$user.log
		fi
	done
	web_list=$(echo "$web_list" | sed -e "s/  */\ /g" -e "s/^ //")
```

I'm not too sure how to fix it. 

`		exclusion=$(echo -e "$WEB" | tr ',' '\n' | grep "^$domain\|\*$")`

Will match:

test.com:public_html
and
test.com

Which then tells it to exclude the whole web domain. Doing

`*:public_html`

Correctly works:
```

2023-04-03 05:40:37 test.com
2023-04-03 05:40:37 excluding directory public_html
2023-04-03 05:40:37 test2.com
2023-04-03 05:40:37 excluding directory public_html
```

Maybe someone else has a suggestion to try?

**Comment by youradds** [comment]
@arielesp could you please try this tweak?

https://github.com/hestiacp/hestiacp/compare/main...youradds:hestiacp:patch-2

I *think* that sorts it (at least, with all the test I did). There seemed to be an issue with:

`grep "^$domain\|\*$"`

It wanted to be:

`grep "^$domain$\|^\*$"`

For some reason (bash isn't my first programming language :)), it looks like it was being treated as:

^$domain
OR
*$

Rather than acting like a Perl regex would work:

`^($domain\|\*)$`

**Comment by arielesp** [comment]
> @arielesp could you please try this tweak?
> 
> [main...youradds:hestiacp:patch-2](https://github.com/hestiacp/hestiacp/compare/main...youradds:hestiacp:patch-2)
> 
> I _think_ that sorts it (at least, with all the test I did). There seemed to be an issue with:
> 
> `grep "^$domain\|\*$"`
> 
> It wanted to be:
> 
> `grep "^$domain$\|^\*$"`
> 
> For some reason (bash isn't my first programming language :)), it looks like it was being treated as:
> 
> ^$domain OR *$
> 
> Rather than acting like a Perl regex would work:
> 
> `^($domain\|\*)$`

aparently, worked

**Comment by youradds** [comment]
Great. I've submitted a PR for review

https://github.com/hestiacp/hestiacp/pull/3434

**Comment by jaapmarcus** [comment]
Merged
