### ISSUE TITLE
[Bug] Misleading title "Error" on popup notification when creating manual backup

### ISSUE THREAD

**Issue by ErminMerdanovic** [hestiacp/hestiacp#3460]
### Describe the bug

Misleading title "Error" on popup notification when creating manual backup.
![image](https://user-images.githubusercontent.com/31346820/231379966-ed6aeb07-5531-47f1-b09a-a2d1c9d2783f.png)

### Tell us how to replicate the bug

1. Click on the Backups tab.
2. Click on Create Backup.
3. Backup notification will popup with the Misleading title "Error"

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.7.2

### Operating system

Ubuntu 22.04

**Comment by AlecRust** [comment]
This is arguably a regression in #3401, as we now show titles in dialogs in more places.

Simply removing this line should revert this "global dialog" code to previous behaviour (no title):

https://github.com/hestiacp/hestiacp/blob/f9c51984eb3684d5fa5e966ce800dbedca1d113b/web/templates/footer.php#L78

Perhaps that's the best fix for now, this is included in #3461. But it will mean legitimate "error" dialogs don't show the "error" title.

As you can see from surrounding code such as `if (!empty($_SESSION["error_msg"])):` it looks like this "Task has been added to queue" message is being set to `error_msg`. So this code is currently specific to error messages, hence the "Error" title. Ideally a wider refactor would take place here, perhaps allowing these "global dialogs" to be of type `notice` or `warn` or `error`, instead of just `error`.
