### ISSUE TITLE
[Feature] HTTP/3 for Nginx

### ISSUE THREAD

**Issue by oantonioo** [hestiacp/hestiacp#3483]
### Describe the feature or change in detail

I did a clean install Nginx + PHP-FPM (without Apache)
Is there a reason why it is installed with HTTP/1.1 when there is the possibility of using HTTP/2 or even HTTP/3?

Nginx flies with HTTP/3, the problem is that it doesn't with the default configuration... I had to rack my brains to configure it correctly and in the end I ended up surprised.

It is an easy suggestion to implement, but I understand that they do not see it as important.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by jaapmarcus** [comment]
https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/

It is not supported yet but in beta support

**Comment by jaapmarcus** [comment]
HTTP/2 is allready supported:
![Screenshot 2023-04-20 at 07 44 57](https://user-images.githubusercontent.com/9754650/233269366-4d6fa058-fcb4-47b4-b29b-01ea11b2286b.png)

As HTTP3 is still in test mode I don't see a reason why we need to to support it yet...

**Comment by enreda-net** [comment]
http3 is not in beta, but well I just wanted to explain that despite the fact that some say that it is not compatible with ngnix, I have managed to install it and it works, that is if the version is Pre-release.

about http2 which was my special concern.

You are right... it is installed and working for the added domains, I had to do the test since I didn't have any domain installed.

I made the mistake of looking at it over the hestiaCP panel and the panel if you use HTTP1.1. which is hard for me to understand, but I don't need clarification about it.

**Comment by jaapmarcus** [comment]
> http3 is not in beta, but well I just wanted to explain that despite the fact that some say that it is not compatible with ngnix, I have managed to install it and it works, that is if the version is Pre-release.
> 
> about http2 which was my special concern.
> 
> You are right... it is installed and working for the added domains, I had to do the test since I didn't have any domain installed.
> 
> I made the mistake of looking at it over the hestiaCP panel and the panel if you use HTTP1.1. which is hard for me to understand, but I don't need clarification about it.

Nginx has still not implemented it there software. As there packages is still in preview release and only available for 22.04 ... If you want to fund it so we can build our own packages and distribute it.  Go ahead.. But it will start at around 1000 euro / month...
