### ISSUE TITLE
[Bug] The Users are not listed for Admin

### ISSUE THREAD

**Issue by mike16os** [hestiacp/hestiacp#3546]
### Describe the bug

After Login as System Administrator, the Admin User can not see the user list anymore.

### Tell us how to replicate the bug

1. Login As System Administrator
2. Check the User List.

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.7.5

### Operating system

Ubuntu 20.04 (x86_64)

### Log capture

ERROR Log
```
of type float, string given in /usr/local/hestia/web/inc/main.php:373
Stack trace:
#0 /usr/local/hestia/web/inc/main.php(373): number_format()
#1 /usr/local/hestia/web/templates/pages/list_user.php(174): humanize_usage_size()
#2 /usr/local/hestia/web/inc/main.php(198): include('...')
#3 /usr/local/hestia/web/list/user/index.php(33): render_page()
```

**Comment by jaapmarcus** [comment]
What error do you see?

**Comment by jaapmarcus** [comment]
Check /var/log/hestia/nginx-error.log

**Comment by mike16os** [comment]
`#0 /usr/local/hestia/web/inc/main.php(373): number_format()
#1 /usr/local/hestia/web/templates/pages/list_user.php(174): humanize_usage_size()
#2 /usr/local/hestia/web/inc/main.php(198): include('...')
#3 /usr/local/hestia/web/list/user/index.php(33): render_page()
#4 {main}
  thrown in /usr/local/hestia/web/inc/main.php on line 373" while reading upstream, client: xx.xx.xx.xx, server: _, request: "GET /list/user/ HTTP/1.0", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "xx.xx", referrer: "https://xx.xx/login/"
2023/05/05 10:50:23 [error] 3551518#0: *165 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: number_format(): Argument #1 ($num) must be of type float, string given in /usr/local/hestia/web/inc/main.php:373
Stack trace:
`

**Comment by ifaist0s** [comment]
I have a similar problem: The list of users stops displaying after a certain user. In my case, I believe the problem is due to the following...

In Hestia UI I had created some Packages (/list/package/), one of them is the "NS-ONLY" which only allows DNS domains and nothing else. When I go to the list of users (/list/user/) I can see all the users up to (including) the user assigned the NS-ONLY Package. The rest of the users are not displayed, nor is the user counter at the end of the page (XX user accounts). If a assign another Package to that user(s), the list completes OK. The difference between the NS-ONLY Package and the other Package, is that NS-ONLY allows DNS Domain ONLY (no WEB, no Mail, etc).

Have a look at the screenshot: https://imgur.com/a/zfSQ4OP
Notice there are no Web/DNS/Mail domain number/icons next to the user. It's like something broke on the HTML/CSS/PHP part and the rest of the code/page is gone (I have the Firefox search bar at the bottom for you to see that this is the end of the page)

I do not know if my issue is the same as the OP or just similar.

**Comment by mike16os** [comment]
Changing the limit of the Packages fixes the problem.

**Comment by mike16os** [comment]
The limitations of packages were stored as Text "STRING/VARCHAR"
Now you have to update them and will be the required Number "Float/INT"

That's the problem.

**Comment by jaapmarcus** [comment]
No number format converts a float to a string ... have solved in the last pr

**Comment by jaapmarcus** [comment]
> The limitations of packages were stored as Text "STRING/VARCHAR" Now you have to update them and will be the required Number "Float/INT"
> 
> That's the problem.

```php
<?php var_dump(number_format(12.1243343,2));
```

Returns string(4) 12.12 

Then we number format it a second time ...

It seems it was mainly caused when the mb was set to 1000mb

**Comment by mike16os** [comment]
unfortunately, the value was 1000 in my case.

**Comment by jaapmarcus** [comment]
1.7.6 has been released addressing this issue
