### ISSUE TITLE
ssl stapling need improvement to be enable by default

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#355]
We have to figure something here

it is great the Hestia Teams think security but

or the ssl_stapling and ssl_stapling_verify are commented in /etc/nginx/nginx.conf
or Hestia let's the user to define the CA
or Hestia find a way to _detect/download_ the **SSL Certificate Authority / Intermediate**

> It is specially anoying when it is a self generated certificate

![image](https://user-images.githubusercontent.com/5204724/59728515-aecdeb80-923a-11e9-9d3b-10084c37befb.png)

### for cloudflare

it is simply a matter of monitoring change of those certificate
https://support.cloudflare.com/hc/en-us/articles/115000479507#h_30cc332c-8f6e-42d8-9c59-6c1f06650639

### for let's encrypt

it is those one: https://letsencrypt.org/certificates/

**Comment by ScIT-Raphael** [comment]
We know that ssl stapling will generate a notification on nginx restart/reload due to self signed certificates. We would suggest to use a let's encrypt cert for the backend, which you can do easy with the following commands:

v-add-letsencrypt-domain 'admin' $HOSTNAME '' 'yes'
v-update-host-certificate admin $HOSTNAME
echo "UPDATE_HOSTNAME_SSL='yes'" >> /usr/local/hestia/conf/hestia.conf

If I missed some point, please feel free to add more informations and reopen this issue!
