### ISSUE TITLE
[Bug] 8.0 & 8.2 not supported for ioncube?

### ISSUE THREAD

**Issue by vikasprogrammer** [hestiacp/hestiacp#3594]
### Describe the bug

We are trying to run this https://github.com/jaapmarcus/ioncube-hestia-installer but the ioncube doesn't get installed for PHP 8.0 and 8.2

Bug # 2 - PHP 8.1 service doesn't get restarted automatically. 

### Tell us how to replicate the bug

1. Run the script at https://github.com/jaapmarcus/ioncube-hestia-installer

### Which components are affected by this bug?

(Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.6.14

### Operating system

Ubuntu 20.04

### Log capture

```shell
PHP 5.6 successfully updated
PHP 7.0 successfully updated
PHP 7.1 successfully updated
PHP 7.2 successfully updated
PHP 7.3 successfully updated
PHP 7.4 successfully updated
PHP8.0 is currently not supported
PHP 8.1 successfully updated
PHP8.2 is currently not supported
```

**Comment by ScIT-Raphael** [comment]
The error message is clear and it isnt a bug: Ioncube just doesnt support php8.0 and 8.2 so it is impossible to install.

For the second bug, please create an issue report on the related github project.

**Comment by jaapmarcus** [comment]
See:

https://www.ioncube.com/loaders.php

Ioncueb doesn't support 8.0 (Not planned) or 8.2 (Not yet) 

Will you be supporting PHP 8.0?

https://blog.ioncube.com/2022/08/12/ioncube-php-8-1-support-faq-were-almost-ready/

We will not be supporting PHP 8.0. Much like with our version 10 release, we decided early on to skip over the x.0 PHP release as those can tend to be incomplete but mainly because it allows us more time to work on things our end. PHP 8 support will come in version 12 starting with PHP 8.1.
