### ISSUE TITLE
Login as 'user' loops you out to 2FA

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#375]
After yesterday's upgrade, when I login as admin and then click a user to login as that user, I'm presented with login screen again and it asks for user/pass with 2FA. 
Giving admin user/pass then it redirects to .../inc/2fa/active.php?user=admin and gives page not found.

Some kind of loop here, may be because it is not finding custom templates setup for websites or similar error. 

Pardon the brevity of this message, I'm typing this from my phone

**Comment by Lupul** [comment]
Could not reproduce on a clean Hestia install on Ub18.04 ( Apache:yes, Nginx:yes, php-fpm:yes )
What features were enabled in Hestia before upgrade and which os/ver? (nginx multiphp exim etc )

**Comment by ScIT-Raphael** [comment]
I also checked the codepart for the loginas function, it is in top of the login procedure and does not have a "way out", so the code execution will be even canceled or you will be forwarded to /list/user or if you have set a loginas user to /list/web: https://github.com/hestiacp/hestiacp/blob/f651a7cc81fef548a015ab079590067ffde401f3/web/login/index.php#L17https://github.com/hestiacp/hestiacp/blob/f651a7cc81fef548a015ab079590067ffde401f3/web/login/index.php#L17

As far as I see the code, there is now way that the 2fa code part will be executed again when you are logged in as admin.

**Comment by mehargags** [comment]
My Stack was Nginx only...
I came back today from Vacation and could login fine as a second user from super admin.  Can't say if it is a bug resolved or was it the choppy internet connection... but I sure had a loop throwing me out to 2FA from Firefox and Chrome on MAC OS

**Comment by ScIT-Raphael** [comment]
Just noticed that you wrote it will "redirect" to ../inc/2fa/active.php?user=admin (was already late yesterday) - this is a built in function using javascript which you can see here: https://github.com/hestiacp/hestiacp/blob/f651a7cc81fef548a015ab079590067ffde401f3/web/templates/login.html#L28

So it really looks like a issue on client side due to choppy internet connection, the function just checks if user has 2fa enabled and show the token box if true. I will close the issue for now, please feel free to repost if you have any additional informations or open a new one.

**Comment by blaineam** [comment]
every time I sign in as the admin user for my ubuntu 18.04 hestiacp server I experience this same bug. it occurred on version 1.0.6 and now again on 1.1.0 Im using macOS Catalina Safari browser and the 1password browser extension. it allows me to paste the 2fa code in and then it reloads the login page the first sign in attempt stating invalid or missing token and then the second attempt always loads the path /inc/2fa/active.php?user=admin with a white page and a 200 status. then deleting the path and signing in once more with the same process of using 1password it actually makes it sign me in. It happens every time I sign in and I know it isn't an internet connectivity issue for me. the bug seems to be isolated to safari browser as it doesn't happen when using google chrome browser.
