### ISSUE TITLE
[Bug] Delete a DNS record with ID 0 will delete the entire domain

### ISSUE THREAD

**Issue by softcodex-team** [hestiacp/hestiacp#3990]
### Describe the bug

I create a DNS record from command line, wiith ID parameter 0 (type error)
Deleting this record from UI will cause entire domain to be deleted

### Tell us how to replicate the bug

1. run v-add-dns-record USER DOMAIN RECORD A IP '' 0
2. this create the dns record with ID 0
3. delete it from UI
4. entire dns domain disappear from list and from config /home/USER/conf/dns

### Which components are affected by this bug?

Control Panel Backend, Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.7

### Operating system

Ubuntu 20.04

**Comment by sahsanu** [comment]
I was able to reproduce the same bug in HestiaCP version `1.8.7`.

This is the error I got:

`[error] 60942#0: *277 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: ksort(): Argument #1 ($array) must be of type array, null given in /usr/local/hestia/web/list/dns/index.php:98`

And this is the code causing the error, seems `$data` is not an array an `ksort` can't manage it.

```
        exec(
                HESTIA_CMD .
                        "v-list-dns-records " .
                        $user .
                        " " .
                        quoteshellarg($_GET["domain"]) .
                        " 'json'",
                $output,
                $return_var,
        );
        $data = json_decode(implode("", $output), true);
        if ($_SESSION["userSortOrder"] == "name") {
                ksort($data);
```

My knowledge of php is zero so I don't know how to solve it from php side but maybe it should be good to disallow the use of 0 as an id record.

This is an approach to solve it modifying `func/main.sh`:

Changing this:
`id) is_int_format_valid "$arg" 'id' ;;`
To this:
`id) is_id_format_valid "$arg" 'id' ;;`

And adding new function `is_id_format_valid`:
```
# DNS record id validator
is_id_format_valid() {
        if ! echo "$1" | grep -qE '^[1-9][0-9]{0,}$'; then
                check_result "$E_INVALID" "invalid $2 format :: $1"
        fi
}
```

Well, this is simply a first approach to prevent the bug from occurring.

**Edit**: Seems that due `ksort `error, the `record_id` is empty so when trying to delete the record, this is the code executed `web/delete/dns/index.php`:
```
// DNS domain
if (!empty($_GET["domain"]) && empty($_GET["record_id"])) {
        $v_domain = quoteshellarg($_GET["domain"]);
        exec(HESTIA_CMD . "v-delete-dns-domain " . $user . " " . $v_domain, $output, $return_var);
```

And instead of executing the command `v-delete-dns-record`, as the `record_id` is empty it uses command `v-delete-dns-domain` and the dns domain is completely removed.

**Comment by jaapmarcus** [comment]
I don't have issues with ksort issues 
<img width="1103" alt="Screenshot 2023-09-09 at 23 20 45" src="https://github.com/hestiacp/hestiacp/assets/9754650/9e7e1401-f213-452a-b268-fba5a820fb2c">

How ever we should prevent ID zero from being created ...

ON the second comment:
I am sure var_dump(empty(0));

Will return "true" so even if record_id exists and if it is set to "0"..  I  :heart: PHP in this case. 

As we assume 0 is never a valid id I think we should not change this behaviour ...

**Comment by sahsanu** [comment]
> I don't have issues with ksort issues

The problem with ksort appears when you try to remove the record with id 0 from Web UI. After doing it, you should get a beautiful Internal Error and when you list the zones, the entire zone has been deleted (make a backup of the zone if you want to try it ;))

**Comment by jaapmarcus** [comment]
Because It doesn't exists any more ... 

Attached PR will fix the bug for creating it ...
