### ISSUE TITLE
Error: Let's Encrypt validation status 400 for Master Branch

### ISSUE THREAD

**Issue by hanzicode** [hestiacp/hestiacp#404]
### In a few words, please describe the issue that you're experiencing:
Basically I tried to use the Hestia panel (master branch) to issue Let's Encrypt SSL for certain websites and then I got the following error:

> Error: Let's Encrypt validation status 400

### What steps did you take when the issue occured? 
1. Click on the domain.com under Web
2. Pick Enable SSL for this domain
3. Pick Use Lets Encrypt to obtain SSL certificate and then click on Save

### Expected behavior:
Error as above

### Operating system distribution and release:
Debian 9

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`

VERSION='0.10.0'

### Which branch are you using?
master

### Which of the following web server configurations are you using?
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

Don't know which log file to look into

### Related issues or forum threads:
I had no such a problem after switching from VestaCP. This problem happened after recent automatic system upgrade

### Additional notes:
I had already sent you the login credentials to you for another resolved issue listed here: https://github.com/hestiacp/hestiacp/issues/381

**Comment by ScIT-Raphael** [comment]
Please check inside of the "hestia" user - it seems you have a invalid dns OR invalid e-mail address. I created a test domain with ssl certificate - worked properly.

**Comment by vasike** [comment]
i get the same for "default" Cron job on this

Cron <admin@name> sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl

domain1.xxx Error: Let's Encrypt validation status 400
domain2.xxx Error: Let's Encrypt validation status 400

**Comment by ScIT-Raphael** [comment]
we have prepared a fix for let's encrypt in some special cases, can you try to run the following code:
```
wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/bin/v-add-letsencrypt-domain -O $HESTIA/bin/v-add-letsencrypt-domain
wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/bin/v-add-letsencrypt-user -O $HESTIA/bin/v-add-letsencrypt-user
chmod +x $HESTIA/bin/v-add-letsencrypt-domain
chmod +x $HESTIA/bin/v-add-letsencrypt-user
# Then rerun v-update-letsencrypt-ssl and check if it works now.
v-update-letsencrypt-ssl
```

**Comment by v3g0** [comment]
it still does not work

VERSION='1.0.5'
Ubuntu 18.04

**Comment by ScIT-Raphael** [comment]
@v3g0 can you please describe, what exactly doesnt work? Maybe open up a separate issue report and follow our procedure.

**Comment by vasike** [comment]
> i get the same for "default" Cron job on this
> 
> Cron [admin@name](mailto:admin@name) sudo /usr/local/hestia/bin/v-update-letsencrypt-ssl
> 
> domain1.xxx Error: Let's Encrypt validation status 400
> domain2.xxx Error: Let's Encrypt validation status 400

i confirm i do not receive those cron job emails anymore - hestia autoupdated to 1.0.5

**Comment by ScIT-Raphael** [comment]
@vasike thanks for your update, glad the update fixed your issue!

**Comment by v3g0** [comment]
Temporary vhost nginx and htaccess files for verification purposes Lets Encrypt does not work. 

Adding verification files such as in VestaCp to the v-add-letsencrypt-domain file helped verify the new domain, but it doesn't work with more complex ngnix and htaccess configurations.

**Comment by ScIT-Raphael** [comment]
@v3g0 if you like, you can open a new issue report and provide as much informations as possible, so we can have a look.

**Comment by Trobolit** [comment]
Same issue. Brand new install on Ubuntu 18. Successfully ran the certbot --apache script and obtained a SSL certificate.. Tried to manually input it no success.

**Comment by ScIT-Raphael** [comment]
@Trobolit Please open a separate issue and fill out the template. Also validate that you've got a valid mail address in user settings, valid dns records without ipv6 and a open connection on port 80.

**Comment by Trobolit** [comment]
@ScIT-Raphael Decided to abondon this setup. I'm not paying for error messages that don't say anything. 
My server was on the WAN side of the switch, static public IP. Valid email, valid DNS records etc.

**Comment by ScIT-Raphael** [comment]
@Trobolit You're of course free to do that - even when you don't have to pay anything for hestia :). And if you want to have also free support, you need to share more informations, not only "same issue" and "does not work" - there are multiple sources of potential issues causing this error.

**Comment by Trobolit** [comment]
@ScIT-Raphael You're right.
What I meant to say is that I was hoping this would automate setup of wordpress but the softtacolous package (or whatever it's called) has wordpress being paid for.
That said I'd rather make my own scripts for that and then I don't really need this CP.

Further if all I get from a software is an error code and limited insight into why I really don't feel like fixing or working around it is worth my time. I could pay Microsoft for giving me that. :P
Therefore it is hard to give you more info. It's an older HP server, clean fresh install of ubuntu 18.04 LTS, fresh install according to documentation of the CP, correct DNS records with wildcard enabled, public static IP outside of the firewall, and when I try to use a domain with lets encrypt  I don't get any more info than has already been provided here. Which is why it's hard to give you more.

Therefore I will be looking into other solutions.

**Comment by ScIT-Raphael** [comment]
@Trobolit Sure, I wish you good luck and all the best!

**Comment by ghost** [comment]
@Trobolit, just to confirm you've also set the CAA DNS record for Let's Encrypt as well and not just a wildcard alias on the web domain itself? This is required for the certificate to be issued otherwise you will encounter error 400.

Just FYI, there is a replacement for Softaculous that we've implemented beginning in 1.1.0 which can automate the process of installing WordPress and some other applications as well. Whether you choose to seek another solution or not is up to you and in any case hope that you are able to find a solution to accommodate your needs regardless of if that is Hestia or another panel, however we are trying our best to address the issues and concerns given our limited resources and time.

**Comment by Trobolit** [comment]
@kristankenney 
You know, I think I may owe this forum an apology. I've only set DNS record to my server, A, @, *, etc.
Nothing for the CAA.

And along with the info of 1.1.0 and Wordpress, heck, I think I spoke too soon!

I'll be back if I get it up and running!

(But please, lets strive for better error messages!)

**Comment by ScIT-Raphael** [comment]
@Trobolit That was what I meant with "additional informations", so in your case the 400 authorization error was what it was :). Let us know, if you have any other issue, we're here to help!

**Comment by Trobolit** [comment]
@ScIT-Raphael 
Hehe thanks again! And again sorry for my attitude.

**Comment by Trobolit** [comment]
@ScIT-Raphael 
Whats the correct way of asking for help regarding this?

I did a reinstall of ubuntu 18.04.3, then a standard install of hestia.
I then ran the following as root in root home:
`wget -O $HESTIA/bin/v-update-sys-hestia-git https://raw.githubusercontent.com/hestiacp/hestiacp/master/bin/v-update-sys-hestia-git`
`chmod +x $HESTIA/bin/v-update-sys-hestia-git`
Followed by this command in the bin folder of hestia:
`cd /usr/local/hestia/bin/`
`./v-update-sys-hestia-git master`

I restarted the server.
I can log in as admin in the control panel, but cannot save anything.
Adding a user, wont save. Adding a domain, wont save.
I can't see anything in the system error log.

> root@gazelle2:~# tail /var/log/hestia/system.log 
> 2020-01-09 16:15:29 v-delete-firewall-chain  'FTP'
> 2020-01-09 16:15:29 v-delete-firewall-chain  'MAIL'
> 2020-01-09 16:15:29 v-delete-firewall-chain  'MAIL'
> 2020-01-09 16:15:29 v-delete-firewall-chain  'HESTIA'
> 2020-01-09 16:18:24 v-add-firewall-chain  'HESTIA'
> 2020-01-09 16:18:24 v-add-firewall-chain  'SSH'
> 2020-01-09 16:18:25 v-add-firewall-chain  'FTP'
> 2020-01-09 16:18:25 v-add-firewall-chain  'MAIL'
> 2020-01-09 16:18:25 v-add-firewall-chain  'MAIL'
> 2020-01-09 16:18:25 v-add-firewall-chain  'HESTIA'

What should my next steps be? Where should I post this?
kind regards

**Comment by ScIT-Raphael** [comment]
Basicly i would not recommend to switch to master branch, this is in current development and should not be used as productive server. We will have a deep testing for the next week, so you would need to have a little bit of patience, we will ship 1.1.0 soon!

**Comment by Trobolit** [comment]
@ScIT-Raphael Allright! No worries.
Would you recommend:
a) reinstall of OS and stable Hesta and just wait
b) some downgrade option?
c) a) but install wordpress manually and hope that it will still work smooth with the automated process coming up in a few weeks?

**Comment by ScIT-Raphael** [comment]
If you want to use Hestia, of course a :). Also you can combine it with c.

**Comment by Trobolit** [comment]
I restarted the server, and the not saving problem seems intermittent, but during the times that it does work things work very well!
Do add to the wordpress installation script a line about removing the original (working hat) index.html.
Otherwise the wordpress site will not show, but once removed it all works.
I'll stick with what I have for now and then do a full reinstall once 1.1.0 is officially out :)
