### ISSUE TITLE
[Feature] Specify while creation a custom mail domain

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#4084]
### Describe the feature or change in detail

Hello!

Currently, one cannot have any custom mail domains. The system adds a default subdomain having **mail**.domain.com.

There are thousands of users using Cloudflare. They also have multiple VPS. If Hestia is installed on One VPS, this will have mail.vpsOne.com by default. Thereafter, it is not possible to create any further mail domains on any extra VPS because Cloudflare will not permit extra subdomains. On the second VPS, how can one create the mail domain because the subdomain is mapped to the frist VPS.

But it is fundamental to have multiple VPS to receive emails, like VPS1, VPS2, etc having delivery priorities. One these VPS, it is not possible to create mail domains and use Let's Encrypt certificates.

If one adds multiple IP to mail.vpsOne.com, then it will work theoretically by a round robin IP but there will be no master. Let's Encrypt will not be usable too. It is not possible to create any Let's Encrypt SSL certificate on a round robin IP mapped list of email servers. There are more practical difficulties, if the mail.vpsOne.com is forced on users. It can be there but if a user chooses to have custom domain for emails, this should be possible. The only problem would be to create the respective exim config.

### Would you like to sponsor this feature to have it implemented?

No

**Comment by Skamasle** [comment]
Hi

I dont understand the issue,

You want in same VPS 
mail1.vps.com
mail2.vps.com
somemail.vps.com

As mail host ?

And then you want users cant connect to SMTP with SSL ?

Soyou want have SNI in SMTP ? ( Server name indication like SSLs in port 443 multiple SSL for SMTP ) ?

**Comment by DeRaja** [comment]
Hello!

Yes, you truely did not understand the issue and this was never discussed in the forum, where I am a member (and also a user of HestiaCP) since many years. 

The target is to use - for example three email servers like below:

mail.vps.com ---> 1.1.1.1  ---> Priority 10 ---> MasterEmailServer
mail2.vps.com ---> 2.2.2.2  ---> Priority 20
somemail.vps.com ---> 3.3.3.3  ---> Priority 30

**These three VPSes are hosted with three different providers in three different datacenters.**

Usually, the primary mail domain mail.vps.com will receive all emails. For any reasons it cannot, emails will be delivered to mail2.vps.com, if this fails, it will be delivered finally the last one somemail.vps.com.

It is common in such a setup that there is a sync function using some other utility. If any email is captured by the second or the third, it will appear (due to sync function) in the MasterEmailServer after few minutes.

It is possible to create Let's Encrypt on the first VPS mail.vps.com.

On the second VPS, I will have to create  Let's Encrypt. But that subdomain is mapped to the first one and SSL is not possible anymore.

Therefore, it is necessary to have a possibility to enter a customain domain mail2.vps.com.

Remark: Cloudflare allowed only a second level of subdomains like mail.vps.com but not like One.mail.vps.com, Two.mail.vps.com, etc.

**Comment by jaapmarcus** [comment]
We don't currently have support for MX fail over so the use case for this would be currently less then 0.. 

If you really want you can use mail2.domain.com has hostname or even create DNS record. Hestia / Exim doesn't care about.

**Comment by jaapmarcus** [comment]
I assume this is the topic?
https://forum.hestiacp.com/t/reserve-mail-server/11458

**Comment by DeRaja** [comment]
Hello Marcus!

I saw the topic. It is not exactly the same but near to it.

It is most important to respect someone's feature request and keep it open, instead of closing at a lightening speed. A feature request is opened requesting the group or community to work togather or exchange ideas or give solution. I certainly know that you are one of the main drive behind this work. But that also should be that you give a thought on your closing a feature request without giving any solution.

You are working on this coding like a dictator. You command everyone to enforce your ideas to use mail.domain.com. We are all users and you do not respect that we are using your commanding manner of coding activity.

Wheather it is a mail failover or not, I do not want to use the mail.domain.com at all. It is a subdomain that is very easy to guess by scammers and hackers.

But you do not even care to understand the very nature of the issue I have raised and have closed at a lightening speed. This is your regular habit in the forum also. When will you learn to change? When will you stop telling all users to get lost and not to use HestiaCP, if they do not like your commanding coding?

**Comment by Skamasle** [comment]
Your solution for this is just create subdomain  and assign it as MX.

And this will work as mx

You can use same wildcard SSL for 3 servers or not

As you use it as mx for EXIM  is irrelevant what is the max name

You may ha e the hostname of server like hi.domain.com and send email to
bye.domain.com and all will work, just create mx in cloudflare.

The uniq issue I see is the let's encrypt SSL.

But as I say you can't sync some wildcard on all servers

**Comment by DeRaja** [comment]
Hello Maksim!

Yes, I am using the same approach without wildcard SSL the remaining part of your suggestion since many years. I used a self cretated SSL for the second and third server. This has some disadvantages that many email servers like mail.google.com will refuse to deliver on second and third email servers, although all other parameters are equal.

I was planning to publish my solution to the HestaCP community in this thread instead of giving a pull request. However wanted to use my basic solution for their servers, they can.

But Markus Jaap made me angry again with his dictatorial declaration that any other solution by any other programmer **DARE NOT BE PART OF THE HESTACP CODING** because this is in conflict with his choice of enforcing hard coded email domain names.

Thanking you for your suggestion. My dear young friend, both of us, you and me, were supporting other users in Vesta forum supporting before many years, long before HestaCP was born. I am a senior administrator working since three decades on Linux. I am able to find all such solutions. However, after I found out the personality of Markus Jaap, I have refused to participate in active support to the HestaCP community. He is not a person I like to work with because of his limited vision to  perceive a problem and finite method to create a solution.

However, I felt like opening this as a feature request because my young friend Maskus Jaap has been pumping his personal taste of hard coding his choice of subdomains as well as maintaining it since many years. At the time of opening, I had already known that Markus will immediately refuse to do or support any activity of change. This is his personality, to show a deaf ear to one of the most fundamental feature request that triggers the very hard core of daily functioning.

So this feature request also raises to create some awareness to Markus Jaap. He is doing a fantastic job of coding. He has made this entire Hesta thing to be a very important piece of his programming work. But he has to also understand that his own taste is one thing. But if he were to offer his work to this community, then he can integrate and delevop his work for a larger acceptance. 

A coder offering his excellence should view the requirement of the community and develop from the eyes of the general user. That is the issue in parallel that Markus has to keep in mind.

**Comment by DeRaja** [comment]
Hello Skamasle,

I politely request you to delete your answer or delete the quotation of my (deleted) reply. My intention was to send an email to Markus and not have my answer remain here forever. Upon your quoting my older answer in your solution, it remains here. 

Thanks for your understanding.

**Comment by jaapmarcus** [comment]
Cloudflare support child domains:
https://developers.cloudflare.com/dns/zone-setups/subdomain-setup/setup/

Changes in Exim for on demand are painful but if you can get it working feel free to submit a PR.]

How ever from our "team" side we don't see any use for it ...

**Comment by ghost** [comment]
Markus, the Zone and DNS has nothing to do with this issue because of the differences in plans. By paying thousands of dollars, one can get almost everything from Cloudflare. There are too many users, who do not want to pay even $5 or $10.

The intention is to use free Let's Encrypt SSL certificates. In a free plan, this option is not available to use SSL for Sub.Sub-domain.com or www.Sub.Sub-domain.com or mail.Sub.Sub-domain.com. This was discussed here in the forum long time ago:

https://community.cloudflare.com/t/what-is-the-best-way-to-handle-this-multiple-subdomains-ssl/38731/8

I had stopped using such an easy to guess subdomain "mail" or "webmail" for an email server rDNS in the begining of this century, which you compell to everyone to use it even today, because of the brute-force DNS cache poisoning attack scenario occuring at that time. 

Currently, I have not studied on the last security threads because I do not plan to use it in the future.

**Comment by ghost** [comment]
Markus, here is more official information:

Limitations for Universal SSL:
https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/limitations/

Here is information on the costs:
$10.00 / month
https://developers.cloudflare.com/ssl/edge-certificates/advanced-certificate-manager/

Or the second alternative:
Upgrade to a Business or Enterprise plan

**Comment by jaapmarcus** [comment]
First of all my first name is Jaap  and my last name is Marcus. Not Markus..

2. You can't use ssl from cloud flare In combination with mail servers the block by default  all the mail ports in that case you still need to use DNS only.  

As told if you want to use mail.vsp1.domain.com it should be possible  with: 
https://developers.cloudflare.com/dns/zone-setups/subdomain-setup/setup/

Unless you maybe use Cloudflare Tunnels and so on but it is not tested or even tried by me before. 

3. We have limited resources. And currently I am the most active person working on it and we need to set our priorities. It is opensource and I make almost 0 dollar / euro out of this project mean while I invest +10 hours a week into it. If we keep accepting all Feature requests all the request will pile up and never been worked on.  We currently have +50 000 servers running and this is the first time somebody asked for this feature.  I can spend my time on a feature more users want / need or spend my time 1 user need. Pick is easy made. 

4. Users can still nslookup mx records so changing it from mail to something random will help really not a lot.  Most bots come via ip address currently anyway...

**Comment by ghost** [comment]
Hello Jaap Markus!

**I am not interested to use** Sub.Subdomains.com or mail.vsp1.domain.com, regardless of Cloudflare. Suggestion on using mail.vsp1.domain.com is diversion of the issue.

**I am not interested to pay** Cloudflare.

**I am not interested to use**  the exclusive rDNS mail.domain.com enforced by you.

**I am not interested to use**  the exclusive subdomain webmail.domain.com enforced by you.

**However, I am only interested to use mail1.domain.com, mail2.domain.com and mail3.domain.com on different servers having different IPs**. To be able to use these three subdomaiins with different priorities and on different VPs is a fundamental need of every administrator running an email server. 

**It is a pathetic story to not being able to use this very basic and fundamental constellation**.

This is my last message.

**Comment by jaapmarcus** [comment]
> **However, I am only interested to use mail1.domain.com, mail2.domain.com and mail3.domain.com on different servers having different IPs**.

Please make the required changes and test it. And if it is working please submit a Pull Request. 
We are open for pull requests. How ever we don't plan to implement it our self if we need to make all the code changes.
