### ISSUE TITLE
[Feature] Only execute automated backups when sufficient space is available

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp#4161]
### Describe the feature or change in detail

Especially when an instance is not fully configured yet, we had the occurrence multiple times that the server ran full due to to insufficient space, creating a chain reaction of issues. Of course this should be treated and monitored at the root, but nonetheless some caution is useful.

I would propose the ability to configure which percentage of disk space needs to be free for automated local backups to run, configured by default at something like 90% usage.

One could alternatively check if the size of the user directory does fit onto disk, but if it fits just so and the disk consecutively runs full you run into issues nevertheless, so a buffer is sensible.

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by jaapmarcus** [comment]
Users are usually complaining the "check" requires too much free space....

Due to the following check that requires 2x the available user account system. 
https://github.com/hestiacp/hestiacp/blob/7a09373de3f05547ed2c2824eba8df807b50934a/bin/v-backup-user#L179-L182

With a lot of "small" accounts there might be still enough space to make the backup and it will become to full. How I wonder we need to fix the issue..

So there might be issues when 

```let v_disk=$(($(stat -f --format="%a*%S" $BACKUP)))/1024/1024```

returns a invalid value or an incorrect value this might be the issue when it mounted to the filesystem with cifs...

Also there might be an issue  when Rclone or sftp / ftp doesn't have enough if they have enough free space as we can't check how much free space on those system are availble...

**Comment by xeruf** [comment]
I think the issue on our system were multiple backups somehow running in parallel, I found some leftovers in `/tmp`

**Comment by Skamasle** [comment]
The remote systems space is not a hestia problem, hestia not need check that, sysadmin need take their own monitoring systems for this.
Just notify when get space error in NFS or remote system.

And in my opinion check  local free space per x2 is too much.

The most backup systems not care about the space used by account, just check if server have X% of freespace, like cpanel, plesk and orthers

Calculate the freespace for x2 is too much, maybe you have 40GB free space and account have a 40GB used spaces, but that account have a lot of logs or big TXT files or mysql use too much space, but we know that 10 GB logs is like 500MB compressed, same with mysql.

So too much servers may not backup some accounts because that not have x2 free space, but maybe server can store 2 o 3  backups of that big account with out any problem.

**Comment by jaapmarcus** [comment]
> The remote systems space is not a hestia problem, hestia not need check that, sysadmin need take their own monitoring systems for this. Just notify when get space error in NFS or remote system.
> 
> And in my opinion check local free space per x2 is too much.
> 
> The most backup systems not care about the space used by account, just check if server have X% of freespace, like cpanel, plesk and orthers
> 
> Calculate the freespace for x2 is too much, maybe you have 40GB free space and account have a 40GB used spaces, but that account have a lot of logs or big TXT files or mysql use too much space, but we know that 10 GB logs is like 500MB compressed, same with mysql.

But  on the other hand 30 gb of video files or images stay about the same..  So it hard to find a balance that works...

Also due to the if efficiency how the backups are created 
1. Create all files 1 to 1 to the backup folder
2. Then compress 
3. then do the other domains / items (Email / database)
4. Create a "tar" of the same backup
5. Delete the tmp folder

If somebody has an idea how to improve this calculation it is really appreciated. 

There is also a check if 95% or more is used on the backup drive an error is thrown..  So this issue can be closed...

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/9e12fe60e81758f45ed98892c052bc349c9ec417/func/main.sh#L37

and

https://github.com/hestiacp/hestiacp/blob/9e12fe60e81758f45ed98892c052bc349c9ec417/func/backup.sh#L31-L38
