### ISSUE TITLE
Feature Request: Possibility to add PHP Modules dynamicly.

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#417]
### In a few words, please describe the issue that you're experiencing:
I wasn't able to register on the forum as I never got an activation email, so ill ask the question here, Is there a way to install multiPHP after install of hestia.

### Operating system distribution and release:
Ubuntu 18.04.2 LXC / Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.1

### Which branch are you using?
Please enter your response here (e.g master, develop, etc.)

### Which of the following web server configurations are you using?
default

### Which of the following server roles are installed on your server?
default

**Comment by ghost** [comment]
Adding or removing server roles after the initial installation is currently unsupported due to the original architecture of the code base, and while running the installer script in `--force` mode with `--multiphp yes` might work it's likely to leave the server in an inconsistent state.

With that said, this functionality has been discussed internally on a few occasions and we would like to make the stack more modular in the future so that roles can be added or removed in a clean fashion.

**Comment by JOduMonT** [comment]
@kristankenney as I understood your comment: To have a stable server you would recommend to backup than reinstall and restore ?

**Comment by ScIT-Raphael** [comment]
If you have some linux sysadmin knowledge, you could try to add them on your own. Basicly the integration works with dpeca's way he posted here: https://forum.vestacp.com/viewtopic.php?t=17129

The templates u could find here: https://github.com/hestiacp/hestiacp/tree/master/install/deb/multiphp

**Comment by ScIT-Raphael** [comment]
We work on implement v-add-web-php and v-delete-web-php scripts to extend or remove php fpm versions and provide a better multiphp implementation. The work has been started under feature/web/AddPHPVersions branch and should be finished next week.

**Comment by ScIT-Raphael** [comment]
https://github.com/hestiacp/hestiacp/commit/529208a746fbc93f2eb908f3822d5dd956bff937#diff-695ad17dd48e6d51649d83033a1fd3fd
