### ISSUE TITLE
[Feature]  Add time zone setting

### ISSUE THREAD

**Issue by acastrovargas** [hestiacp/hestiacp#4284]
### Describe the feature or change in detail

Add time zone settings in the installation process, this can avoid problems in later processes.

Example : timedatectl set-timezone 'Asia/Kolkata'

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by Skamasle** [comment]
I give you my opinion about this:

In principle this is something that the sysadmin must assign when installing the server.

The panel can change the configuration, but the server is supposed to have its time zone correctly configured when installed.

It is like the network configuration, repositories, hostname, ssh port, root password, etc.

Can be done when panel installs? Yeah
Is it necessary and something that everyone needs? No since this is prior configuration of the server startup.

**Comment by jaapmarcus** [comment]
We don't touch the the time zone settings at al I don't see the need to do it during the server install.

**Comment by acastrovargas** [comment]
OK
