### ISSUE TITLE
[Feature] MariaDB incremental backup

### ISSUE THREAD

**Issue by schneiderbruno** [hestiacp/hestiacp#4326]
### Describe the feature or change in detail

Hi 

Is there any possibility of having incremental mariadb backups?

https://mariadb.com/kb/en/incremental-backup-and-restore-with-mariabackup/

I think that if this solution already exists in the mariadb core, natively, then there could be an option in hestiacp to enable/activate incremental backup.

As time passes, there is more and more data for backups, which increases the total time required to perform the backup.

Thanks

### Would you like to sponsor this feature to have it implemented?

Yes

**Comment by Skamasle** [comment]
This is not posible if not change entery backup systems

In any case you cannot backup just mariadb database in incremental way and compress all backup files, and use that system, so is incompatible with gziped backups because full backups will be deleted each time.

But, maybe you can backup just databases in incremental way and exclude databases from main backup, or include this in a restic backup system.
