### ISSUE TITLE
Feature Request: Reseller Level

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#436]
Add Reseller Level priviledged accounts.

**Comment by ScIT-Raphael** [comment]
Until now, we can't find enough time to develop and fullfill all feature request. I'll close this request for now,   if someone would like to do it on their own, just push a pull request - we will be happy for every contribution.

**Comment by xeruf** [comment]
Please use labels rather than closing issues if they are not actually resolved.
Also see the forum entry: https://forum.hestiacp.com/t/reseller-accounts-support/282

Anyways, we are a small hosting company eager for this feature as we are switching from liveconfig and would be up to sponsor it if we can find a good fit :)
