### ISSUE TITLE
[Bug] Spamhaus DNS-Resolver Blocks all incoming email

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#4366]
### Describe the bug

Spamhaus has started blocking public DNS servers when they do a lookup against their servers.

This means that Hestia installations that are hosed on places like Digital Ocean start blocking all incoming email

Suggest that either Spamhaus is replaced, or there is some GUI configuration for configuring a custom Spamhaus resolver.

### Tell us how to replicate the bug

Setup Hestia using a public DNS Server
Setup a domain with email
Try to receive email - it will always be rejected due to Spamhaus restrictions.

### Which components are affected by this bug?

Mail (Exim, Dovecot), Mail Security (Antivirus, Antispam)

### Hestia Control Panel Version

1.8.11

### Operating system

Debian 10

**Comment by jaapmarcus** [comment]
You are using an public ip resolver probally Cloudflare ...
https://hestiacp.com/docs/server-administration/email.html#rejected-because-ip-is-in-black-list-at-zen-spamhaus-org-error-open-resolver-https-www-spamhaus-org-returnc-pub-65-1-174-102

**Comment by tlcd96** [comment]
You should have given an input of the logs, replacing the domain and the machine name. I had this problem, if you didn't receive the email from zen.spamhaus then disable all blacklists and try again

**Comment by tlcd96** [comment]
on the file `/etc/exim4/dnsbl.conf`
```conf
bl.spamcop.net
zen.spamhaus.org
```
comment both lines and try again.
the file should look like this:
```conf
# bl.spamcop.net
# zen.spamhaus.org
```

and you should be able to send and receive emails especially from zen.spamhaus

**Comment by tlcd96** [comment]
> on the file `/etc/exim4/dnsbl.conf`
> 
> ```
> bl.spamcop.net
> zen.spamhaus.org
> ```
> 
> comment both lines and try again. the file should look like this:
> 
> ```
> # bl.spamcop.net
> # zen.spamhaus.org
> ```
> 
> and you should be able to send and receive emails especially from zen.spamhaus

One thing, this is not recommended, at least keep the zen.spamhaus.org blocklist. the other one blocks the zen blocklist

**Comment by jaapmarcus** [comment]
Don't use Cloudflare as DNS server and the issue is fixed. Or follow the docs to change it your self...

**Comment by nativ69** [comment]
I know this issue is marked as solved, but I wanted to add some relevant context:

It appears that Spamhaus is blocking DNS queries originating from public cloud providers whose nameservers are publicly accessible, such as Hetzner, OVH, and others.
For example, the Hetzner DNS server at 185.12.64.1 fails to resolve zen.spamhaus.org.

For a default installation, requiring each client to set up their own Spamhaus API key isn't ideal.
In my opinion, it would be better to switch to a different DNS-based RBL, such as b.barracudacentral.org or bl.spamcop.net, which don't have these restrictions.
