### ISSUE TITLE
Version is showing 1.0.2 but 1.0.2 has not been released yet

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#456]
### In a few words, please describe the issue that you're experiencing:
Just Installed a new hestia today and noticed version says 1.0.2 but this hasnt been released. My old hestia instance installed on 6-28 is still showing 1.0.1

### What steps did you take when the issue occured? 
1. Install Hestia
2. Login and configure version & release shows 1.0.2

### Expected behavior:
It shouls show 1.0.1 as 1.0.2 has not been released

### Operating system distribution and release:
ubuntu 18.04.2 LCX/Proxmox

### Which version of Hestia Control Panel is currently installed?
1.0.1 but says 1.0.2

### Which branch are you using?
release

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- MySQL (MariaDB)
- PostgreSQL

**Comment by ghost** [comment]
Did you use `wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install.sh` or `wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh`? That is likely why you're seeing a different version and likely other cosmetic differences with the installer. The packages in the repository are compatible, so you'll wind up on the latest stable build regardless. v1.0.2 is mostly bug fixes and further refinements.

We recently changed our development and branching process so that **master** is our primary development branch (formerly develop), **prerelease** is the next version being prepared for release, and **release** is the stable code branch (this used to be master).

**Comment by johnnyq** [comment]
ah gotchya I did do a wget https://raw.githubusercontent.com/hestiacp/hestiacp/master/install/hst-install.sh

I copied it from the main page of the site. I should have looked before i just copied and pasted hahaha

Well anyway to prevent other people doing the same thing update the site to reflect wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

I see the install instructions were updated on github README.md so thats good

Keep up the great work This is break through stuff! You guys really are putting a dent into web hosting control panels and are a great asset to the opensource community.
