### ISSUE TITLE
Feature Request: Allow Columns to be sorted by clicking on the column name

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#458]
### In a few words, please describe the issue that you're experiencing:
Allow the columns to be sorted by clicking the column name instead of the sort by drop down

**Comment by ghost** [comment]
Due to the limitations of the currently inherited front end architecture (which we've extended since forking from VestaCP), this is tricky to implement without causing the table header views to break -- however, we are planning an overhaul of the front end interface in the future and sortable columns will be available by default; closing this issue for the time being.
