### ISSUE TITLE
Proposition: hardening SSHd

### ISSUE THREAD

**Issue by JOduMonT** [hestiacp/hestiacp#487]
I saw Hestia chroot sftp, hide the banner, ... which is great

### but if I may suggest few more configuration based on Best Practice
1. Disable the `Compression no` because anyway it's only for SSHv1 and increase the attack surface ([ref](https://github.com/CISOfy/lynis/issues/217))
2. Reducing the `LoginGraceTime 1m`, some even recommend 30s ([ref](https://github.com/dev-sec/chef-ssh-hardening))
3. Disconnecting idle connection with ClientAliveInterval 600 and ClientAliveCountMax 3 ([ref](https://github.com/dev-sec/ansible-ssh-hardening#role-variables))
4. Limiting concurrent session with `MaxStartups 10:30:100`

### Also I would recommend to use a group instead of listing every user
`Match User sftp_dummy99,admin`
`Match Group ssh`

**Comment by ioannidesalex** [comment]
Hi jordumont and thanks for your suggestions. Please note the below:

1. Exactly like you said compression value is irrelevant since we use SSHv2. Thus, there is no benefit which justifies modifying a default value. We "mess" with users' configuration files when there is an added value.

2. I agree with you on this. LoginGraceTime can be reduced from the default 2m to 1m - 30s is a little bit extreme in my opinion.

3. I strongly disagree on this. It will be a nightmare for sysadmins and on a technical level doesn't really add to security.

4. MaxStartups is by default at 10:30:100 and I don't really think it's an unreasonable value.

It is worth to be mentioned that we implement fail2ban which per Hestia's default blocks anything more than 3 failed attemps from the same IP.

Regarding your suggestion about a group: I am not sure I understand what's the benefit of this - since we are not limiting anyone's access.

**Comment by JOduMonT** [comment]
3. is more to liberate resources used by idle connection than a security point but I understand I didn't regards all using case and only look a one or two ways to use SSH such as for file transfer and remote connection.

**Comment by ioannidesalex** [comment]
Thanks for your feedback @jodumont . LoginGraceTime has been reduced to 1m per your suggestion beginning from v1.0.2 on upgraded installations and from v1.1.0 on new installations.
