### ISSUE TITLE
Change font for HestiaCP

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#489]
The new font used in HestiaCP is a bit too small. It does save space but it still strains eyes a bit and the letters are not very clearly distinguishable. I have seen many sites adapt this font and have seen almost all of them leave it soon. Paypal was using the same font but when I logged into my account today, I see they changed it too.

Infact they used a font that was pretty good to read and caught my eye instantly... so I wanted to share the font.
https://klim.co.nz/custom-fonts/paypal-sans-small/

It really suits a "control panel" UI
Can the design team pls consider using this font in the next build ?

Many Thanks...

**Comment by ghost** [comment]
Hi @mehargags,

We'll be evaluating the font used in the Control Panel for a future release as it does appear to have some issues on Windows and Linux (but not macOS) where the lettering does not display correctly. Additionally, we'll be providing controls to scale the test for accessibility.

**Comment by mehargags** [comment]
I would suggest to use a built in universal Web Safe font that is supported by all major browsers on all major OS. Arial, Helvetica, Verdana would be my choice and I would strongly suggest not to include google or other CDN based external fonts.
Thanks

**Comment by ghost** [comment]
Hi @mehargags,

We're not relying on an external source for the font libraries used with in the Control Panel UI, they're self contained on the server as part of the installation.

**Comment by vvcares** [comment]
Yes. We feel the font is too stylish. Bit difficulty on eyes to read the texts, due to the font designed as sameheight/weight. 

Please just use Arial/Helvatica. 

Control panels no need stylish UI.
Also make it darker texts  
The icons also toooo lighter. 

Better let diff color, especially for DEL icon with RED color. So easy to see

**Comment by ScIT-Raphael** [comment]
Arial/Helvetica would not fit optically, design rework is in progress like @kristankenney mentioned already.

**Comment by hippi777** [comment]
hi there! :)

the ubuntu font is free and really impressive both for true-type and ordinary texts, and it also covers really much from the unicode chars. i think ive never seen any prettier fonts out there! :D 

otherwise, i was around when hestia have born, cuz i had a vesta related work, but ive never seen hestia, so could u add some screenshots? (beneficial for the project as well! :) ) i had to change the frontend to a custom one with some custom functionality here and there, so im interested in the outfit of hestia that much more :D 

bests! :)

**Comment by ghost** [comment]
We've changed the font back to the original "Exo" version instead of "Exo 2", the latter was supposed to offer cleaner rendering but we've found that to be the opposite. Additionally the font size has been increased so the combination of the improved rendering and size should help alleviate this issue. 

These changes will be made available starting with v1.1.0, in addition to basic support for themes/custom CSS override stylesheets which will allow you to customize the look and feel of the panel further.

**Comment by mehargags** [comment]
@kristankenney 
can you help us with a one-liner command that can replace the font to "exo" on are current servers pls... that'll be great

**Comment by ScIT-Raphael** [comment]
Basicly a search and replace in: https://github.com/hestiacp/hestiacp/blob/master/web/css/styles.min.css

But better wait for the theme implementation in release 1.1.0, then the change will not be overwritten during a upgrade.
