### ISSUE TITLE
Database Passwords wrong after v-restore-user

### ISSUE THREAD

**Issue by cmstew** [hestiacp/hestiacp#548]
### In a few words, please describe the issue that you're experiencing:

When I restore user backups, the database passwords for the user don't work anymore.

### What steps did you take when the issue occured? 
1. Ran v-restore-user username

### Expected behavior:
Database password to still function

### Operating system distribution and release:
Debian 9

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
After clean install, and restoring users.

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by johnnyq** [comment]
Hi @cmstew Please see [https://github.com/hestiacp/hestiacp/issues/415](https://github.com/hestiacp/hestiacp/issues/415) 
This is an inherited issue from VestaCP

**Comment by johnnyq** [comment]
@cmstew I should have asked, did the backup come from vestacp and then restored on hestiacp? If not what version of hestia did you do the backup on and what version of hestia did you restore to? For example did a backup on hestiacp 1.0.1 and restored to a clean install of hestia 1.0.4.

**Comment by cmstew** [comment]
Hey! Yeah, it's kind of related. Here's the breakdown.

Awhile ago I switched from Vesta to Hestia and had this problem with the restore. I thought it was my fault and just reset all the database passwords.

Yesterday, I broke Hestia and had to do a fresh install. I restored my backups from Hestia 1.0.4 and again had the database password problem.

At this point, I don't know if this is somehow still tied to the files originally coming from vesta, even though the restore was from a hestia backup. Or if it's a hestia problem.

**Comment by ScIT-Raphael** [comment]
@cmstew can you please review the following file and check, if the md5 hash is set properly?
`cat /usr/local/hestia/data/users/Your_User/db.conf`

**Comment by cmstew** [comment]
I just tried `cat /usr/local/hestia/data/users/*/db.conf` and each database has a unique MD5.

Here's a test I just did:

1. Create user 'temp'
2. Create Database user 'temp_temp'
3. Set password to 'temporary'
4. Backup user with v-backup-user temp
5. Delete user with v-delete-user temp
6. Restore user with v-restore-user temp
7. Try to login to database with username temp_temp and password temporary
8. Got this error: `mysqli_real_connect(): (HY000/1045): Access denied for user 'temp_temp'@'localhost' (using password: YES)`

**Comment by laraaj** [comment]
I just posted about this, for anyone dealing with this issue a quick work around is to set the old password for the database user manually either from HestiaCP webUI or commands after you restore the backup. this should work until the issue is fixed in HestiaCP.

**Comment by ScIT-Raphael** [comment]
Maybe the solution is here: https://github.com/serghey-rodin/vesta/issues/1962#issuecomment-566082382

**Comment by ScIT-Raphael** [comment]
*Closed by mistake, sorry :)

**Comment by joshbmarshall** [comment]
Hi @ScIT-Raphael it definitely would help you. I think that VestaCP is not by default running the latest MariaDB whereas I have upgraded myself. Since (looking at your install scripts) you install v10.4 of MariaDB by default then you will find that code will fix the problem. I hadn't tested in older versions of MariaDB but since you don't run older versions you might not have to ;)
I run a dockerized version of VestaCP with multiple PHP versions. I only just found out about HestiaCP and think I might be spending some time over the next few weeks making a dockerized version of HestiaCP to upgrade to :)

**Comment by ScIT-Raphael** [comment]
@joshbmarshall there is no need for a dockerized version, checkout the --multiphp installation flag :).

**Comment by joshbmarshall** [comment]
Ahh yes but I run a fleet of servers so deploying via docker is quick and consistent. I don't separate services in the "proper" docker style so all php versions are in the one container. Thanks for the note though, I'll definitely be using the multiphp :)

**Comment by ScIT-Raphael** [comment]
@cmstew this should have been fixed with the following commit: https://github.com/hestiacp/hestiacp/commit/402530a3c6d6ab7287ecdeb045c3f78fe58b9c28

Could you check that change when you've got some time? Please reopen the issue if the problem should be still persistent, on my side, this fix worked well.

**Comment by cmstew** [comment]
I just tried this out and the fix is verified working. Good work finding a fix everyone! :)

**Comment by crarchile** [comment]
Today I restored a backup made with vestacp 0.9.8.26 (Ubuntu 18.04)  into hestiacp 1.0.6 (Debian 9.11), from user 'admin' to user 'admin', from web 'abc.site.tld' to web 'abc.site.tld', and after testing the restored site on browser I get the error "CDbException CDbConnection failed to open the DB connection"  when I tried to open my Mailwizz site.

My solution to this issue was to change the password of the restored DB to the old password used by my app and the problem was solved !
