### ISSUE TITLE
Bug: www alias not created in some cases

### ISSUE THREAD

**Issue by ioannidesalex** [hestiacp/hestiacp#558]
### In a few words, please describe the issue that you're experiencing:
In case you add a domain test.co.uk or test.com.cy the www alias is not created by default.

### What steps did you take when the issue occured? 
Add web domain

### Expected behavior:
www alias should be added.

### Operating system distribution and release:
 Ubuntu 18.04.2 LTS

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
Both

### Which of the following web server configurations are you using?
- Nginx + PHP-FPM

### Which of the following server roles are installed on your server?
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
Can confirm this bug, we need to rework the subdomain check for such domain names.

**Comment by ghost** [comment]
The alias creation field has been moved from Advanced Options to the primary domain creation area, and automatic www. creation is now disabled due to the limitations with regional TLD's which was discussed internally today. (Commit: c009a6802e2462d3842f40dcb60d5346a6c670d8)

There will be a visual indication/reminder added to the Add Web Domain screen before the upcoming version ships, with necessary information/instructions being added to our documentation as well.

**Comment by ScIT-Raphael** [comment]
I just reopen and selfassign this issue, because I would like to rework this part with a checkbox for www alias on creation. This would make more sense instead disable the feature, usualy you want to have a www alias for normal domains.
