### ISSUE TITLE
Feature Request: multiple admin users

### ISSUE THREAD

**Issue by sydro** [hestiacp/hestiacp#636]
Possibility to add more admin users in addition to the default one.

**Comment by ghost** [comment]
Hi @sydro,

Sorry for the delay in responding to your feature request. The ability to add more admin users and also a reseller access hierarchy are on the project roadmap, but I don't have a timeline to share with you right now unfortunately as there will be a fair bit of work involved to make this happen due to limitations in the existing code base inherited from Vesta.

**Comment by ScIT-Raphael** [comment]
Due to the missing timeline, we will close this issue. All of the team would like to expand hestia to be able to handle multiple admin users and also maybe a reseller function. But both would need a rework of more than 80% of the code base - which will take a lot of time and man power.
