### ISSUE TITLE
v-restore-user only works with the backup in /backups

### ISSUE THREAD

**Issue by animeai** [hestiacp/hestiacp#641]
When importing backed up users, v-restore-user only works when the backup files are located in the /backups/ directory, even when full paths to v-restore-user and the backup file are used. The script simply gives an error of "invalid archive" if the backups are in another directory.

### What steps did you take when the issue occured? 
1. Log into SSH
2. Copy backup files from previous hestiacp or  vestacp install to a directory that isn't /backups/
3. Attempt to restore with v-user-restore

### Expected behavior:
Backup should import regardless of location or a more explicit error message should be generated.

### Operating system distribution and release:
Ubuntu 18.0.4 latest

### Which version of Hestia Control Panel is currently installed?
Latest release 1.0.6

### Which branch are you using?
Release

### When did this issue occur? After a clean installation, or after an upgrade?
Clean install, but presumably would occur on an existing install too.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ghost** [comment]
Hi @animeai,

Thanks for your issue report, much appreciated. We've been able to reproduce this internally and believe this behavior may also linked to the inability to properly move the backup storage location; the team is working on improving the backup system and its reliability before we ship 1.1.0 and will let you know when a fix is implemented.

**Comment by ifaist0s** [comment]
I'm not opening a new issue, because I think what I'm about to describe is related to what @kristankenney mentioned. If you think this deserves a new topic, please let me know.

In one Hestia server (identical specs as @animeai ), I have changed the location of the backup folder. In that specific installation, it is impossible to download the backup files from Web UI. When clicking on the icon to download the backup file, a blank page is displayed.

**Comment by theotherpeople** [comment]
Solved here:
https://github.com/serghey-rodin/vesta/pull/1975

**Comment by ScIT-Raphael** [comment]
Hi @theotherpeople 
Thanks for pointing us to the fix for ftp, I've added it with the following commit: https://github.com/hestiacp/hestiacp/commit/ed0f00a1ab88a33a3f470e484e9cb596ae662442

But it's just a partitial fix for ftp based restores, there is still a issue with restoring it from cli with another location than /backup.

**Comment by ScIT-Raphael** [comment]
We just discussed this in our dev chat: We're going to leave it like it is - a backup should be placed in /backup, then restored from there.

**Comment by wojsmol** [comment]
@ScIT-Raphael Then male sure that this information is added to the documentation.

**Comment by ScIT-Raphael** [comment]
@wojsmol good idea, expanded the text.
