### ISSUE TITLE
upgrade from vestacp

### ISSUE THREAD

**Issue by Wqrld** [hestiacp/hestiacp#657]
is it possible to upgrade from vestacp to this? this looks more actively maintained and i'd be happy to help with the development and also get more people to use it.

**Comment by ScIT-Raphael** [comment]
Thanks for your question! We do not provide or support a migration from a running vesta to hestia system, due to the mass of changes we did. But you can restore vesta backups using v-restore-user script directly to hestia.

For every help with the development we're very grateful, just push a pull request or a issue, we will check them asap.
