### ISSUE TITLE
Restoring from Vestacp 

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#676]
### In a few words, please describe the issue that you're experiencing:

when Restoring the backup from Vestacp it doesn't update the DNS IP (it shows the old IP of the server) and everything imports properly expect MySQL password. 

### What steps did you take when the issue occured? 

 I just need to re-enter the password via the panel for MySQL and it works fine.

### Expected behavior:

when importing the backup from vestacp it should put the new IP address in DNS records instead of showing old IP of the server and MySQL password should restore correctly.

### Operating system distribution and release:
Ubuntu 18.04.3

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
The mysql password issue has already been fixed: https://github.com/hestiacp/hestiacp/issues/548#issuecomment-569330180

I'll check the dns issue, don't know if a direct ip replacement is a good idea, because we do not know the old ip of the server. So we would also overwrite other dns zones which would have another ip address from a external service.

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/72202502-47051980-3486-11ea-9040-cda577dacf7f.png)

**Comment by ScIT-Raphael** [comment]
I just rechecked the restore commands and can confirm, that it worked porperly on my side.

**Explanation of dns ip replacement**
Here, we will load the dns conf file and grab the "old" ip: https://github.com/hestiacp/hestiacp/blob/d69add31e64ef7da2d4e022fbad8da3c38b3742b/bin/v-restore-user#L489

After IP validation, we will do a sed replacement for old to new ip address here: https://github.com/hestiacp/hestiacp/blob/d69add31e64ef7da2d4e022fbad8da3c38b3742b/bin/v-restore-user#L517-L519

I can't find any issue in this procedure, is it possible, that the main ip was different than for the oder records (like TXT/IMAP/POP) you had there?

Due to the fact, that I wasnt able to reproduce this issue, I'll close it. Please feel free to answer it and also create a new issue, if there occurs any other bug.
