### ISSUE TITLE
Emails not going to AOL and Yahoo

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#697]
### In a few words, please describe the issue that you're experiencing:

When i try to send email to AOL or Yahoo i get 

Warning: message 1ixkzu-0001ep-Ga delayed 72 hours. 
This message was created automatically by mail delivery software.
A message that you sent has not yet been delivered to one or more of its
recipients after more than 72 hours on the queue on s1.b2btech.in.

The message identifier is:     1ixkzu-0001ep-Ga
The date of the message is:    Sat, 1 Feb 2020 10:37:02 +0530
The subject of the message is: Testing from b2bTech.in

The address to which the message has not yet been delivered is:

  alber@yahoo.com
    host mta5.am0.yahoodns.net [67.195.204.72]
    Delay reason: SMTP error from remote mail server after pipelined MAIL FROM:<alber@b2btech.in> SIZE=1659:
    421 4.7.0 [TSS04] Messages from 104.225.221.17 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html

No action is required on your part. Delivery attempts will continue for
some time, and this warning may be repeated at intervals if the message
remains undelivered. Eventually the mail delivery software will give up,
and when that happens, the message will be returned to you.

 

### What steps did you take when the issue occured? 

I tried sending the email to another provider like gmail and webmail and it works perfectly fine and it's not even going on SPAM Folder and the PTR Record is already set. 

### Expected behavior:

Should send mails to yahoo and aol without any issues. 

### Operating system distribution and release:
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-76-generic x86_64)

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by tudorr89** [comment]
Seems that your IP is grey/blacklisted for sending to yahoo. The error specifies it clearly:
`421 4.7.0 [TSS04] Messages from 104.225.221.17 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html`

You might want to check your IP against MXToolbox, it has nothing to do with HESTIA what so ever.

**Comment by alber-khan** [comment]
![image](https://user-images.githubusercontent.com/39749258/73732435-2fa50d80-4760-11ea-9f28-1dc3dfb7ccf3.png)

it's not blacklist! :/

**Comment by tudorr89** [comment]
I've checked it [here](https://www.dnsbl.info/dnsbl-database-check.php) and [here](http://mail-blacklist-checker.online-domain-tools.com/) and it does appear, so you might want to address that.

In the meantime, you could use sendgrid or mailgun as a SMTP relay for EXIM until your IP gets whitelisted again. There's thread on [vestacp](https://forum.vestacp.com/viewtopic.php?f=12&t=8861) forums about how to set it up.

Good luck!

**Comment by alber-khan** [comment]
Another thing I notice is 

remote_smtp:
  driver = smtp
  helo_data = mail.${sender_address_domain} 

// the helo_data  is set for each domain but it should set to the hostname of the server as the IP can be assigned to a hostname only? (PTR Record)  

![image](https://user-images.githubusercontent.com/39749258/73749459-70614e80-4781-11ea-839e-e68767d890bf.png)

![image](https://user-images.githubusercontent.com/39749258/73749579-a9012800-4781-11ea-93e8-a0c2248b6288.png)

**Comment by ScIT-Raphael** [comment]
Doesnt mean when yahoo blocks you, you're on a blacklist - it depends on their way how to receive/accept emails. This issue is not hestia related, as @tudorr89 requested it would be a solution to switch to a smtp service like mailgun or filter out why yahoo doesnt accept your communication - usualy this depends also about your ip address or range, sending emails is a bit a weird  thing. You can also expect that emails will go to spam folder on O365 services randomly.

About mail.${sender_address_domain}, this value is correct, because it depends on the domain you send. As you already get a 10 out of 10 on mailtester, you're anyway good to go.

Due to the fact that it isnt hestia related, I'm going to close this issue. Thank you for your understanding!
