### ISSUE TITLE
SMTP AUTH Required when sending from another server using same domain

### ISSUE THREAD

**Issue by jaiume** [hestiacp/hestiacp#714]
### In a few words, please describe the issue that you're experiencing:
When sending to an email address that is in a domain hosted by Hestia (or Vesta) from the same domain (or address) but from a different server, the message is rejected with the message SMTP AUTH REQUIRED.

It seems this logic in the exim.conf.template is what governs this behaviour

deny    message       = smtp auth required
            sender_domains = +local_domains
            !authenticated = *

There are situations where you need to send to a Hestia hosted domain from the same domain, but from a different server.

Safeguards could be checking the SPF record for the domain to see if the host is an authorized sender.

### What steps did you take when the issue occured? 
1. Send a message to a Hestia hosted email address from the same address from a different server

### Expected behavior:
Email will be accepted

### Operating system distribution and release:
Debian 9.12

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
Release

### When did this issue occur? After a clean installation, or after an upgrade?
After clean install

### Which of the following web server configurations are you using?
- Apache + Nginx (default)

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by ScIT-Raphael** [comment]
Hi @jaiume 

Thanks for the issue report, after a short check using telnet, I can confirm this behaviour. I'll discuss this with our core devs if we're able to solve it.

**Comment by ioannidesalex** [comment]
I am not sure whether disabling SMTP AUTH should be an option. You can always use SMTP auth from your other server to send emails.

**Comment by ScIT-Raphael** [comment]
I confirm the view of @ioannidesalex, also I think you've got only one mail location and do not share a domain over multiple servers.

**Comment by jaiume** [comment]
I think this is not a good conclusion to this issue.

The SPF framework as well as other mail security and identity frameworks explicitly allow for the situation where multiple servers can send on behalf of a domain.

I don't think the issue is about disabling SMTP AUTH.

There must be a less dangerous  method of allowing the receipt of a email sent from a different server but the same domain.

Thanks
Jamie

**Comment by ioannidesalex** [comment]
@jaiume find the below line at your exim conf - /etc/exim4/exim4.conf.template and amend accordingly, based on your needs:

hostlist relay_from_hosts = 127.0.0.1 : yourotherip1 : yourotherip2

After that, restart exim and try again. Let us know if it works for you as it should please.

**Comment by jrohde** [comment]
I know this is long closed, but the issue is still here i'm afraid (sorry).
The answer given above works, but it is more of a workaround then a real solution.

I also have multiple external services / mail servers sending out e-mail 'in name of' my domain(s). Think of services like mailing lists (mailchimp, etc..) and electronic invoicing. SPF records are set for these service in the DNS, so they are allowed to do this. Now these mails will go out to the whole world, except to myself and other users on the hestiaCP server the mail domain is hosted, because of the required SMTP AUTH. Disabling the required AUTH is not really an option. Setting IP's manually - like advised above - is very tricky, because i don't control those IP's (if they change, the conf is useless). Also there might be other people on the server using external services sending out e-mail for them of which i have no knowledge and so no IP's (and even if i knew, that would be a very cumbersome administration).

I think the best solution is to rewrite the ACL so SPF is taken into account.
The current ACL responsible for blocking SPF passed hosts is:

```
deny    message       = smtp auth required
         sender_domains = +local_domains
         !authenticated = *
 ```
 
Somehow SPF validated (/passed) hosts should be excluded from this ACL, but until now i've no idea how to do this. I've tried adding the SPF setup from here: https://www.sidn.nl/en/modern-internet-standards/hands-on-implementing-spf-dkim-and-dmarc-in-exim, hoping to get a ```$spf_result``` var which i could use in this ACL, but it resulted in lots of errors (probably it's to old and/or my exim setup is missing the SPF libs). I've spend hours online searching for someone with a similar issue, but failed miserably (??). Since i'm a complete noob regarding Exim (always used Postfix), I hope there's some Exim guru in here who might have a real solution and/or direction to search for?!
