### ISSUE TITLE
Feature Request: Mobile-friendly design

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#747]
It would be amazing if HestiaCP has a mobile-friendly design!

**Comment by ghost** [comment]
Hi @itstnt,

Thanks for your feature request. We're constantly working on user interface improvements with each release, and a mobile-friendly interface is on our roadmap for a future version. I can't commit to a specific date yet, but will update you when I have more to share.

**Comment by Skamasle** [comment]
In general way I think ( personal opinion ) hestia design is very ugly, remember me web site in  year 2003.

I think you need remove gradients in bars and buttons.

**Comment by ScIT-Raphael** [comment]
@Skamasle well, it is still based on vesta and due to the fact how the current stack is built, we're very limited :). @kristankenney did already a great job with the lot of improvements and fixes that where done on the current version. The only way to gain a new, fresh design with mobile compatibility is a complete rewrite from zero - for this we just dont have enough man power yet.

**Comment by Skamasle** [comment]
I know, I not say this is bad work, I just say is a lite ugly with gradients or instead of that it looks too old, If you remove gradients you get a fresh look or a "modern" but this is only my personal opinion.

**Comment by ScIT-Raphael** [comment]
If you would like to share a own template with us, checkout the theme function (v-add-sys-theme). You can adjust it like you want and share it with us over a pull request :).

**Comment by Lupul** [comment]
@Skamasle with release v1.1.0 there was a new theme added called 'flat' , have you checked it out?

**Comment by ScIT-Raphael** [comment]
Closed due to inactivity, redesign is on roadmap.
