### ISSUE TITLE
Cosmetics - Redirect back after adding a Mailuser

### ISSUE THREAD

**Issue by gOOvER** [hestiacp/hestiacp#782]
When adding a Mail User, you will not redirected to /list/mail/?domain= back. You stay on "Add User"

I think, this is not really a Bug. More Cosmetics. There are some other Parts, where you are not redirected back

**Comment by jaapmarcus** [comment]
It is actually almost on almost all forms.  I think it's more a personal opinion what you need / want. 

For error reporting and display the success the current system is easier to make and build. Also when you need to add multiple "accounts"

**Comment by gOOvER** [comment]
> It is actually almost on almost all forms. I think it's more a personal opinion what you need / want.
> 
> For error reporting and display the success the current system is easier to make and build. Also when you need to add multiple "accounts"

Thats why i labeled Cosmetics :)

I'm really new with Hestia and in a Test Phase. Maybe I'm a little spoiled from my long way during all OpenSource Panels starting from VHCS -> ispCP -> i-MSCP -> ispconfig3 (my actual)

**Comment by ScIT-Raphael** [comment]
As @jaapmarcus the redirect is a point of view (and also as you did :)). It is set that you can create multiple accounts without clicking everytime on "new" and will stay like it is.

**Comment by gOOvER** [comment]
As is said; funny how feature requests handled ;) Looks like, that hestia is only for the "HARDCORE" Users and not for other users. If you want to be OpenSOurce, learn how to admit such Requests. Now what are u doing is stupid, sorry.

I will think about to use Hestia. 

Thank for giving me this decision ;)

//Edit German

Ist das die Schweizer Neutralität oder werden wirklich nur Hardcore User für Verbesserungen berücksichtigt?

Sry, aber das ist doch sinnlos; wer macht denn 100te von FTP Accounts oder Domains oder eMail Adressen? In meinen Augen sinnlos, weil vorallen kein wirklicher Back Button da ist.

Aber so wie es aussieht, hat Hestia sich eh erledigt für mich ;) 

Wieder so ein Projekt, wo ein sehr junger Entwickler, ohne wirklcihe Ahnung der OpenSource Community, mit einem kleinen Projekt, versucht fuss zu fassen als Referenzprojekt. ;) Klappt nicht mit Deiner Einstellung ;)

Vorallem, wenn man sich anschaut, wie die Entwicklung verläuft; Corona und plözlich geht alles. WIe ist es nach COrona; dann schläsft es wieder ein wie es sie letzten 6 Monate war ;)

**Comment by ScIT-Raphael** [comment]
To be honest: You flamed me first, for giving not a clear answer, now you got one and flaming me for giving a direct answer? Don't get it.

It's the current way, how hestia handles the things - I discussed this with our core team and we decided to not change it - that's all. That has nothing to do with hardcore users nor anything else - this is just a clear decission that we do not want to change it.

We do all a hard work here, it's a free to use software - you are free to have your own mind as we have our own decission, accept it or leave it - that's the way it works.

As you already wrote, you don't wanna use hestia, and that's more than ok for me - it is your decission, not mine. Also I do not know what this multi nationality project should have together with switzerland and network neutrality - just because I'm the one who provides you the answer for your request.

**Comment by gOOvER** [comment]
I never flamed you, but you have no knowlegde how to handle such an OpenSource FORK Project. Not more ;) If you can't deal with criticism, that's not my problem ;) Then you must learn it ;)

All Enhancement will be closed, because, i'm a NEW User and HARDCORE USers have more voice in here.

I have my opinion now from this Project and i will others never Recommend this project, as long one og the Leaders have not the knowlegde to admin such a project. 3 Monats and it's dead again. Like your Fork ;)

You are young and you should first learn the basics to admin such a Community ;)

**Comment by ioannidesalex** [comment]
Dear gOOvER, thanks for your feedback.

This is an open source project, managed by a team. Everyone is free to contribute and raise their voice, however certain decision are taken by the team - exactly the same concept like all open source projects (eg. Canonical & Ubuntu).

As far as I understand, you proposed a change of functionality regarding the add a mailuser function. We discussed your proposal internally and democratically decided that we shouldn't change the behavior of the function. I really don't understand why you are trying to force HestiaCP to fullfil your own individual needs, when the majority thinks otherwise.

If you have seen the already closed issues, you will notice that many of them are implemented. Feedback and suggestions are more than welcome, in fact we actively encourage those. Pull requests are even more appreciated, since it's very easy to ask for things, while doing nothing to assist in the development of the project.

Afterall, everyone here is giving their precious time for free, without expecting anything in return. The minimum they expect is to not being insulted and some appreciation for the work they do. 

There are many hosting panels available, feel free to check the althernatives and choose the one that fits you best and use that one.

**Comment by gOOvER** [comment]
Thank you for your Answer.

I started 2 Enhancements Ticket. First was closed and after close he said, he did't read it correct. 2nd ok, this was only cosmetics. ANd then i flame him? Sry this guy should learn criticism. 

But pls teach your young guy @ScIT-Raphael in adminstration of Tickets. see below.

I had also a lot to learn, when i manage the Community of a Big OpenSource Server Panel (Over 10k Installations nd a Userbase over 3k)  like yours. And it was a hard time ;) 

OpenSource Project lives from Guys which post Bug, enhancements or Feedback. In this point you are right. But with such answers like from @ScIT-Raphael , you only pollute the users. It looks like, you are not really intressted in new Users, which want to help, like me. I'm really new, installed it today. 

For me it really looks like, that you don't want feedback. 

And when u want Feedback, only from "Old" Users ;)

**Comment by ioannidesalex** [comment]
Of course we want feedback, new users, as well as testers. The project is pretty new so there is no such thing as "old" users. Fresh ideas are always welcome, but please learn to accept a "no" as well for an answer. It's not something personal :)

**Comment by gOOvER** [comment]
> Of course we want feedback, new users, as well as testers. The project is pretty new so there is no such thing as "old" users. Fresh ideas are always welcome, but please learn to accept a "no" as well for an answer. It's not something personal :)

I accept a No, but i don't accept things like; i flame him. Sorry, but this is not the Way that a Team Member should talk. @ScIT-Raphael must learn a lot and start talking in a nice way. Also start reading Tickets correct. 

Such an OpenSource Project is not a Springboard for young guys to a better life ;) Potential employers also look at tickets and how to deal with them.

So stop discussing of that and try to teach @ScIT-Raphael ;) 

btw: TLong discussion, easy Solution:

Add a checkbox, when you want to add more than 1 ;)

Checkbox unchecked -> redirect back
Checkbox check -> Add & add & add as much you want

**Comment by ioannidesalex** [comment]
Your feedback is appreciated. Have a nice weekend ahead.

**Comment by jaapmarcus** [comment]
In the Dark template there is all ready back button on most pages (except index pages) 

If it's not in the default theme it would be nice add-on. 

How ever I don't see any reason to alter de default behaviour. 

Also there are a lot of feature requests and less time to complete all of them there is limited time to do it.  At some moments there are decisions to be made. 

How ever to compare it even with paid control panels in that I have used this is a very basic one but with great possibilities to change any thing what you want.

**Comment by gOOvER** [comment]
> Also there are a lot of feature requests and less time to complete all of them there is limited time to do it. At some moments there are decisions to be made.

Thats the Way an OpenSource Project should go. And Github Ticket have so much Power to handle this, insteed of closing ;) Why closing it, insteed of adding a Tag "Future Realease" or something else ;) Better than closing in 5 mins ;) 

So it looks as if no feedback is desired

As i said; someone need to learn how to handle a community ;)

**Comment by ioannidesalex** [comment]
Thanks for your feedback @gOOvER !
