### ISSUE TITLE
Feature Request: Install MySQL instead of MariaDB

### ISSUE THREAD

**Issue by sebasira** [hestiacp/hestiacp#821]
Hi guys! According to https://github.com/hestiacp/hestiacp/issues/800 it should be possible to install MySQL v5.7 instead of MariaDB...

I'm struggling with that and don't know what else to do. I'm with a fresh new DigitalOcean droplet, Ubuntu 18.04

I've installed HestiaCP with this command:

> bash hst-install.sh --mysql no

After successful installation I reboot and then when I try to install MySQL with:

> sudo apt update && sudo apt install mysql-server

I get the following error:

>Setting up mysql-server-5.7 (5.7.30-0ubuntu0.18.04.1) ...
/var/lib/dpkg/info/mysql-server-5.7.postinst: line 191: /usr/share/mysql-common/configure-symlinks: No such file or directory
dpkg: error processing package mysql-server-5.7 (--configure):
 installed mysql-server-5.7 package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 mysql-server-5.7
E: Sub-process /usr/bin/dpkg returned an error code (1)

I have try it several times even destroy and create new Droplets because I was messing with the configuration. I've try purge and remove commands I found but I always get the same. Could you please guide me? (I'm not a sysadmin so if you could guide me as a child it would be nice)

Thanks!

**Comment by sebasira** [comment]
After lots of trial and error I manage to make it work removing dependencies:

```
apt remove roundcube-mysql

sudo apt remove exim4-daemon-light

sudo apt remove mysql-common

apt remove mariadb-common

sudo apt install mysql-server-5.7

apt-get install mysql-common --reinstall

apt remove mysql-* mariadb-* --purge

sudo apt install mysql-server
```

My question now is... As you can see, I've removed **roundcube-mysql** and **exim4-daemon-light**... Can I just re-install them and all will be fine? Or do I need to configure or better say re-configure them?

**Comment by ScIT-Raphael** [comment]
As I wrote in #800 I'm "nearly sure" that it should work doesnt mean it works. Also infact you write that you are not a sysadmin, I'm not sure if it is a good idea at all - hestia's configuration does stick on mariadb, mysql is not tested - so there may occure additional problems which to handle.

If you want to add mysql, I would have started to adjust the hestia installer, remove the mariadb repository and replace the mariadb server packages in installation process with them from mysql. If you "just" install hestia without mysql, the system will anyway not be properly configured and you could not manage the databases from the backend/interface. You'll find the installer files here, take either the debian or ubuntu one: https://github.com/hestiacp/hestiacp/tree/release/install

I'll leave this ticket open to discuss with the team, if we would expand hestia to support both - mariadb and mysql.

**Comment by sebasira** [comment]
Thank you very much @ScIT-Raphael!

I hope you can support both in the future! I've been using Vesta for years and I'm moving to Hestia because of the active development and I think it has better features, and I've decided to give it a try

**Comment by mahdiyari** [comment]
FYI, I installed MySQL 8 with docker and adjusted a few configurations in Hestia, PHPMyAdmin, and Roundcube.
Everything looks fine.

**Comment by sebasira** [comment]
@mahdiyari would yo mind sharing those configurations? I've installed MySQL v5.7 would that be the same?

If not, would you share the whole process? I could uninstall v5.7 and move to 8 if required

**Comment by mahdiyari** [comment]
It's not easy for normal people and may break Hestia. But you can figure it out if you are advanced enough.
I just confirmed that MySQL 8 works with Hestia so devs can check that out.

**Comment by ScIT-Raphael** [comment]
Hi @mahdiyari 

It would really help us if you can share your modifications and installation steps, so we can check if we would be able to implement it into the installer.

**Comment by devilstars** [comment]
What is the reason heatia uses mariadb by default? It doesn't even support json fields :/

Was unable to replace mariadb with mysql so I had to switch back to vestacp

**Comment by kpapad904** [comment]
It probably won't solve your issues with MySQL 5.7, but have you tried the 2-step method (first do CREATE USER ... and then do GRANT ALL ...) offered in a recent Vesta PR for MySQL 8 compatibility ?

https://github.com/serghey-rodin/vesta/pull/2012/files

**Comment by archergod** [comment]
I too love to see Mysql, infact it can ask for option in setup to install either. I think it won't effect much.

**Comment by jaapmarcus** [comment]
In a future release we working on a module based install. So it would be come easier to create a "module" for it.

**Comment by sg3339** [comment]
Hi. Any news on the module installer? Or can anyone share what changes are needed in the configuration for the panel to work correctly with mysql?

**Comment by devilstars** [comment]
Any updates on this? 26.01.2021 - Mariadb 10.5 still has no native JSON support.

**Comment by ScIT-Raphael** [comment]
Currently, there is no update on that feature request. We currently don't have enough man power to fullfill it yet, if you're interrested to have a look, please feel free to modify the installer script and check if you can solve it.

**Comment by user746655** [comment]
> What is the reason heatia uses mariadb by default? It doesn't even support json fields :/
> 
> Was unable to replace mariadb with mysql so I had to switch back to vestacp

I'd also like to understand the reasoning behind mariadb as default over MySQL. I was excited to install HestiaCP and move my sites today, but as I started the installer I noticed that MariaDB was listed and there was no option to select which DB server could be installed. A big let down. I will have to stick with VestaCP for now. I just don't understand the logic behind this decision, if the point was to move people away from VestaCP and on to a better platform that is more actively maintained. 

This seems like a big turn-off for many. I hope this is being actively looked into. Seeing the comments from others, it doesn't seem all that difficult. I would assume the team could provide two separate install scripts depending on which DB you wanted to use. I will be watching this thread, but sadly, I have to stick with VestaCP for now and I cannot recommend the move to this platform to others.

**Comment by ScIT-Raphael** [comment]
@user746655 I see a long text, but I don't see why you would like to stick on mysql? Due to the current exploits, I strongly suggest to accept mariadb (for now or have a look on our forum, a user installed mysql) and proceed with hestia.

**Comment by devilstars** [comment]
MySQL has JSON type support. MariaDB - doesn't. Ok, for some reason someone
from hestia devs does not like mysql... Well, there is percona db. It is as
good as mysql and it is much better than mariadb. Weird decisions from
hestia devs and no solutions :/

ср, 14 апр. 2021 г., 22:06 Raphael Schneeberger ***@***.***>:

**Comment by ScIT-Raphael** [comment]
We do not not like mysql, we just havent had enough time to check for a solution. It's an opensource project, if you like to see mysql support, feel free to adjust the installer and provide a pull request. We will implement it for sure after validation and testing.

**Comment by user746655** [comment]
Thank you for the post. You've hit the nail on the head. This is precisely the question I have. I'm not sure why I would or wouldn't want to stick with MySQL. The reasons for why I would, is because its what I have today. There needs to be a reason for why I would want to switch. As the developer and designer of the platform, I think you could easily explain the point you just made and then it would make more sense. 

In other words, if there is some security concerns or performance concerns and MariaDB is the solution for the future, then that makes sense and I think I would definitely be happy to move. I think a simple KB doc or explanation on this would be helpful for those that don't know about the security concerns and reasoning to be educated and then be happy to move. I'm one of those persons and I assumed that could be the reason why MariaDB was chosen (but again, it was not explained anywhere in the installer or even in this thread until your last comment. 

Also, as I read through this thread (and bc I'm unaware of the security concerns), I was looking for a reason for why not to proceed with Maria. And then I read several posts about JSON and not supporting. I'm not sure if this matters to me, but again its another thing that raises a flag. And since I don't know enough about this topic to know whether its in my best interest to move forward, I cannot make a decision. I also don't know if my MySQL database files can easily just be dumped and migrated to the new server with MariaDB and all my Wordpress sites will work as they have. 

I understand you are trying to make a better platform and this may be the reason you choose MariaDB, but these things need to be explained if they are different from where people are coming from, otherwise you will be challenged to get user adoption. I'm trying to help the cause, as VestaCP is dead and no help intheir forums, so I want you to succeed. So please take these comments as advice and a 3rd party perspective. I look forward to seeing what comes out of this and hopefully to get my sites over to a better platform.

**Comment by devilstars** [comment]
I'm not DevOps, I'm a casual consumer of the product. All I want - is
ability to choose DB type, it's just a feature request.

For now I use PostreSQL, as there are no more options for me

ср, 14 апр. 2021 г., 22:17 Raphael Schneeberger ***@***.***>:

**Comment by user746655** [comment]
btw, sadly, while I was writing this comment, I had a fresh install of a digitalocean droplet on Ubuntu 20.04 LTS and the HestiaCP installer did not complete successfully. No idea, I assume based on the website that 20.04 is supported. I literally just created the droplet, logged in with my SSH key and ran the wget command and bash command to run the script, so no idea how the installer would fail if it was test for Ubuntu 20.04LTS, I will try creating the droplet again and attempting a second time.

**Comment by jaapmarcus** [comment]
So far I know Hestia is an open source project. Everybody can make this future and make a pull request with all the changes he / she want. If they are decent we might be included.

**Comment by ScIT-Raphael** [comment]
@user746655 I just can suggest to install hestia, take a vesta backup and restore it in hestia. Then you can see if all works as expected.

**Comment by ScIT-Raphael** [comment]
> btw, sadly, while I was writing this comment, I had a fresh install of a digitalocean droplet on Ubuntu 20.04 LTS and the HestiaCP installer did not complete successfully. No idea, I assume based on the website that 20.04 is supported. I literally just created the droplet, logged in with my SSH key and ran the wget command and bash command to run the script, so no idea how the installer would fail if it was test for Ubuntu 20.04LTS, I will try creating the droplet again and attempting a second time.

Please reach out in our forum for support, i can suggest to run a apt update && apt dist-uograde prior to the install.

**Comment by ScIT-Raphael** [comment]
Just checked mariadb for json and found this: https://mariadb.com/kb/en/json-data-type/

As far as I understand, not a pro at all in mysql, mariadb supports json but you need to do some adjustments.

**Comment by user746655** [comment]
> Just checked mariadb for json and found this: https://mariadb.com/kb/en/json-data-type/
> 
> As far as I understand, not a pro at all in mysql, mariadb supports json but you need to do some adjustments.

Thanks @ScIT-Raphael! That did the trick. I created a new droplet with Ubuntu 20.04 LTS and after logging in I ran:

`apt update && apt dist-upgrade`

And then proceeded with downloading the install script and running with -f force command. This was needed as the installer complained of the group admin account. It would be very helpful if these kind of things could be posted in a FAQ section with a link posted directly under the install instructure page here (https://hestiacp.com/). I'm sure it would save you time answering questions to people like me in the future. ;)

Thanks again, I will now try to do the backup and importing it to see how things go. Fingers crossed. ;)

It might also be a good idea to write up a post comparing MariaDB and MYSQL and provide that link as well on the install Welcome page of your website. I think that's why DigitalOcean grew so well. Because of the online KB and user community. It seems like HestiaCP is trying to cultivate the same experience. I loved the fact that I got a quick response here. Keep up the great work!

**Comment by ioannidesalex** [comment]
Thanks a lot for the feedback. However, with that logic the team should explain to people why use nginx as proxy, why use Ubuntu & Debian, why SpamAssassin and the list goes on.

MariaDB is an open source project compared to MySQL and according to several benchmarks a faster one. It was founded by the creator of MySQL, after Sun was acquired by Oracle. It's a drop in replacement so it doesn't cause any issues (even the commands in the CLI are "mysql <command>" and not "mariadb".

There are many tutorials online directly comparing MySQL and MariaDB. After all its an open source project. The team decided that this should be the default an they moved forward with it. That's all. That's the beauty of open source and afterall the team is spending their personal time to develop this product. Nobody forces anyone to use HestiaCP, nobody asked for any compensation for the work they do.

Feel free to submit a PR giving users the option to select and after it has been checked it could be merged to Hestia's codebase.

**Comment by user746655** [comment]
Thanks for the comment. And my feedback is just to provide another perspective and hopefully avoid you guys having to explain the reasoning to others in the future. After all, it does seem like this topic has generated enough interest to get several people talking about it. I tend to disagree regarding the logic. I don't think the comparison is the same. As users coming from VESTACp are all familiar with the default install of nginx as proxy, spamassassin, etc. The main difference is MariaDB vs Mysql, and as that's part of the core (AMP), I think it warrants a bit of explanation. It would probably have prevented this thread from starting. 

Anyway, just trying to save you guys time going forward. You have already convinced me to give it a go, I will trust your judgement on the decision as part of the project. I was just looking to try to understand the rationale and reasoning given it's a new DB server for me and others also expressed interest to not use it. In fact, to spend time hacking up the install script to install it, so there must be some reason and enough attention. 

Anyway, I get it. You guys want to go that route, which is perfectly fine. I think it just helps to explain one time in a clear and concise way, why it was decided and avoid any further decision on the topic. Thanks again, this has been a learning experience. And now that I have finally fixed a broken backup process on my VestaCP server, I can no finally try to import that backup to my newly installed HestiaCP server. What a headache that was. Wasted another 2 hrs of my time. I look forward to seeing how Hestia runs after I import. 

Thanks and keep up the great work! It's appreciated!

**Comment by FalzoMAD** [comment]
> I'm a casual consumer of the product

and this is, where you @devilstars miss the point. 

HestiaCP is not a product and we are not trying to sell you anything. in return we only expect you to understand and accept, that we have no obligation to please anyone. 
it's completely your choice: use it as it is, make it better by bringing your own work and efforts, or just leave it. 🤷‍♂️

the idea behind HestiaCP never was to drive people from Vesta over. while we suggest to not use Vesta anymore for obvious reasons (not maintained, high risk for unknown security holes), this does not mean we need or want any user to blindly switch to HestiaCP instead. we have no interest in being a competition to any other panel, paid or not.

the development of HestiaCP is driven by a bunch of admins that use it themselves on a daily basis and the very egocentric motivation is to make _our_ lifes easier with it in the first place. so obviously we will choose and support software/components/extension that _we_ like to use and feel comfortable with. 
and even then it does not mean, we all think it's better or not, just that we all have no trouble working with it and do not have a need for any alternative.

however, please try to understand that we do not need or convince anyone to like what we do or use it/want it/praise it. it would simply be much appreciated if you refrain from demanding things. 
of course you can request features, but doing so by questioning our choices/motives and calling the decisions 'weird' and such makes it sound a bit offensive and obviously won't earn you anything. 😉

all that said some last words regarding Vesta and the always upcoming 'but Vesta did it this way' - do not expect Hestia to stay 'compatible' forever. the difference between the projects is growing and at some point there will be no need for us to further maintain or support a migration path at all. why? same reason as above, if the dev team itself does not have any Vesta servers anymore to migrate from, there is no need to put any more work into backwards compatibility.

those who still need or want that will then have to step up and build something themselves. script, fork, PR, whatever - it's open source and can be your own project!

**Comment by devilstars** [comment]
> Just checked mariadb for json and found this: https://mariadb.com/kb/en/json-data-type/
> 
> As far as I understand, not a pro at all in mysql, mariadb supports json but you need to do some adjustments.

MariaDB implements JSON as a LONGTEXT. 
MySQL implements JSON as a... JSON. 

And this is a huge disadvantage of MariaDB, because such a clean and neat query is not possible with MariaDB:
```
return $query->where('biodata->personal->income', '>=', $minIncome);
```

**Comment by devilstars** [comment]
> and this is, where you @devilstars miss the point.

I just want to indicate that the wrong choice of services (MariaDB as main DB) used was made and even explained why it is. What to do with this information - decide for yourself.

**Comment by FalzoMAD** [comment]
> decide for yourself

yes, thanks. this is what we did and why our choice of services cannot be wrong for _us_ and I even explained why that is. I agree it might be a wrong choice for _you_ though, but you are free to decide for yourself to not use it then ;-)

**Comment by devilstars** [comment]
> his is what we did and why our choice of services cannot be wrong for _us_

yep, but the service you make is for everyone, because it is... in public repo? Also you didn't provide any pros of using mariadb as the default DB as well as you didn't provide any choice for... everyone?

**Comment by jaapmarcus** [comment]
The development for HestiaCP has only **one** purpose to help **us** the development team with automating the simple daily tasks that we **require** to do. 

The only reason why Hestia exists that we **depend** on a **safe** control panel and we don't like the current available options. 

In stead keeping it closed source we have decided it to keep it fully open source and share it with everybody out of here to use it for free. We don't require anything we supply regular updates for free and even give free support who needs it. If this is not enough please create your own panel.

If you would like to change something there are currently 3 options:

1. Do it your self everybody can make fork our project and submit any changes we will review those changes and decide if it is worth putting it in
2. Hire a developer who do the tasks above. 
3. Accept it that it might take some time that it will get implemented / or even accept it it will never get implemented. 

If option 1 and 2 is not an option only 3 is left. And just stick with it. 

We get multple feature request and we can't complete them all.  And for Mysql vs MariaDB 99% MariaDB is more than enough and won't require the json field. And if they really need it there are probably other better options available.

**Comment by FalzoMAD** [comment]
> but the service you make is for everyone, because it is... in public repo? Also you didn't provide any pros of using mariadb as the default DB as well as you didn't provide any choice for... everyone?

sorry, but I think your logic is very flawed here. 

because something is on a public repo does not mean we 'make' it for everyone. it simply means everyone is free to look at it and is then provided with the most obvious choice of all: use it or do not.

concluding that because it is available for everyone we need to provide (specific) choices for everything that somes with it is quite a stretch. but even then: you do not have to use the installer as it is. that is the beauty of open source. 
everyone is provided with the choice to use it as it is or to tailor it to their needs.

see @jaapmarcus response: 1/2/3 options to go with and make a _choice_ and that is provided to everyone _because_ it's a public repo and open source. you are totaly free to do it differently, fork it, change it, make it a better fit for your need. 

with that said I kindly request you to stop the discussion here and we will do the same. we will update this FR if anything related to it will change or someone provides a proper PR and we can think about fulfilling this wish at some point.

**Comment by ScIT-Raphael** [comment]
Just placing it here so it doesnt get lost: https://forum.hestiacp.com/t/change-mariadb-to-mysql/1193/9

**Comment by ScIT-Raphael** [comment]
We decided to not implement this feature request from our side, because we do not use mysql and have the point, that mariadb is a proper replacement for it. If someone wants to see this feature, please provide a PR with the related changes to both installers - in my post above, there are some first points what is needed to change.
