### ISSUE TITLE
Letsencrypt ssl cert update issue when hosting 2 domains named example.com and example.com.cctld

### ISSUE THREAD

**Issue by kpapad904** [hestiacp/hestiacp#893]
The wildcard used in bin/v-delete-web-domain-ssl line 63

This issue seems to affect HestiaCP as well:
https://github.com/serghey-rodin/vesta/issues/1977

and proposed fix:
https://github.com/serghey-rodin/vesta/pull/1978

**Comment by ghost** [comment]
Hi @kpapad904,

Thank you for your report. Are you able to confirm on your side 100% that this issue also affects Hestia?

With changes that we made to the file system structure last year, SSL certificate files are kept in separate directories at a per-domain level as per line 63 in v-delete-web-domain-ssl:
`rm -f $HOMEDIR/$user/conf/web/$domain/ssl/$domain.*`

Note the difference compared to the original code block in VestaCP, where the `web` folder contains _all_ of the SSL certificates:
`rm -f $HOMEDIR/$user/conf/web/ssl.$domain.*`

Based on this, wildcard deletion of the SSL assets for one domain shouldn't have an effect on other similarly named domains with different TLDs. Please let us know your findings and thanks again. :)

**Comment by kpapad904** [comment]
Indeed HestiaCP is not affected.

PS: That should teach me not to open issues at 4:00am, particularly when I haven't slept at all during the past 48 hours :-)

**Comment by kpapad904** [comment]
Hi @kristankenney , since you mentioned changes to the file system structure, does HestiaCP offer some documentation similar to VestaCP's https://vestacp.com/docs/#config-log-location-debian-ubuntu ?

**Comment by ghost** [comment]
> Indeed HestiaCP is not affected.
> 
> PS: That should teach me not to open issues at 4:00am, particularly when I haven't slept at all during the past 48 hours :-)

Thanks for the update, and no worries -- it happens to the best of us, haha.

While we don't currently have an updated chart showing log and configuration file locations at this time, most paths should still fairly accurate for Hestia (and they haven't changed too much at this point). For example, you'll find that domains are under `/etc/apache2/conf.d/domains/*` specifically instead of ``/etc/apache2/conf.d/*` for Apache, and the same applies with NGINX; also replace any references of "Vesta" with "Hestia".
