### ISSUE TITLE
Possible Bug: apt-transport-https probaly missing on fresh installation

### ISSUE THREAD

**Issue by ScIT-Raphael** [hestiacp/hestiacp#910]
According to the following forum thread (https://forum.hestiacp.com/t/debian-buster-new-install-error/1229) a user wasnt able to install hestia properly, debuging showed that the package apt-transport-https was missing.

Probaly we need to verify if the package check is working properly: https://github.com/hestiacp/hestiacp/blob/ce5f4b8499556a86c63bc2a155144986cade1f9d/install/hst-install-debian.sh#L334-L339

OS: Debian 10 / Buster
Hestia: 1.2.0

**Comment by vestacp-user** [comment]
All those pre-checks and `apt install...` in the installer (Line 313 to 346) are cute, but useless.  They are actually worse than uselless, they are quite bug-prone because they look for specific executables in specific locations which changes over time and over releases and may be difference accross distros.

The installer is just doing work that apt was designed to do.   Just do:

```
echo "[ * ] Checking and Installing Pre-Installation Requirements."
apt-get -y install apt-transport-https dirmngr gnupg ntpdate wget >> $LOG
check_result $? "Pre-Installation failed, please review the logs"
```
I put the packages in alphabetical order to make it easier to read, but apt-get doesn't care, it will resequence the actual install besed on dependencies.  And even for gnupg, you don't even have to specify gnupg vs gnupg2 because the Distros take care of all that with dummy transitional packages.  See: 
https://packages.debian.org/buster/gnupg
https://packages.debian.org/buster/gnupg2

You can offload all this work and code from the Hestia project to the Distros.  If you really **need** to have cute messages to say exactly what was installed (no one should care since they are supposed to start from a clean install, then you can parse the apt-get output.  Admins that want to know what was installed can simply go read the Hestia install log or  `/var/log/apt/history`

**Comment by vestacp-user** [comment]
I assume the project team already knows this, but just to demonstrate in case, if you run that command on a successfully installed HestiaCP 1.2.0, you get the following (see below).  The point being that apt-get can very easily do all that work that the installer currently does.  There is no point in having code in HestiaCP to do what apt-get is designed to do.
```
apt-get -y install apt-transport-https dirmngr gnupg ntpdate wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dirmngr is already the newest version (2.2.12-1+deb10u1).
dirmngr set to manually installed.
gnupg is already the newest version (2.2.12-1+deb10u1).
ntpdate is already the newest version (1:4.2.8p12+dfsg-4).
wget is already the newest version (1.20.1-1.1).
apt-transport-https is already the newest version (1.8.2.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by vestacp-user** [comment]
I just tested a fresh Debian 10 minimal install and it does not have apt-transport-https installed, but *does have a `/usr/lib/apt/methods/https -> http` symlink.  

This is a perfect demonstration of what I explain above, the install script's prerequisites check fails where single apt-get with all pre-installation requirements would work.

**Comment by ghost** [comment]
Closing issue report as per PR #997.
