### ISSUE TITLE
Disable TLS below 1.2 for TLS services by default? (mariadb, proftpd, exim4, dovecot, etc)

### ISSUE THREAD

**Issue by ghost** [hestiacp/hestiacp#950]
I found these lacking in this department so I decided to disable TLS older then 1.2 and the remaining weak ciphers (according to SSL labs anyway). Is this something we would want for the default installation? I can work on a PR if it is.

**Comment by ghost** [comment]
I just thought maybe it's time to bite the bullet on this since browsers are already planning to disable anything below TLS 1.2 and most other clients should be capable of TLS 1.2 by now.

**Comment by ioannidesalex** [comment]
Hi @braewoods , we have disabled anything older than TLS 1.2 in webservers (browsers), including hestia-nginx . We have also disabled anything older than TLS 1.1 in all other services as well.

We have kept though TLS 1.1 for mail services (at least for now), since there are old mail servers out there that aren't upgraded to the latest standards and this might cause a big trouble/hustle with non delivered emails to users mailboxes.

Regarding FTP, I guess we might disable TLS 1.1 as well. We are already using strong ciphers there.

Regarding MariaDB, we aren't configuring TLS/SSL by default, since our default behavior is to bind MariaDB to localhost and block via firewall all remote, incoming connections. So I guess it's up to the sysadmin that wants to enable remote connections how he/she wants to deal with TLS/SSL.

The above statements are mostly my personal opinion :)

**Comment by ghost** [comment]
I had read that too but if that's the case it would mean they're too old to support TLS 1.2, no? Email is strange at times. At the very least we could probably switch the dovecot POP3 and IMAP services to TLS 1.2 minimum since that's not going to impact the ability to send or receive email since that's the job of SMTP. Either way it's a topic for another day I'm sure. I have higher priority things I'd like to contribute first.

**Comment by ronald-at** [comment]
I disabled TLS 1.1 on exim and dovecot on my server nine month ago, which is running eight domains at the moment. I've never had complaints of any user, who had problems sending or receiving emails, which was related to TLS problems. So in my opinion TLS 1.1 could be disabled also on services related to email.

**Comment by ioannidesalex** [comment]
One of the issues I have noticed is that older OS don't support the parameter "ssl_tlsv1_1=NO" for vsftpd.

Similar issues to Dovecot where "ssl_protocols" (2.2) has been replaced with "min_ssl_protocol" (v2.3).

I hope I will find some time to do more on this later (compatibility along all supported OS), however, please feel free to submit your PRs.

**Comment by ghost** [comment]
That's not even in the vsftpd upstream source. I found out that's only available when the CentOS patch is applied for it. But there's still a portable method for disabling TLSv1.1. You can disable it with some clever usage of the ciphers list. For that matter this method makes all those explicit disable options redundant.

**Comment by ioannidesalex** [comment]
Thanks @braewoods . Use of stronger ciphers, practically disabling TLS v1.1 will be implemented at a next release.

Thanks for the tip!

**Comment by jaapmarcus** [comment]
#2012 for mail everything else is disabled already.
