### ISSUE TITLE
Theme Documentation. 

### ISSUE THREAD

**Issue by archergod** [hestiacp/hestiacp#967]
I see the Add theme Command, but it look for Github repo (as per comment) which is fine. But what I don''t get it what file structure we use there? 

I look for pre-existing theme, but didn't find one. Can someone guide through how to make theme for it. Maybe just put some basic theme in git repo and we replicate it our design.

**Comment by jaapmarcus** [comment]
We currently only support a theme by changing the css files 

https://github.com/hestiacp/hestiacp/blob/main/bin/v-add-sys-theme to install the css file 



CSS file can be found on 
https://github.com/hestiacp/hestiacp/blob/main/web/css/src/styles.css

Currently we overwrite certain css style via  css see: 

https://github.com/hestiacp/hestiacp/blob/main/install/deb/themes/dark.css or 
https://github.com/hestiacp/hestiacp/blob/main/install/deb/themes/flat.css

Any changes to the html template files will be overwritten by a new update.

**Comment by archergod** [comment]
Well, I try to use `v-add-sys-theme`, but it fails

Steps I followed:

* Copy `/usr/local/hestia/install/deb/themes/dark.css` to `/opt/dark2.css`
* Make my modifications
* run `#v-add-sys-theme dark2 local active`. Command ask for path I type `/opt/dark2.css` it shows no message and prompt again. I thought it is success. 
* Go to Panel, All themes from dropdown are gone and my changes are not reflected.
* Use `v-delete-sys-theme` to remove dark2 and all default themes comes back. 
* I copy dark2.css to themes folder manually, it is now listed, but my changes are still not reflected. 

I am using Digital Ocean's VPS with Ubuntu 20.04 LTS. that is freshly installed and just default installer of Hestia I am trying to setup new server

**Comment by ScIT-Raphael** [comment]
basicly, use v-add-sys-theme dark2, it should create all needed folders and default files - the you can replace them.

EDIT: Seems not to work as suggested, doing further checks herre.

**Comment by jaapmarcus** [comment]
Have the same issue.

**Comment by jaapmarcus** [comment]
There where some changes in our template system see https://github.com/hestiacp/hestiacp/commit/42ef7ffbee940326d14718a8e9402f20c9c2bdcd#diff-363c077474575eabca85fd7428109aa0 Don't know this is currently in the "release" branch.

How ever this will be fixed the next release.

To test I used the following command:

`touch jaap.css`
Make my changes in this case:
```
.body-login, .body-reset {
    height: auto;
    padding-top: 10%;
    background: rgb(231, 102, 194) !important;
    background: radial-gradient(circle, rgba(231, 102, 197, 1), rgba(174, 43, 177, 1)) !important;
}
```

Then entered the following command.  
```
root@dev:~# v-add-sys-theme jaap local
Please enter the full path to the CSS file to import: /root/jaap.css
```
https://github.com/hestiacp/hestiacp/blob/main/bin/v-add-sys-theme

Active flag is currently ignored 

Reload login page and the changes where made :)

The list function should be fixed with 
https://github.com/hestiacp/hestiacp/pull/969 or this commit https://github.com/hestiacp/hestiacp/pull/969/commits/06d8bb142749d1959a474654991a24b983e894f6

**Comment by jaapmarcus** [comment]
Updated basic information. Please not it only applies for 1.2.1 for 1.2.0 please force reload by clear caches
