### ISSUE TITLE
Install Script forcing sshd_config "PasswordAuthentication yes".  What breaks with "PasswordAuthentication no"?

### ISSUE THREAD

**Issue by vestacp-user** [hestiacp/hestiacp#978]
Has there been any discussion about fact that the install script forces "PasswordAuthentication yes" in the install script and if that is still necessary?  (This is also the default with a Debian 10 system.)   HestiaCP seems to have full support for SSH Keys via the web interface, so I am trying to find what gets broken in HestiaCP with "PasswordAuthentication no" in `/etc/ssh/sshd_config`

**Comment by ScIT-Raphael** [comment]
There was no discussion yet, you just started it - thanks for that :).

I also think the line isnt needed anymore, but I also have to do some checks why we implemented it there or if it was a takeover from vesta. Give me some time for it, maybe you're even faster than I.

**Comment by jaapmarcus** [comment]
Using PasswordAuthentication no since my first Hestia install. Thats why I created the SSH key changes ...

It is al ready since creating the hestia installer. Think it is save to use the "system" preferences.  We maybe need to fix the issue for the new sftp jail  for "additional ftp accounts"

https://github.com/hestiacp/hestiacp/commit/d46ec4374d5da97f02d809285fc27d498a2cf312#diff-e0798b087fbb2ffd7cf5ffd4565cc08e

**Comment by jaapmarcus** [comment]
Also applies to Ubuntu 

https://github.com/hestiacp/hestiacp/blob/b27cc6625a5abb6245d3bcdbd1f1d4db4f7cb6f2/install/hst-install-ubuntu.sh#L918-L926

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/pull/980

**Comment by jaapmarcus** [comment]
I think we can safely say it can be closed...
